:_mod-docs-content-type: PROCEDURE

[id="installing-tks-clone"]
= Installing TKS clone

Follow this process to install a TKS subsystem as a clone of an existing TKS subsystem.

Prior to installation, ensure that the xref:../others/installation-prerequisites.adoc[Installation Prerequisites] are configured.

== Exporting existing TKS system certificates

On the existing system, export the TKS system certificates with the following command:

[literal]
....
$ pki-server tks-clone-prepare \
    --pkcs12-file tks-certs.p12 \
    --pkcs12-password Secret.123
....

The command exports the following certificates (including the certificate chain) and their keys into a PKCS #12 file:

* subsystem certificate

* audit signing certificate

Note that the existing SSL server certificate is not exported.

If necessary, third-party certificates, for example trust anchors, can be added into the same PKCS #12 file with the following command:

[literal]
....
$ pki -d /var/lib/pki/pki-tomcat/conf/alias -f /var/lib/pki/pki-tomcat/conf/password.conf \
    pkcs12-cert-import <nickname> \
    --pkcs12-file tks-certs.p12 \
    --pkcs12-password Secret.123 \
    --append
....

== Installing TKS subsystem

Prepare a deployment configuration, for example `tks-clone.cfg`, to deploy TKS subsystem clone. By default the subsystem is deployed into a Tomcat instance called `pki-tomcat`.

A sample deployment configuration is available at xref:../../../base/server/examples/installation/tks-clone.cfg[/usr/share/pki/server/examples/installation/tks-clone.cfg].

It assumes that the:

* Primary CA and TKS are running at https://primary.example.com:8443.

* CA signing certificate has been exported into `ca_signing.crt`.

* Admin certificate and key have been exported into `ca_admin_cert.p12`.

* PKCS #12 password is specified in the `pki_client_pkcs12_password` parameter.

See xref:../ca/installing-ca.adoc[Installing CA] for details.

To start the installation execute the following command:

[literal]
....
$ pkispawn -f tks-clone.cfg -s TKS
....

== TKS system certificates

After installation the existing TKS system certificates (including the certificate chain) and their keys are stored in the server NSS database (i.e. `/var/lib/pki/pki-tomcat/conf/alias`), and a new SSL server certificate is created for the new instance:

[literal]
....
$ certutil -L -d /var/lib/pki/pki-tomcat/conf/alias

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

ca_signing                                                   CT,C,C
subsystem                                                    u,u,u
tks_audit_signing                                            u,u,Pu
sslserver                                                    u,u,u
....

If necessary, the certificates can be exported into PEM files with the following command:

[literal]
....
$ pki-server cert-export <cert ID> --cert-file <filename>
....

The valid certificate IDs for TKS are:

* `tks_audit_signing`
* `subsystem`
* `sslserver`

Note that the `pki-server cert-export` command takes a certificate ID instead of a nickname. For simplicity the nicknames in this example are configured to be the same as the certificate ID.

== Admin certificate

To use the admin certificate, do the following.

. Import the CA signing certificate into the client NSS database:
+
[literal]
....
$ pki nss-cert-import --cert ca_signing.crt --trust CT,C,C ca_signing
....

. Import admin certificate and key into the client NSS database (by default ~/.dogtag/nssdb) with the following command:
+
[literal]
....
$ pki pkcs12-import \
    --pkcs12 ca_admin_cert.p12 \
    --pkcs12-password Secret.123
....

. To verify that the admin certificate can be used to access the TKS subsystem clone, execute the following command:
+
[literal]
....
$ pki -n caadmin tks-user-show tksadmin
---------------
User "tksadmin"
---------------
  User ID: tksadmin
  Full name: tksadmin
  Email: tksadmin@example.com
  Type: adminType
  State: 1
....
