#!/bin/bash
# BEGIN COPYRIGHT BLOCK
# (C) 2010 Red Hat, Inc.
# All rights reserved.
# END COPYRIGHT BLOCK

##
## Include common 'compose' functions
##

COMPOSE_PWD=`dirname $0`
source ${COMPOSE_PWD}/compose_functions


## Always switch into the base directory three levels
## above this shell script prior to executing it so
## that all of its output is written to this directory

cd `dirname $0`/../..


##
## Retrieve the name of this base directory
##

PKI_PWD=`pwd`


##
## Establish the 'pki-tks' name and version information
##

PKI_TKS="pki-tks"
PKI_TKS_VERSION="9.0.9"


##
## Establish the SOURCE files/directories of the 'pki-tks' source directory
##

PKI_SPECS_FILE="${PKI_DIR}/specs/${PKI_TKS}.spec"
PKI_COMPONENT_LIST="tks"


##
## Establish the TARGET files/directories of the 'pki-tks' source/spec files
##

PKI_PACKAGES="${PKI_PWD}/packages"
PKI_TKS_BUILD_DIR="${PKI_PACKAGES}/BUILD"
PKI_TKS_RPMS_DIR="${PKI_PACKAGES}/RPMS"
PKI_TKS_SOURCES_DIR="${PKI_PACKAGES}/SOURCES"
PKI_TKS_SPECS_DIR="${PKI_PACKAGES}/SPECS"
PKI_TKS_SRPMS_DIR="${PKI_PACKAGES}/SRPMS"

PKI_TKS_TARBALL="${PKI_TKS}-${PKI_TKS_VERSION}.tar.gz"
PKI_TKS_SPEC_FILE="${PKI_TKS_SPECS_DIR}/${PKI_TKS}.spec"
PKI_TKS_PACKAGE_SCRIPT="${PKI_PACKAGES}/package_${PKI_TKS}"
PKI_TKS_PACKAGE_COMMAND="${RPMBUILD_CMD} SPECS/${PKI_TKS}.spec"

PKI_TKS_STAGING_DIR="${PKI_PACKAGES}/staging"
PKI_TKS_DIR="${PKI_TKS_STAGING_DIR}/${PKI_TKS}-${PKI_TKS_VERSION}"
PKI_TKS_BASE_DIR="${PKI_TKS_DIR}/base"


##
## Always create a top-level 'packages' directory
##

mkdir -p ${PKI_PACKAGES}


##
## Always create 'pki-tks' package directories
##

mkdir -p ${PKI_TKS_BUILD_DIR}
mkdir -p ${PKI_TKS_RPMS_DIR}
mkdir -p ${PKI_TKS_SOURCES_DIR}
mkdir -p ${PKI_TKS_SPECS_DIR}
mkdir -p ${PKI_TKS_SRPMS_DIR}


##
## Always start with new 'pki-tks' package files
##

rm -rf ${PKI_TKS_BUILD_DIR}/${PKI_TKS}-${PKI_TKS_VERSION}
rm -f  ${PKI_TKS_RPMS_DIR}/${PKI_TKS}-${PKI_TKS_VERSION}*.rpm
rm -f  ${PKI_TKS_SOURCES_DIR}/${PKI_TKS_TARBALL}
rm -f  ${PKI_TKS_SPEC_FILE}
rm -f  ${PKI_TKS_SRPMS_DIR}/${PKI_TKS}-${PKI_TKS_VERSION}*.rpm


##
## Copy a new 'pki-tks' spec file from the
## current contents of the PKI working repository
##

cp -p ${PKI_SPECS_FILE} ${PKI_TKS_SPECS_DIR}


##
## If specified, copy all Patches from the spec file URL to SOURCES
##

if [ ${FETCH_PATCH_FILES} -eq 1 ] ; then
	Fetch_Patch_Files ${PKI_SPECS_FILE} ${PKI_TKS_SOURCES_DIR}
fi


##
## Copy the specified Source Tarball from the spec file URL to SOURCES, or
## Generate a fresh Source Tarball from the local source
##

if [ ${FETCH_SOURCE_TARBALL} -eq 1 ] ; then
	Fetch_Source_Tarball ${PKI_SPECS_FILE} ${PKI_TKS_SOURCES_DIR}
else
	##
	## Always start with a new 'pki-tks' staging directory
	##

	rm -rf ${PKI_TKS_STAGING_DIR}


	##
	## To generate the 'pki-tks' tarball, construct a staging area
	## consisting of the 'pki-tks' source components from the
	## current contents of the PKI working repository
	##

	mkdir -p ${PKI_TKS_DIR}
	cd ${PKI_DIR}
	for file in "${PKI_FILE_LIST}" ;
	do
		cp -p ${file} ${PKI_TKS_DIR}
	done
	find ${PKI_CMAKE_DIR}             \
		-name .svn -prune -o          \
		-name *.swp -prune -o         \
		-print | cpio -pdum ${PKI_TKS_DIR} > /dev/null 2>&1
	cd - > /dev/null 2>&1

	mkdir -p ${PKI_TKS_BASE_DIR}
	cd ${PKI_BASE_DIR}
	cp -p ${PKI_BASE_MANIFEST} ${PKI_TKS_BASE_DIR}
	for component in "${PKI_COMPONENT_LIST}" ;
	do
		find ${component}             \
		-name .svn -prune -o          \
		-name *.swp -prune -o         \
		-print | cpio -pdum ${PKI_TKS_BASE_DIR} > /dev/null 2>&1
	done
	cd - > /dev/null 2>&1


	##
	## Create the 'pki-tks' tarball
	##

	mkdir -p ${PKI_TKS_SOURCES_DIR}
	cd ${PKI_TKS_STAGING_DIR}
	gtar -zcvf ${PKI_TKS_TARBALL}    \
		"${PKI_TKS}-${PKI_TKS_VERSION}" > /dev/null 2>&1
	mv ${PKI_TKS_TARBALL} ${PKI_TKS_SOURCES_DIR}
	cd - > /dev/null 2>&1


	##
	## Always remove the PKI staging area
	##

	rm -rf ${PKI_TKS_STAGING_DIR}
fi


##
## Always generate a fresh 'pki-tks' package script
##

rm -rf ${PKI_TKS_PACKAGE_SCRIPT}
printf "#!/bin/bash\n\n"                >  ${PKI_TKS_PACKAGE_SCRIPT}
printf "${PKI_TKS_PACKAGE_COMMAND}\n\n" >> ${PKI_TKS_PACKAGE_SCRIPT}
chmod 775 ${PKI_TKS_PACKAGE_SCRIPT}


##
## Automatically invoke RPM/SRPM creation
##

cd ${PKI_PACKAGES} ;
bash ./package_${PKI_TKS} | tee package_${PKI_TKS}.log 2>&1

