#!/usr/bin/expect -f

set force_conservative 0  ;# set to 1 to force conservative mode even if
                          ;# script wasn't run conservatively originally
if {$force_conservative} {
        set send_slow {1 .1}
        proc send {ignore arg} {
                sleep .1
                exp_send -s -- $arg
        }
}

set timeout 50
spawn /usr/bin/passwd
match_max 100000
#send -- "passwd root\r"
expect "password: "
send -- "redhat\r"
expect "password: "
send -- "redhat\r"
expect eof
