= Dogtag PKI Documentation Convention

Due to style and format requirements of downstream docs, please follow the following convention when editing or adding Asciidoc files.

See installation/ca/installing-ca.adoc for example.

== Convention ==

* File naming convention
** use hyphon ('-') instead of underscore ('_')
** all lower cases
** bears extension .adoc
** no articles (e.g. 'a', 'the')
* Add header including the “id” line at the very beginning of the file, using the file name. e.g.
** :_mod-docs-content-type: PROCEDURE
** <blank line>
** [id="installing-ca"]
** Do not add any comment or blank lines between the id line and the subject header line (the line begins with a '=') that it's supposed to anchor.
* Do not refer to a section as “page”.  If applies, try using the word "section".
* when referencing another documention:
** If it's outside of this github pki repo, use `link:`
** If it's within this github pki repo, use `xref:`
* Do not use “e.g.”.  Use “for example” instead
* Quoted blocks (“....” v.s. “----”)
** Use “....” for commands or other smaller blocks
** Use “----” block brackets for code blocks or content of a file such as pkispawn cfg file samples
** Add the following line above beginning of each block:
*** [literal]
* use a pair of backticks around words that are literal such as file names or commands
* do not use future tense (e.g. 'will', "will be", etc.).  Use present tense instead.
* Create PR and request for reviews from members of the dogtag pki team (and doc team if applicable)

== Upstream->Downstream Import File Lists ==

The following are lists of files that are currently imported downstream. Be aware that you are updating any of the files listed in the lists below and the changes affect any of the downstream release, you need to follow the internal inport instructions.

* xref:include-install.list[include-install.list]
** contains a list of selected installation methods adoc files from `pki/docs/installation`.
* xref:include-cfg.list[include-cfg.list]
** contains a list of selected pkispawn .cfg files from `pki/base/server/examples/installation`
* xref:others.list[others.list]
** files (currently just `pki/docs/admin/configuration-for-server-side-keygen.adoc` and the 3 image files that it references) that are manually imported
