#!/bin/bash
# BEGIN COPYRIGHT BLOCK
# (C) 2008 Red Hat, Inc.
# All rights reserved.
# END COPYRIGHT BLOCK

# Always switch into this base directory
# prior to script execution so that all
# of its output is written to this directory
cd `dirname $0`

# Retrieve the name of this base directory
PKI_PWD=`pwd`

# Name and location of the SVN external properties DB.
SVN_EXTERNAL_PROPERTIES_DB_LOCATION="${PKI_PWD}"
SVN_EXTERNAL_PROPERTIES_DB_NAME="base_svn_external_properties_db"
SVN_EXTERNAL_PROPERTIES_DB="${SVN_EXTERNAL_PROPERTIES_DB_LOCATION}/${SVN_EXTERNAL_PROPERTIES_DB_NAME}"

# Always make sure that the SVN external properties DB exists.
if [ ! -f ${SVN_EXTERNAL_PROPERTIES_DB} ]; then
    printf "The SVN external properties DB called '${SVN_EXTERNAL_PROPERTIES_DB}' does NOT exist!\n"
    exit 255;
fi

# Specify the location and a list of the SVN components that
# require these SVN external properties to be updated.
SVN_COMPONENTS_LOCATION="${PKI_PWD}/.."
SVN_COMPONENTS="ca common console java-tools kra manage migrate native-tools ocsp osutil ra setup silent symkey tks tps util"

# Change directory to the location of all of these components,
# and execute the defined SVN external property changes.
cd ${SVN_COMPONENTS_LOCATION}
for SVN_COMPONENT in ${SVN_COMPONENTS} ; do
    if [ -d "${SVN_COMPONENTS_LOCATION}/${SVN_COMPONENT}" ]; then
        printf "Setting external SVN properties for the component called '${SVN_COMPONENT}' . . .\n"
        cd "${SVN_COMPONENT}"
        svn propset svn:externals -F "${SVN_EXTERNAL_PROPERTIES_DB}" .
        svn propget svn:externals .
        svn update
        cd ..
    else
        printf "The component called '${SVN_COMPONENTS_LOCATION}/${SVN_COMPONENT}' does NOT exist!\n"
    fi
done 

exit 0;

