:_mod-docs-content-type: PROCEDURE

[id="creating-ds-instance"]
= Directory Server instance creation 

// This content is copied and modifed from https://github.com/dogtagpki/pki/wiki/Installing-DS-Server

*Note: Prior to installing DS instances, make sure the following procedures are done:*

* xref:installing-ds-packages.adoc[installing DS packages] - done on the DS host system

* xref:fqdn-configuration.adoc[Setting the FQDN of the host system] - done on the host systems of DS and PKI

Follow this process to prepare a local DS instance for PKI server.

*Note:* The DS installation automatically generates a bootstrap self-signed signing certificate which issues a bootstrap server certificate for SSL connection. The PKI installation takes advantage of this security offer to complete its installation. The bootstrap server certificate could be replaced by a server certificate issued by an actual CA at a later step after the installation.

_If you wish to disable bootstrap certificate generation and SSL connection, set `self_sign_cert = False` in the `sed` command below. You can still enable SSL later by following xref:enabling-ssl-connection-in-ds-with-bootstrap-cert.adoc[Enabling SSL Connection in DS with Bootstrap Cert]._

== Creating a DS Instance 

=== Generating a DS configuration file, for example `ds.inf`: 

[literal]
....
$ dscreate create-template ds.inf
....

Customize the DS configuration file as follows:

[literal]
....
$ sed -i \
    -e "s/^;instance_name = .*/instance_name = localhost/" \
    -e "s/^;root_password = .*/root_password = Secret.123/" \
    -e "s/^;suffix = .*/suffix = dc=example,dc=com/" \
    -e "s/^;create_suffix_entry = .*/create_suffix_entry = True/" \
    -e "s/^;self_sign_cert = .*/self_sign_cert = True/" \
    ds.inf
....

where

* *instance_name* specifies the name of the DS instance. In this example it's set to `localhost`.

* *root_password* specifies the password for DS admin, that is `cn=Directory Manager`. In this example it is set to `Secret.123`.

* *suffix* specifies the namespace for the DS instance. In this example it is set to `dc=example,dc=com`.

* *self_sign_cert* specifies whether to create self-signed certificates for SSL connection. In this example it is set to `True`. The SSL connection is enabled.

For more information see the parameter descriptions in the DS configuration file itself (i.e. `ds.inf`) and in link:https://directory.fedoraproject.org/docs/389ds/design/dsadm-dsconf.html[DS documentation].

=== Creating an instance 

Finally, create the instance:

[literal]
....
$ dscreate from-file ds.inf
....

== Creating PKI subtree 

Note: The `dc=pki,dc=example,dc=com` subtree is not mandatory, but it is highly recommended in order to avoid conflicts with other applications sharing the same DS instance.

Initially the DS instance is empty. Use an LDAP client to add a root entry and PKI base entry, for example:

[literal]
....
$ ldapadd -H ldap://$HOSTNAME -x -D "cn=Directory Manager" -w Secret.123 << EOF
dn: dc=pki,dc=example,dc=com
objectClass: domain
dc: pki
EOF
....
To confirm you can run:
....
$ ldapsearch -H ldap://$HOSTNAME -x
....

The subtree for each PKI subsystem is created when the subsystem is installed. When all PKI subsystems are created, the LDAP tree looks like the following:

[literal]
....
dc=example,dc=com
+ dc=pki
  + dc=ca
  + dc=kra
  + dc=ocsp
  + dc=tks
  + dc=tps
  + dc=acme
  + dc=est
....

== Enabling SSL connection 

If you set `self_sign_cert = False` earlier, and now decide to create bootstrap certs so that your PKI can be installed using SSL connection to DS,
follow xref:../others/enabling-ssl-connection-in-ds-with-bootstrap-cert.adoc[Enabling SSL Connection in DS]

*Note:* The bootstrap server certificate could be replaced by a server certificate issued by an actual CA at a later step after the installation.

== Configuring replication 

See link:https://github.com/dogtagpki/389-ds-base/wiki/Configuring-DS-Replication[Configuring DS Replication].

== Removing DS instance 

To remove DS instance:

[literal]
....
$ dsctl localhost remove --do-it
....

== Log Files 

DS log files are available in `/var/log/dirsrv/slapd-localhost`:

* access
* audit
* errors

== See Also

* link:https://www.port389.org/docs/389ds/howto/howto-ssl.html[Configuring TLS/SSL Enabled 389 Directory Server]
