:_mod-docs-content-type: PROCEDURE

[id="creating-ds-instance_{context}"]
// This content is copied and modifed from https://github.com/dogtagpki/pki/wiki/Installing-DS-Server
//
= Directory Server Instance Creation 

*Note: Prior to installing DS instances, make sure the following procedures are done:*

* link:installing-ds-packages.adoc[installing DS packages] - done on the DS host system
* link:fqdn-configuration.adoc[Setting the FQDN of the host system] - done on the host systems of DS and PKI

Follow this process to prepare a local DS instance for PKI server.

*Note:* The DS installation automatically generates a bootstrap self-signed signing certificate and a bootstrap server certificate for SSL connection. If desired, the bootstrap server certificate could be replaced by a server certificate issued by a CA at a later step.

_If you wish to have the certificate generation and the SSL connection disabled (*such as for the case of creating a DS instance for a pki clone*), set `self_sign_cert = False` in the `sed` command below. You can still enable SSL later by following link:enabling-ssl-connection-in-ds.adoc[Enabling SSL Connection in DS]._

== Creating a DS Instance 

=== Generate a DS configuration file, for example `ds.inf`: 

----
$ dscreate create-template ds.inf
----

Customize the DS configuration file as follows:

----
$ sed -i \
    -e "s/;instance_name = .*/instance_name = localhost/g" \
    -e "s/;root_password = .*/root_password = Secret.123/g" \
    -e "s/;suffix = .*/suffix = dc=example,dc=com/g" \
    -e "s/;create_suffix_entry = .*/create_suffix_entry = True/g" \
    -e "s/;self_sign_cert = .*/self_sign_cert = True/g" \
    ds.inf
----

where

* *instance_name* specifies the name of the DS instance. In this example it's set to `localhost`.
* *root_password* specifies the password for DS admin (i.e. `cn=Directory Manager`). In this example it's set to `Secret.123`.
* *suffix* specifies the namespace for the DS instance. In this example it's set to `dc=example,dc=com`. *It is important that the `suffix` and the host FQDN matches*.
* *self_sign_cert* specifies whether to create self-signed certificates for SSL connection. In this example it's set to `True`. The SSL connection is enabled.

For more information see the parameter descriptions in the DS configuration file itself (i.e. `ds.inf`) and in link:https://directory.fedoraproject.org/docs/389ds/design/dsadm-dsconf.html[DS documentation].

=== Creating an instance 

Finally, create the instance:

----
$ dscreate from-file ds.inf
----

== Creating PKI Subtree 

Initially the DS instance is empty. Use an LDAP client to add a root entry and PKI base entry, for example:

----
$ ldapadd -H ldap://$HOSTNAME -x -D "cn=Directory Manager" -w Secret.123 << EOF
dn: dc=pki,dc=example,dc=com
objectClass: domain
dc: pki
EOF
----

The subtree for each PKI subsystem is created when the subsystem is installed. See link:../others/pki-ldap-tree.adoc[PKI LDAP Tree].

== Enabling SSL Connection 

If you set `self_sign_cert = False` earlier, and are now ready to have your PKI configured to use SSL connection to DS,
follow link:../others/enabling-ssl-connection-in-ds.adoc[Enabling SSL Connection in DS]

== Configuring Replication 

See link:https://github.com/dogtagpki/389-ds-base/wiki/Configuring-DS-Replication[Configuring DS Replication].

== Removing DS Instance 

To remove DS instance:

----
$ dsctl localhost remove --do-it
----

== Log Files 

DS log files are available in `/var/log/dirsrv/slapd-localhost`:

* access
* audit
* errors

== See Also

* link:https://www.port389.org/docs/389ds/howto/howto-ssl.html[Configuring TLS/SSL Enabled 389 Directory Server]
