:_mod-docs-content-type: PROCEDURE

[id="creating-ds-instance"]
= Directory Server instance creation 

// This content is copied and modifed from https://github.com/dogtagpki/pki/wiki/Installing-DS-Server

*Note: Prior to installing DS instances, make sure the following procedures are done:*

* xref:installing-ds-packages.adoc[installing DS packages] - done on the DS host system

* xref:fqdn-configuration.adoc[Setting the FQDN of the host system] - done on the host systems of DS and PKI

Follow this process to prepare a local DS instance for PKI server.

*Note:* The DS installation automatically generates a bootstrap self-signed signing certificate which issues a bootstrap server certificate for SSL connection. The PKI installation takes advantage of this security offer to complete its installation. The bootstrap server certificate could be replaced by a server certificate issued by an actual CA at a later step after the installation.

_If you wish to disable bootstrap certificate generation and SSL connection, set `self_sign_cert = False` after the `dscreate create-template` command below. You can still enable SSL later by following xref:enabling-ssl-connection-in-ds-with-bootstrap-cert.adoc[Enabling SSL Connection in DS with Bootstrap Cert]._

== Creating a DS Instance 

=== Generating a DS configuration file, for example `ds.inf`: 

[literal,subs="+quotes,verbatim"]
....
$ dscreate create-template ds.inf
....

Make sure to customize the resulting content of ds.inf to have the appropriate values. Specifically check (or set if needed) the following values:

* *instance_name* specifies the name of the DS instance. In our example that follows, we are setting it to `localhost`.

* *root_password* specifies the password for DS admin, that is `cn=Directory Manager`. In our example that follows, we are setting it to `Secret.123`.

* *suffix* specifies the namespace for the DS instance. In our example that follows, we are setting it to `dc=example,dc=com`.

* *create_suffix_entry* specifies whether to create a generic root node entry for the suffix in the database.  In our example that follows, we are setting it to `True`.

* *self_sign_cert* specifies whether to create self-signed certificates for SSL connection. In our example that follows, we are setting it to `True`. The SSL connection is enabled.

For more information see the parameter descriptions in the DS configuration file itself (i.e. `ds.inf`) and in link:https://directory.fedoraproject.org/docs/389ds/design/dsadm-dsconf.html[DS documentation].

=== Creating an instance 

Finally, create the instance:

[literal,subs="+quotes,verbatim"]
....
$ dscreate from-file ds.inf
....

== Creating PKI subtree 

Initially the DS instance is empty. Use an LDAP client to add a root entry and PKI base entry, for example:

[literal,subs="+quotes,verbatim"]
....
$ ldapadd -H ldap://$HOSTNAME -x -D "cn=Directory Manager" -w Secret.123 << EOF
dn: dc=pki,dc=example,dc=com
objectClass: domain
dc: pki
EOF
....

The subtree for each PKI subsystem is created when the subsystem is installed. When all PKI subsystems are created, the LDAP tree looks like the following:

[literal,subs="+quotes,verbatim"]
....
dc=example,dc=com
+ dc=pki
  + dc=ca
  + dc=kra
  + dc=ocsp
  + dc=tks
  + dc=tps
  + dc=acme
  + dc=est
....

== Enabling SSL connection 

If you set `self_sign_cert = False` earlier, and now decide to create bootstrap certs so that your PKI can be installed using SSL connection to DS,
follow xref:../others/enabling-ssl-connection-in-ds-with-bootstrap-cert.adoc[Enabling SSL Connection in DS]

*Note:* The bootstrap server certificate could be replaced by a server certificate issued by an actual CA at a later step after the installation.

== Configuring replication 

See link:https://github.com/dogtagpki/389-ds-base/wiki/Configuring-DS-Replication[Configuring DS Replication].

== Removing DS instance 

To remove DS instance:

[literal,subs="+quotes,verbatim"]
....
$ dsctl localhost remove --do-it
....

== Log Files 

DS log files are available in `/var/log/dirsrv/slapd-localhost`:

* access
* audit
* errors

== See Also

* link:https://www.port389.org/docs/389ds/howto/howto-ssl.html[Configuring TLS/SSL Enabled 389 Directory Server]
