:_mod-docs-content-type: PROCEDURE

[id="enabling-ssl-connection-in-ds-with-bootstrap-cert"]
= Enabling SSL connection in DS using bootstrap certs

// This content was copied and adjusted from https://github.com/dogtagpki/pki/wiki/Enabling-SSL-Connection-in-DS

*If you already have an active trusted CA, and you wish to issue a server cert for your DS, follow xref:getting-ds-cert-issued-by-actual-ca.adoc[this section] instead.*

Follow this process using `pki` CLI (run `man pki-client`) commands to enable SSL connection in DS by creating a bootstrap DS self-signed signing certificate and the bootstrap server certificate issued by it.

This section assumes that a DS instance named `localhost` already exists, it does not have certificates, and the SSL connection is disabled.

*Note:* In newer DS versions the certificates are created and the SSL connection is enabled by default, so in general it is not necessary to follow this procedure.

== Creating DS signing certificate 

. Generate DS signing CSR with the following command:
+
[literal,subs="+quotes,verbatim"]
....
$ pki \
    -d /etc/dirsrv/slapd-localhost \
    -C /etc/dirsrv/slapd-localhost/pwdfile.txt \
    nss-cert-request \
    --subject "CN=DS Signing Certificate" \
    --ext /usr/share/pki/server/certs/ca_signing.conf \
    --csr ds_signing.csr
....

. Issue DS signing certificate:
+
[literal,subs="+quotes,verbatim"]
....
$ pki \
    -d /etc/dirsrv/slapd-localhost \
    -C /etc/dirsrv/slapd-localhost/pwdfile.txt \
    nss-cert-issue \
    --csr ds_signing.csr \
    --ext /usr/share/pki/server/certs/ca_signing.conf \
    --cert ds_signing.crt
....

. Import DS signing certificate:
+
[literal,subs="+quotes,verbatim"]
....
$ pki \
    -d /etc/dirsrv/slapd-localhost \
    -C /etc/dirsrv/slapd-localhost/pwdfile.txt \
    nss-cert-import \
    --cert ds_signing.crt \
    --trust CT,C,C \
    Self-Signed-CA
....

. Verify the DS signing certificate:
+
[literal,subs="+quotes,verbatim"]
....
$ certutil -L -d /etc/dirsrv/slapd-localhost -n Self-Signed-CA
...
    Certificate Trust Flags:
        SSL Flags:
            Valid CA
            Trusted CA
            User
            Trusted Client CA
        Email Flags:
            Valid CA
            Trusted CA
            User
        Object Signing Flags:
            Valid CA
            Trusted CA
            User
....

[id="creating-ds-server-certificate"]
== Creating DS Server Certificate 

. Generate DS server CSR with the following command:
+
[literal,subs="+quotes,verbatim"]
....
$ pki \
    -d /etc/dirsrv/slapd-localhost \
    -C /etc/dirsrv/slapd-localhost/pwdfile.txt \
    nss-cert-request \
    --subject "CN=$HOSTNAME" \
    --subjectAltName "critical, DNS:$HOSTNAME" \
    --ext /usr/share/pki/server/certs/sslserver.conf \
    --csr ds_server.csr
....

. Issue DS server certificate:
+
[literal,subs="+quotes,verbatim"]
....
$ pki \
    -d /etc/dirsrv/slapd-localhost \
    -C /etc/dirsrv/slapd-localhost/pwdfile.txt \
    nss-cert-issue \
    --issuer Self-Signed-CA \
    --csr ds_server.csr \
    --ext /usr/share/pki/server/certs/sslserver.conf \
    --cert ds_server.crt
....

. Import DS server certificate:
+
[literal,subs="+quotes,verbatim"]
....
$ pki \
    -d /etc/dirsrv/slapd-localhost \
    -C /etc/dirsrv/slapd-localhost/pwdfile.txt \
    nss-cert-import \
    --cert ds_server.crt \
    Server-Cert
....

. Verify the DS server certificate:
+
[literal,subs="+quotes,verbatim"]
....
$ certutil -L -d /etc/dirsrv/slapd-localhost -n Server-Cert
...
    Certificate Trust Flags:
        SSL Flags:
            User
        Email Flags:
            User
        Object Signing Flags:
            User
....

[id="enabling-ssl-connection"]
== Enabling SSL Connection 

. To enable SSL connection in the DS instance:
+
[literal,subs="+quotes,verbatim"]
....
$ dsconf localhost config replace nsslapd-security=on
....

. Restart the DS instance:
+
[literal,subs="+quotes,verbatim"]
....
$ dsctl localhost restart
....

. Verify the SSL connection:
+
[literal,subs="+quotes,verbatim"]
....
$ LDAPTLS_REQCERT=never ldapsearch \
    -H ldaps://$HOSTNAME:636 \
    -x \
    -D "cn=Directory Manager" \
    -w Secret.123 \
    -b "" \
    -s base
....

== See Also 

* link:https://www.port389.org/docs/389ds/howto/howto-ssl.html[Configuring TLS/SSL Enabled 389 Directory Server]
* link:https://access.redhat.com/documentation/en-us/red_hat_directory_server/11/html/administration_guide/enabling_tls#doc-wrapper[RHDS 11: Enabling TLS]
