:_mod-docs-content-type: PROCEDURE

[id="enabling-ssl-connection-in-ds_{context}"]

= Enabling SSL Connection in DS 

Follow this process using `pki` CLI (run `man pki-client`) commands to enable SSL connection in DS.

This section assumes that a DS instance named `localhost` already exists,

Two conditions are covered by this section:

* The DS instance does not already have any SSL server certificate, temporary or otherwise, and it is time to create an actual server cert for it.
* The DS instance has a temporary SSL server certificate, and it is time to replace it.

It is assumed that an actual trusted CA is available for issuing certificates.

== Import the CA signing certificate
Import the CA signing cert into the nssdb of the DS instance.

[literal,subs="+quotes,verbatim"]
....
# pki \
    -d /etc/dirsrv/slapd-localhost \
    -C /etc/dirsrv/slapd-localhost/pwdfile.txt \
    nss-cert-import \
    --cert ca_signing.crt \
    --trust CT,C,C \
    "CA Signing Cert"
....

== Creating DS Server Certificate 

=== Generate DS server CSR

As a DS administrator:

----
$ pki \
    -d /etc/dirsrv/slapd-localhost \
    -C /etc/dirsrv/slapd-localhost/pwdfile.txt \
    nss-cert-request \
    --subject "CN=server.example.com" \
    --subjectAltName "critical, DNS:server.example.com" \
    --csr ds_server.csr
----

=== Submit DS Server Certificate Request:

As a DS admin:

----
$ pki ca-cert-request-submit --profile caServerCert --csr-file ds_server.csr
----

=== Approve the Certificate Request:

As a PKI agent:

----
$ pki -n caadmin ca-cert-request-review <request ID> --action approve
----

== Retrieve and Import the Certificate

Retrieve the cert as the DS admin user:

----
$  pki ca-cert-export <certificate ID> --output-file ds_server.crt
----

Finally, import DS server certificate:

----
$ pki \
    -d /etc/dirsrv/slapd-localhost \
    -C /etc/dirsrv/slapd-localhost/pwdfile.txt \
    nss-cert-import \
    --cert ds_server.crt \
    Server-Cert
----

To verify the DS server certificate:

----
$ certutil -L -d /etc/dirsrv/slapd-localhost -n Server-Cert
...
    Certificate Trust Flags:
        SSL Flags:
            User
        Email Flags:
            User
        Object Signing Flags:
            User
----

== Enabling SSL Connection 

To enable SSL connection in the DS instance:

----
$ dsconf localhost config replace nsslapd-security=on
----

Finally, restart the DS instance:

----
$ dsctl localhost restart
----

To verify the SSL connection:

----
$ LDAPTLS_REQCERT=never ldapsearch \
    -H ldaps://$HOSTNAME:636 \
    -x \
    -D "cn=Directory Manager" \
    -w Secret.123 \
    -b "" \
    -s base
----

== See Also 

* link:https://www.port389.org/docs/389ds/howto/howto-ssl.html[Configuring TLS/SSL Enabled 389 Directory Server]
* link:https://access.redhat.com/documentation/en-us/red_hat_directory_server/11/html/administration_guide/enabling_tls#doc-wrapper[RHDS 11: Enabling TLS]
