= Tools Changes =

== Move PKI tools into jss-tools ==

The following tools have been moved into `jss-tools`:

* `p12tool`
* `p7tool`
* `sslget`

== Update pki-server status ==

The `pki-server status` command has been updated to no longer show
the subsystem `Type` field since it's redundant.

Instead, it will show an `SD Manager` field which will indicate whether
the subsystem is a security domain manager.

== Update certificate enrollment commands ==

The `pki ca-cert-request-submit` command has been updated to provide options
to specify the enrollment password and PIN.

== Update certificate revocation commands ==

The `pki ca-cert-revoke`, `pki ca-cert-hold`, and `pki ca-cert-release-hold` commands
have been updated to accept multiple serial numbers.

== Update certificate import command ==

The `pki-server ca-cert-import` command has been updated to provide an option
to specify the CSR of the certificate to be imported.

== Deprecate revoker tool ==

The `revoker` tool has been deprecated. Use the following commands instead:

* `pki ca-cert-revoke`
* `pki ca-cert-hold`
* `pki ca-cert-release-hold`

== Remove pki-server-upgrade ==

The `pki-server-upgrade` was deprecated in PKI 10.7.1 so now it has been removed.
Use `pki-server upgrade` instead.

== Update pki-server <subsystem>-user-add ==

The `pki-server <subsystem>-user-add` command has been updated to provide an option
to specify the user certificate.

== Update pki-server ca-cert-create ==

The `pki-server ca-cert-create` command has been updated to provide an option
to import the new certificate into CA database.

== Update pkispawn to support EST and ACME subsystem ==

The `pki-server <subsystem>-user-add` command has been updated to provide an option

== Update pkispawn

The `pkispawn` command has been updated to include ACME and EST subsystem deployment.

== Update pkidestroy

The `pkidestroy` command has been updated to include ACME and EST subsystem removal.

== Add pki-server password-set/unset ==

The `pki-server password-set/unset` commands have been added
to replace `pki-server password-add/del`.

The `pki-server password-add/del` commands have been deprecated.

== Deprecate pki-server subsystem-cert-find/show ==

The `pki-server subsystem-cert-find/show` commands have been deprecated.
Use `pki-server cert-find/show` commands instead.
