#!/bin/bash
#
# --- BEGIN COPYRIGHT BLOCK ---
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Copyright (C) 2007 Red Hat, Inc.
# All rights reserved.
# --- END COPYRIGHT BLOCK ### ---
#
# pki-cad    Startup script for pki-ca with tomcat6
#
# chkconfig:    - 81 19
# description:  Certificate Authority (Tomcat 6.0)
# processname:  pki-cad
# piddir:       /var/run/pki/ca
#

PROG_NAME=`basename $0`
SERVICE_NAME="pki-cad"
SERVICE_PROG="/sbin/service"
PKI_PATH="/usr/share/pki/ca"
PKI_REGISTRY="/etc/sysconfig/pki/ca"
PKI_TYPE="pki-ca"
PKI_TOTAL_PORTS=7

# Disallow 'others' the ability to 'write' to new files
umask 00002

command="$1"
pki_instance="$2"

# Source function library.
. /etc/init.d/functions

# Source the PKI function library
. /usr/share/pki/scripts/functions

# See how we were called.
case "${command}" in
    start|stop|restart|status)
        ${command}
        exit $?
        ;;
    condrestart|force-restart|try-restart)
        [ ! -f ${lockfile} ] || restart
        exit $?
        ;;
    reload)
        echo "The 'reload' action is an unimplemented feature."
        exit ${default_error}
        ;;
    *)
        # 3 unimplemented feature (for example, "reload")
        #     [invalid command - should never be reached]
        echo
        usage
        echo "where valid instance names include:"
        list_instances
        exit 3
        ;;
esac

