#!/bin/bash
# BEGIN COPYRIGHT BLOCK
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301  USA 
# 
# Copyright (C) 2007 Red Hat, Inc.
# All rights reserved.
# END COPYRIGHT BLOCK

# Always switch into the base directory of this
# shell script prior to executing it so that all
# of its output is written to this directory
cd `dirname $0`

# Retrieve the directory name housing this component
PWD=`pwd`

# Set Dogtag component-specific environment variables
DOGTAG_BUILD_SCRIPT=`basename $0`
export DOGTAG_BUILD_SCRIPT
DOGTAG_COMPONENT=`basename ${PWD}`
export DOGTAG_COMPONENT
DOGTAG_SPECFILE="dogtag-pki-tps-ui.spec"
export DOGTAG_SPECFILE

# Invoke the shared Dogtag PKI build script
config-ext/build_dogtag_pki $@

