:_mod-docs-content-type: PROCEDURE

[id="installing-ocsp-clone"]
= Installing OCSP Clone 


Follow this process to install a OCSP subsystem as a clone of an existing OCSP subsystem.

Prior to installation, please ensure that the xref:../others/installation-prerequisites.adoc[Installation Prerequisites] are configured.

== Exporting Existing OCSP System Certificates 

On the existing system, export the existing OCSP system certificates with the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki-server ocsp-clone-prepare \
    --pkcs12-file ocsp-certs.p12 \
    --pkcs12-password Secret.123
....

The command will export the following certificates (including the certificate chain) and their keys into a PKCS #12 file:

* OCSP signing certificate
* audit signing certificate
* subsystem certificate

Note that the existing SSL server certificate will not be exported.

If necessary, third-party certificates, for example trust anchors, can be added into the same PKCS #12 file with the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki -d /var/lib/pki/pki-tomcat/conf/alias -f /var/lib/pki/pki-tomcat/conf/password.conf \
    pkcs12-cert-import <nickname> \
    --pkcs12-file ocsp-certs.p12 \
    --pkcs12-password Secret.123 \
    --append
....

== OCSP Subsystem Installation 

Prepare a deployment configuration, for example `ocsp-clone.cfg`, to deploy OCSP subsystem clone.
By default the subsystem is deployed into a Tomcat instance called `pki-tomcat`.

A sample deployment configuration is available at xref:../../../base/server/examples/installation/ocsp-clone.cfg[/usr/share/pki/server/examples/installation/ocsp-clone.cfg].
It assumes that the primary CA and OCSP subsystems are running at https://primary.example.com:8443,
the CA signing certificate has been exported into `ca_signing.crt`,
and the admin certificate and key have been exported into `ca_admin_cert.p12`.
The PKCS #12 password is specified in the `pki_client_pkcs12_password` parameter.
See xref:../ca/installing-ca.adoc[Installing CA] for details.

To start the installation execute the following command:

[literal,subs="+quotes,verbatim"]
....
$ pkispawn -f ocsp-clone.cfg -s OCSP
....

== OCSP System Certificates 

After installation the existing OCSP system certificates (including the certificate chain)
and their keys are stored in the server NSS database (i.e. `/var/lib/pki/pki-tomcat/conf/alias`),
and a new SSL server certificate is created for the new instance:

[literal,subs="+quotes,verbatim"]
....
$ certutil -L -d /var/lib/pki/pki-tomcat/conf/alias

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

ca_signing                                                   CT,C,C
ocsp_signing                                                 u,u,u
sslserver                                                    u,u,u
subsystem                                                    u,u,u
ocsp_audit_signing                                           u,u,Pu
....

If necessary, the certificates can be exported into PEM files with the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki-server cert-export <cert ID> --cert-file <filename>
....

The valid certificate IDs for OCSP are:

* `ocsp_signing`
* `ocsp_audit_signing`
* `subsystem`
* `sslserver`

Note that the `pki-server cert-export` command takes a certificate ID instead of a nickname.
For simplicity the nicknames in this example are configured to be the same as the certificate ID.

== Admin Certificate 

To use the admin certificate, do the following.

Then import the CA signing certificate into the client NSS database:

[literal,subs="+quotes,verbatim"]
....
$ pki nss-cert-import --cert ca_signing.crt --trust CT,C,C ca_signing
....

Finally, import admin certificate and key into the client NSS database (by default ~/.dogtag/nssdb) with the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki pkcs12-import \
    --pkcs12 ca_admin_cert.p12 \
    --pkcs12-password Secret.123
....

To verify that the admin certificate can be used to access the OCSP subsystem clone, execute the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki -n caadmin ocsp-user-show ocspadmin
----------------
User "ocspadmin"
----------------
  User ID: ocspadmin
  Full name: ocspadmin
  Email: ocspadmin@example.com
  Type: adminType
  State: 1
....
