:_mod-docs-content-type: PROCEDURE

[id="installing-standalone-ocsp"]
= Installing standalone OCSP 

Follow this process to install a standalone OCSP subsystem.

In xref:installing-ocsp.adoc[regular OCSP installation] the OCSP certificates are issued automatically by the CA and the OCSP will join the CA's security domain.

In standalone OCSP installation, the OCSP certificates are issued manually and the OCSP has its own security domain.

The installation process consists multiple steps:

* Generating certificate requests
* Issuing the certificates
* Completing installation with the certificates

== Generating certificate requests 

. Prepare a file, for example `ocsp-standalone-step1.cfg`, that contains the first deployment configuration.
+
A sample deployment configuration is available at xref:../../../base/server/examples/installation/ocsp-standalone-step1.cfg[/usr/share/pki/server/examples/installation/ocsp-standalone-step1.cfg].

. Execute the following command:
+
[literal]
....
$ pkispawn -f ocsp-standalone-step1.cfg -s OCSP
....

It creates an NSS database in `/var/lib/pki/pki-tomcat/alias` and generates CSRs in the specified paths.

== Issuing certificates 

Use the CSRs to obtain OCSP certificates by submitting the CSRs to an external CA to issue the KRA system certificates. In the section that follows, it is assumed that the KRA system certificates are stored in the following files:

* ocsp_signing.crt
* subsystem.crt
* sslserver.crt
* ocsp_audit_signing.crt
* ocsp_admin.crt

// * link:https://github.com/dogtagpki/pki/wiki/Generating-OCSP-Signing-Certificate[Generating OCSP Signing Certificate]
// * link:https://github.com/dogtagpki/pki/wiki/Generating-Subsystem-Certificate[Generating Subsystem Certificate]
// * link:https://github.com/dogtagpki/pki/wiki/Generating-SSL-Server-Certificate[Generating SSL Server Certificate]
// * link:https://github.com/dogtagpki/pki/wiki/Generating-Audit-Signing-Certificate[Generating Audit Signing Certificate]
// * link:https://github.com/dogtagpki/pki/wiki/Generating-Admin-Certificate[Generating Admin Certificate]

== Completing installation 

. Prepare another file, for example `ocsp-standalone-step2.cfg`, that contains the second deployment configuration. The file can be created from the first file, that is `ocsp-standalone-step1.cfg`, with the following changes:
+
[literal]
....
pki_external_step_two=True
....

. Specify the certificate files with the following parameters:
+
[literal]
....
pki_ocsp_signing_cert_path=ocsp_signing.crt
pki_subsystem_cert_path=subsystem.crt
pki_sslserver_cert_path=sslserver.crt
pki_audit_signing_cert_path=ocsp_audit_signing.crt
pki_admin_cert_path=ocsp_admin.crt
....
+
Each certificate file can contain either a single PEM certificate or a PKCS #7 certificate chain.

. Specify the CA certificate chain with the following parameters:
+
[literal]
....
pki_cert_chain_nickname=ca_signing
pki_cert_chain_path=ca_signing.crt
....
+
The CA certificate chain file can contain either a single PEM certificate or a PKCS #7 certificate chain as well.
+
A sample deployment configuration is available at xref:../../../base/server/examples/installation/ocsp-standalone-step2.cfg[/usr/share/pki/server/examples/installation/ocsp-standalone-step2.cfg].

. Execute the following command:
+
[literal]
....
$ pkispawn -f ocsp-standalone-step2.cfg -s OCSP
....

== Verifying Admin Certificate 

. Import the CA signing certificate:
+
[literal]
....
$ pki nss-cert-import --cert ca_signing.crt --trust CT,C,C ca_signing
....

. Import admin certificate and key into the client NSS database (by default ~/.dogtag/nssdb) with the following command:
+
[literal]
....
$ pki pkcs12-import \
    --pkcs12 ocsp_admin_cert.p12 \
    --pkcs12-password Secret.123
....

. Verify that the admin certificate can be used to access the OCSP subsystem by executing the following command:
+
[literal]
....
$ pki -n ocspadmin ocsp-user-show ocspadmin
----------------
User "ocspadmin"
----------------
  User ID: ocspadmin
  Full name: ocspadmin
  Email: ocspadmin@example.com
  Type: adminType
  State: 1
....
