= Installing TPS


Follow this process to install a TPS subsystem.

Prior to installation, please ensure that the link:../others/installation-prerequisites.adoc[Installation Prerequisites] are configured.

== TPS Subsystem Installation

Prepare a file, for example `tps.cfg`, that contains the deployment configuration.
A sample deployment configuration is available at link:../../../base/server/examples/installation/tps.cfg[/usr/share/pki/server/examples/installation/tps.cfg].

Then execute the following command:

[literal,subs="+quotes,verbatim"]
....
$ pkispawn -f tps.cfg -s TPS
....

It will install TPS subsystem in a Tomcat instance (default is pki-tomcat) and create the following NSS databases:

* server NSS database: /var/lib/pki/pki-tomcat/conf/alias
* admin NSS database: ~/.dogtag/pki-tomcat/tps/alias

**Note**: When TPS is installed on a new system without any other subsystems,
it is necessary to provide the CA's root certificate. Specify the path to
the CA PKCS#7 PEM file in the `pki_cert_chain_path`. This will allow the server
to verify the CA's SSL server certificate when contacting the security domain.
It is up to the administrator to securely transport the CA root certificate
(public key only!) to the system prior to TPS installation.

== Verifying System Certificates

Verify that the server NSS database contains the following certificates:

[literal,subs="+quotes,verbatim"]
....
$ certutil -L -d /var/lib/pki/pki-tomcat/conf/alias

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

ca_signing                                                   CT,C,C
subsystem                                                    u,u,u
tps_audit_signing                                            u,u,Pu
sslserver                                                    u,u,u
....

== Verifying Admin Certificate

Prepare a client NSS database, for example `~/.dogtag/nssdb`:

[literal,subs="+quotes,verbatim"]
....
$ pki -c Secret.123 client-init
....

Import the CA signing certificate:

[literal,subs="+quotes,verbatim"]
....
$ pki -c Secret.123 client-cert-import ca_signing --ca-cert ca_signing.crt
....

Import admin key and certificate:

[literal,subs="+quotes,verbatim"]
....
$ pki -c Secret.123 pkcs12-import \
    --pkcs12 ca_admin_cert.p12 \
    --pkcs12-password Secret.123
....

Verify that the admin certificate can be used to access the TPS subsystem by executing the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki -c Secret.123 -n caadmin tps-user-show tpsadmin
---------------
User "tpsadmin"
---------------
  User ID: tpsadmin
  Full name: tpsadmin
  Email: tpsadmin@example.com
  Type: adminType
  State: 1
  TPS Profiles:
    All Profiles
....
