= Installing TPS Clone


Follow this process to install a TPS subsystem as a clone of an existing TPS subsystem
where the system certificates and their keys are stored in internal NSS token.

Prior to installation, please ensure that the link:../others/Installation_Prerequisites.adoc[Installation Prerequisites] are configured.

== Exporting Existing TPS System Certificates

On the existing system, export the TPS system certificates with the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki-server tps-clone-prepare \
    --pkcs12-file tps-certs.p12 \
    --pkcs12-password Secret.123
....

The command will export the following certificates (including the certificate chain) and their keys into a PKCS #12 file:

* audit signing certificate
* subsystem certificate

Note that the existing SSL server certificate will not be exported.

If necessary, third-party certificates, for example trust anchors, can be added into the same PKCS #12 file with the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki -d /var/lib/pki/pki-tomcat/conf/alias -f /var/lib/pki/pki-tomcat/conf/password.conf \
    pkcs12-cert-import <nickname> \
    --pkcs12-file tps-certs.p12 \
    --pkcs12-password Secret.123 \
    --append
....

== TPS Subsystem Installation

Prepare a deployment configuration, for example `tps-clone.cfg`, to deploy TPS subsystem clone.
By default the subsystem is deployed into a Tomcat instance called `pki-tomcat`.

A sample deployment configuration is available at link:../../../base/server/examples/installation/tps-clone.cfg[/usr/share/pki/server/examples/installation/tps-clone.cfg].
It assumes that the primary CA, KRA, TKS, and TPS subsystems are running at https://primary.example.com:8443,
the CA signing certificate has been exported into `ca_signing.crt`,
and the admin certificate and key have been exported into `ca_admin_cert.p12`.
The PKCS #12 password is specified in the `pki_client_pkcs12_password` parameter.
See link:../ca/Installing_CA.md[Installing CA] for details.

To start the installation execute the following command:

[literal,subs="+quotes,verbatim"]
....
$ pkispawn -f tps-clone.cfg -s TPS
....

== TPS System Certificates

After installation the existing TPS system certificates (including the certificate chain)
and their keys are stored in the server NSS database (i.e. `/var/lib/pki/pki-tomcat/conf/alias`),
and a new SSL server certificate is created for the new instance:

[literal,subs="+quotes,verbatim"]
....
$ certutil -L -d /var/lib/pki/pki-tomcat/conf/alias

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

ca_signing                                                   CT,C,C
sslserver                                                    u,u,u
subsystem                                                    u,u,u
tps_audit_signing                                            u,u,Pu
....

If necessary, the certificates can be exported into PEM files with the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki-server cert-export <cert ID> --cert-file <filename>
....

The valid certificate IDs for TPS are:

* `tps_audit_signing`
* `subsystem`
* `sslserver`

Note that the `pki-server cert-export` command takes a certificate ID instead of a nickname.
For simplicity the nicknames in this example are configured to be the same as the certificate IDs.

== Admin Certificate

To use the admin certificate from the CA subsystem, prepare a client NSS database (default is `~/.dogtag/nssdb`):

[literal,subs="+quotes,verbatim"]
....
$ pki client-init
....

Then import the CA signing certificate into the client NSS database:

[literal,subs="+quotes,verbatim"]
....
$ pki client-cert-import ca_signing --ca-cert ca_signing.crt
....

Finally, import admin certificate and key with the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki pkcs12-import \
    --pkcs12 ca_admin_cert.p12 \
    --pkcs12-password Secret.123
....

To verify that the admin certificate can be used to access the TPS subsystem clone, execute the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki -n caadmin tps-user-show tpsadmin
---------------
User "tpsadmin"
---------------
  User ID: tpsadmin
  Full name: tpsadmin
  Email: tpsadmin@example.com
  Type: adminType
  State: 1
....
