#!/bin/bash
# BEGIN COPYRIGHT BLOCK
# (C) 2008 Red Hat, Inc.
# All rights reserved.
# END COPYRIGHT BLOCK

###############################################################################
#  Since the 'svn.fedorahosted.org' repository uses a different URL prefix to #
#  distinguish between read-only (http) and read-write (svn+ssh) check-outs,  #
#  ALL external SVN properties that refer to this repository MUST now be      #
#  read-only, which means that ALL changes which refer to this repository     #
#  that need to be saved MUST be applied to the top-level directory referred  #
#  to by each external SVN property (i.e. - 'pki/base/config' AND             #
#  'pki/ipa/config-ext').                                                     #
###############################################################################

# Always switch into this base directory
# prior to script execution so that all
# of its output is written to this directory
cd `dirname $0`

# Retrieve the name of this base directory
PKI_PWD=`pwd`

# Name and location of the SVN external properties URL.
SVN_BASE_URL="http://svn.fedorahosted.org/svn/pki/trunk/pki/base"
SVN_DOGTAG_URL="http://svn.fedorahosted.org/svn/pki/trunk/pki/dogtag"
SVN_IPA_URL="http://svn.fedorahosted.org/svn/pki/trunk/pki/ipa"

# Change directory to the location of the "top-level" components,
# and execute the defined SVN external property changes.
cd ${PKI_PWD}/..
printf "Setting external SVN properties for 'ca' external components . . .\n"
svn propset svn:externals "ca ${SVN_DOGTAG_URL}/ca" .
svn propget svn:externals .
svn update

cd ${PKI_PWD}/..
printf "Setting external SVN properties for 'common' external components . . .\n"
svn propset svn:externals "common ${SVN_DOGTAG_URL}/common" .
svn propget svn:externals .
svn update

cd ${PKI_PWD}/..
printf "Setting external SVN properties for 'java-tools' external components . . .\n"
svn propset svn:externals "java-tools ${SVN_DOGTAG_URL}/java-tools" .
svn propget svn:externals .
svn update

cd ${PKI_PWD}/..
printf "Setting external SVN properties for 'native-tools' external components . . .\n"
svn propset svn:externals "native-tools ${SVN_DOGTAG_URL}/native-tools" .
svn propget svn:externals .
svn update

cd ${PKI_PWD}/..
printf "Setting external SVN properties for 'osutil' external components . . .\n"
svn propset svn:externals "osutil ${SVN_DOGTAG_URL}/osutil" .
svn propget svn:externals .
svn update

cd ${PKI_PWD}/..
printf "Setting external SVN properties for 'selinux' external components . . .\n"
svn propset svn:externals "selinux ${SVN_DOGTAG_URL}/selinux" .
svn propget svn:externals .
svn update

cd ${PKI_PWD}/..
printf "Setting external SVN properties for 'setup' external components . . .\n"
svn propset svn:externals "setup ${SVN_DOGTAG_URL}/setup" .
svn propget svn:externals .
svn update

cd ${PKI_PWD}/..
printf "Setting external SVN properties for 'silent' external components . . .\n"
svn propset svn:externals "silent ${SVN_DOGTAG_URL}/silent" .
svn propget svn:externals .
svn update

cd ${PKI_PWD}/..
printf "Setting external SVN properties for 'symkey' external components . . .\n"
svn propset svn:externals "symkey ${SVN_DOGTAG_URL}/symkey" .
svn propget svn:externals .
svn update

cd ${PKI_PWD}/..
printf "Setting external SVN properties for 'util' external components . . .\n"
svn propset svn:externals "util ${SVN_DOGTAG_URL}/util" .
svn propget svn:externals .
svn update

# Change directory to the location of the "ca-ui" component,
# and execute the defined SVN external property changes.
cd ca-ui
printf "Setting external SVN properties for 'ca-ui' external components . . .\n"
svn propset svn:externals "config ${SVN_BASE_URL}/config" .
svn propset svn:externals "config-ext ${SVN_IPA_URL}/config-ext" .
svn propset svn:externals "shared ${SVN_DOGTAG_URL}/ca-ui/shared" .
svn propget svn:externals .
svn update
cd ..

# Change directory to the location of the "common-ui" component,
# and execute the defined SVN external property changes.
cd common-ui
printf "Setting external SVN properties for 'common-ui' external components . . .\n"
svn propset svn:externals "config ${SVN_BASE_URL}/config" .
svn propset svn:externals "config-ext ${SVN_IPA_URL}/config-ext" .
svn propset svn:externals "shared ${SVN_DOGTAG_URL}/common-ui/shared" .
svn propget svn:externals .
svn update
cd ..

exit 0;

