= Server Changes =

== Change nsPagedSizeLimit default value ==

The default value for `nsPagedSizeLimit` has been changed to `-1` to avoid
issues while cloning a CA or KRA that uses sequential serial numbers and
the CA or KRA is configured to access the database using an LDAP user.

Existing CA or KRA instances will need to be updated manually.

See also:

* link:https://github.com/dogtagpki/pki/issues/5133[PKI Issue #5133]
* link:../../upgrade/v11.9/Upgrading-PKI-Database.adoc[Upgrading PKI 11.9 Database]

== Introduce ML-DSA algorithm family ==

The new algorithms `ML-DSA-44`, `ML-DSA-65` and `ML-DSA-87` are
enabled for certificate key and signature. It is possible to deploy a
CA using the `ML-DSA-44` algorithm using the example `pkispawn`
configuration file provided in the
link:../../..//base/server/examples/installation/ca-mldsa.cfg[installation examples].

== VLV Index for CRL Generation ==

VLV indexes are not enabled by default. However, if VLV is enabled during
CA installation (`pki_ds_setup_vlv=True`), a new VLV index
`allRevokedCertsByIssuer` will be created to optimize CRL generation
performance by reducing unindexed LDAP searches for revoked certificates.
This index filters revoked certificates by issuer DN.

For new CA instances with VLV enabled, the index will be created
automatically during installation.

Existing CA instances with VLV enabled will need to add and reindex the
VLV manually after upgrading to 11.9:

----
pki-server ca-db-vlv-add
pki-server ca-db-vlv-reindex
----

*Note:* The reindex operation may take significant time on databases with
many certificates. For replicated environments, VLV indexes are not
replicated, so each replica must run these commands independently.
