= Tools Changes =

== Update subsystem ACL ==

The following commands have been added to find, add and delete ACL:

- `pki-server <subsystem>-acl-find`;
- `pki-server <subsystem>-acl-add`;
- `pki-server <subsystem>-acl-del`.

== Add command to create group ==

The `pki-server <subsystem>-group-add` command has been added to create group.

== Add command for new SD type ==

The `pki-server sd-type-add` command has been added to allow the introduction
of new security domain types.

== New `--key-id-file` option ==

The following commands have been modified to provide an option to specify
a file to store the ID of a new key or to load the ID of an existing key:

* `pki nss-key-create`
* `pki nss-key-show`
* `pki nss-cert-request`

== New shell/batch mode for PKI CLI ==

PKI CLI now provides a shell mode to run commands interactively and
a batch mode to run multiple commands at once.

== New pki nss-cert-mod command ==

The `pki nss-cert-mod` has been added to modify the trust flags
of an existing certificate in NSS database.

The `pki client-cert-mod` has been deprecated.

== Deprecated command ==

The following command have been deprecated:

* `pki client-cert-request`

== Add new algorithm value for ML-DSA ==

The algorithm ML-DSA can be specified for the command:

* `pki client-cert-request`: value **mldsa** for the option `--algorithm` and the option `--length` can be one of 44, 65 (default) or 87;
* `pki nss-cert-request`: value **MLDSA** for the option `--key-type` and the option `--key-size` can be one of 44, 65 (default) or 87.
 
== Add `pki --http-output` option ==

The `pki --http-output` option has been added to replace the `--output` option.
