:_mod-docs-content-type: PROCEDURE

[id="installing-kra-on-separate-instance_{context}"]
= Installing KRA on Separate Instance 


Follow this process to install a KRA subsystem on an instance/host separate from the CA.

Prior to installation, please ensure that the xref:../others/installation-prerequisites.adoc[Installation Prerequisites] are configured.

== KRA Subsystem Installation 

Prepare a file, for example `kra-separate.cfg`, that contains the deployment configuration.

A sample deployment configuration is available at xref:../../../base/server/examples/installation/kra-separate.cfg[/usr/share/pki/server/examples/installation/kra-separate.cfg].
It assumes that the CA is running at https://ca.example.com:8443,
the CA signing certificate has been exported into `ca_signing.crt`,
and the admin certificate has been exported into `ca_admin.cert`.

Then execute the following command:

[literal,subs="+quotes,verbatim"]
....
$ pkispawn -f kra-separate.cfg -s KRA
....

It will install KRA subsystem in a Tomcat instance (default is pki-tomcat) and create the following NSS databases:

* server NSS database: /var/lib/pki/pki-tomcat/conf/alias
* admin NSS database: ~/.dogtag/pki-tomcat/kra/alias

**Note**: When KRA is installed on a new system without any other subsystems,
it is necessary to provide the CA's root certificate. Specify the path to
the CA PKCS#7 PEM file in the `pki_cert_chain_path`. This will allow the server
to verify the CA's SSL server certificate when contacting the security domain.
It is up to the administrator to securely transport the CA root certificate
(public key only!) to the system prior to KRA installation.

== Verifying System Certificates 

Verify that the server NSS database contains the following certificates:

[literal,subs="+quotes,verbatim"]
....
$ certutil -L -d /var/lib/pki/pki-tomcat/conf/alias

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

ca_signing                                                   CT,C,C
kra_transport                                                u,u,u
kra_storage                                                  u,u,u
subsystem                                                    u,u,u
kra_audit_signing                                            u,u,Pu
sslserver                                                    u,u,u
....

== Verifying Admin Certificate 

Prepare a client NSS database, for example `~/.dogtag/nssdb`:

[literal,subs="+quotes,verbatim"]
....
$ pki -c Secret.123 client-init
....

Import the CA signing certificate:

[literal,subs="+quotes,verbatim"]
....
$ pki -c Secret.123 client-cert-import ca_signing --ca-cert ca_signing.crt
....

Import CA admin key and certificate:

[literal,subs="+quotes,verbatim"]
....
$ pki -c Secret.123 pkcs12-import \
    --pkcs12 ca_admin_cert.p12 \
    --pkcs12-password Secret.123
....

Verify that the CA admin certificate can be used to access the KRA subsystem by executing the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki -c Secret.123 -n caadmin kra-user-show kraadmin
---------------
User "kraadmin"
---------------
  User ID: kraadmin
  Full name: kraadmin
  Email: kraadmin@example.com
  Type: adminType
  State: 1
....

== Verifying KRA Connector 

Verify that the KRA connector is configured in the CA subsystem:

[literal,subs="+quotes,verbatim"]
....
$ pki -c Secret.123 -n caadmin ca-kraconnector-show

Host: kra.example.com:8443
Enabled: true
Local: false
Timeout: 30
URI: /kra/agent/kra/connector
Transport Cert:

<base-64 certificate>
....
