= Managing PostgreSQL Realm =

To add a user and associate to the _EST Users_ group it is possible to execeute the following commands:

----
$ psql -U est -t -A -c "INSERT INTO users VALUES ('est-test-user', 'EST TEST USER', '<tomcat_digest>');"  est 
$ psql -U est -t -A -c "INSERT INTO group_members VALUES ('EST Users', 'est-test-user');"  est 
----

Note: the tomcat digest for the password can be obtained with the command:
----
$ tomcat-digest <user_password>
----

== TLS mutual authentication ==

The above configurations allow client authentication using
_username/password_. In some cases or for specific operation, such as
re-enroll for a new certificate, mutual authentication with client
certificate is required.

Realm configuration already support certificate based authentication
out-of-the-box but in order to authenticate a user some additional
information are needed. In more detail, the user entry has to include
a _description_ containing some certificate details and the binary
certificate.

The _description_ has the format
`<Version>;<Serial>;<Issuer>;<subject>`. The version is the hex value
(without _0x_), the serial is in decimal and issuer and subject are
distinguished name (DN). The format for DN is from the more specific
attribute to the more general (note: some tools, like *OpenSSL*, have
different order), separated by comma.

These information are stored in the _user_certs_ table. As an example, if the user
has a certificate with the following values:

----
$ openssl x509 -in cert.pem -subject -serial -issuer -text -noout |head -11
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            33:1c:9e:b7:9a:2d:cc:17:69:24:a2:81:4e:06:07:40
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: O=EXAMPLE, OU=pki-tomcat, CN=CA Signing Certificate
        Validity
            Not Before: Jan 16 11:31:11 2025 GMT
            Not After : Apr 16 11:31:11 2025 GMT
        Subject: CN=test.example.com
----

Then the user entry `est-test-user` defined above requires a new entry in 
the _user_certs_ table which can be added with:
----
$ psql -U est -t -A -c "INSERT INTO user_certs VALUES ('est-test-user', '2;67939231264256858734977554404570695488;CN=CA Signing Certificate,OU=pki-tomcat,O=EXAMPLE;CN=test.example.com', pg_read_binary_file('/cert.der'));" est
----
