.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH CMCRequest 1 "March 14, 2018" "version 10.5" "PKI CMC Request Generation Tool" Dogtag Team
.\" Please adjust this date whenever revising the man page.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for man page specific macros, see man(7)
.SH NAME
CMCRequest \- Used to generate a CMC certificate issuance or revocation request.

.SH SYNOPSIS
.PP
\fBCMCRequest <CMCRequest configuration filename>\fP

.SH DESCRIPTION
.PP
The Certificate Management over Cryptographic Message Syntax (CMC) Request Generation utility, \fBCMCRequest\fP, provides a command-line utility used to generate a CMC certificate issuance or revocation request.  For issuance request, it requires either a PKCS#10 or CRMF request as input. The resulting CMC request can be sent to the CA via tool such as \fBHttpClient\fP.
.PP
\fBCMCRequest\fP takes a configuration file where various configuration parametrs are supported. 

.SH CONFIGURATION PARAMETERS
.PP
The following are supported configuration parameters for the configuration file.  Each parameter is in the format of <name>=<value> (e.g. format=pkcs10).
.PP
.TP
.B numRequests
Total number of PKCS10 or CRMF requests. (note: lately the CA has only been tested to work with one)

.TP
.B input
full path for PKCS #10 or CRMF certificate request in PEM.

For example if \fBPKCS10Client\fP or \fBCRMFPopClient\fP are used to generate the PKCS#10 or CRMF requests respectively, this value should be the value of the \fB"-o"\fP option of those command line tools.

.TP
.B format
request format.  Either \fBpkcs10\fP or \fBcrmf\fP.

.TP
.B output
full path for the resulting CMC request in ASN.1 DER encoded format.

Note that this would be the \fBinput\fP in the \fBHttpClient\fP configuration file if it is used to submit the CMC request.

.TP
.B dbdir
directory for NSS database: cert8.db, key3.db and secmod.db

.TP
.B tokenname
name of crypto token where user signing certificate key can be found (default is internal)

.TP
.B nickname
The nickname of the user certificate that corresponds to the private key that is used to sign the request.

This parameter is ignored if \fBselfSign\fP or \fBidentityProofV2.enable\fP is true.

.TP
.B password
password to the crypto token where the signing user's certificate and keys are stored.

.TP
.B identification[.enable]
RFC 5272 allows the CA to require inclusion of the \fBidentification\fP control to accompany the \fBidentityProofV2\fP control in a CMC request.

In Dogtag, CA employs the \fBidentification\fP control to assist in locating the shared secret required for verification of the shared secret computed in the \fBidentityProofV2\fP.

In addition, the \fBidentification\fP control is also required for \fBpopLinkWitnessV2\fP for locating the shared secret.

When \fBidentification.eanble\fP is true, \fBidentification\fP should contain a user id known by the CA.

.TP
.B witness.sharedSecret
The \fBwitness.sharedSecret\fP should contain a passphrase that is known by the CA. One usually obtains it from the CA administrator.

This parameter is required by the following options: \fBidentityProofV2\fP, and \fBpopLinkWitnessV2\fP.

See man pages for \fBCMCSharedToken\fP for information on usage.

.TP
.B identityProofV2.[enable, hashAlg, macAlg]
Identity Proof V2 allows one to provide proof of identity without a signing certificate.  It does so by embedding a "witness" value that's calculated from a shared secret (see \fBwitness.sharedSecret\fP) known by the CA.

The \fBidentityProofV2\fP parameter set allows a user to specify the hashing algorithm as well as MAC (Message Authentication Code) algorithm used to compute the value of the witness value.

Supported \fBidentityProofV2.hashAlg\fP are: \fBSHA-256, SHA-384, and SHA-512\fP

Supported \fBidentityProofV2.macAlg\fP are: \fBSHA-256-HMAC, SHA-384-HMAC, and SHA-512-HMAC\fP

When \fBidentityProofV2.eanble\fP is true, these parameters must be accompanied by the \fBidentification\fP as well as the \fBwitness.sharedSecret\fP parameters.

These parameters could be accompanied by the \fBpopLinkWitnessV2\fP parameter set if required by the CA.

.TP
.B popLinkWitnessV2.[enable, keyGenAlg, macAlg]
The POPLinkWitnessV2 control is a mechanim that links the POP (Proof of Possession) to the identity, which adds more credibility to the otherwise distinct POP and Proof of Identity mechanisms. It does so by employing calculation of a random value with a shared secret (see \fBwitness.sharedSecret\fP) known by the CA.

The POP Link Witness V2 value must be baked into the PKCS#10 or CRMF requests.  It is therefore crutial that the caller that employs this option has access to the private key of the certificate request.

If \fBpopLinkWitnessV2\fP is used, then \fBidentification\fP and \fBwitness.sharedSecret\fP must be supplied, and the \fBidentityProofV2\fP parameter set is in general used.

Supported keyGenAlg are: \fBSHA-256, SHA-384, and SHA-512\fP

Supported macAlg are: \fBSHA-256-HMAC, SHA-384-HMAC, and SHA-512-HMAC\fP

.TP
.B request.selfSign
\fBtrue\fP or \fBfalse\fP.  If \fBselfSign\fP is true, the CMC request will be "signed" with the pairing private key of the enrollment request; and in which case the \fBnickname\fP parameter will be ignored.

\fBrequest.selfSign\fP is only used if a signing certificate (of the agent or user herself) is not available to sign. Because the request itself is not signed with a certificate (a proven identity), the proof of origin (proof of identification) must be provided by some other means.

In Dogtag, if \fBselfSign\fP is true, it must be used in conjunction with the \fBidentityProofV2\fP and \fBidentification\fP parameters.  And in that case the Proof Of Origin is accomplished by the Shared Secret (\fBwitness.sharedSecret\fP) mechanism.

The \fBselfSign\fP option is normally used to enroll for a user's first signing certificate while auto-approval (without agent's pre-approval) is preferred. In general, once a user has obtained the first signing certificate, such signing certificate can be used to sign (thus proving origin) and obtain other certificate such as encryption-only ceritifcate, or when doing a renewal or revocation.

By default, if unspecified, \fBselfSign\fP is false.

\fBNote\fP: to employ the \fBselfSign\fP option, the PKCS#10 or CRMF requests must have the \fBSubjectKeyIdentifier extension\fP. (hint: \fBCRMFPopClient\fP and \fBPKCS10Client\fP should be called with the "-y" option)

If \fBselfSign\fP is true, \fBrequest.privKeyId\fP must be specified.
It is crutial that the caller that employs this option has access to the private key of the certificate request.

.TP
.B request.privKeyId
The \fBrequest.privKeyId\fP parameter is required in the following cases:

\fBselfSign\fP, \fBpopLinkWitnessV2\fP, and \fBdecryptedPop\fP

.TP
.B decryptedPop.enable, encryptedPopResponseFile, decryptedPopRequestFile
In case when the enrolling key is an encryption-only key, the traditional POP (Proof of Possession) that employs signing of the request is not possible, CMC provides the EncryptedPOP/DecryptedPOP  mechanism to allow the CA to challenge the client. This mechanism requires two trips.  Frist trip (a CMC request without POP) would trigger the CA to generate a challenge and encrypt the challenge with the request public key in the certificate response (one should find the EncryptedPOP control as well as status with "failedInfo=POP required" in the CMCResponse); while second trip from the client would contain proof that the client has decrypted the challenge and thereby proving ownership of the private key to the enrollment request.
When preparing for the second trip, the following parameters must be present:

\fBdecryptedPop.enable\fP - set to true; default is false;

\fBencryptedPopResponseFile\fP - the input file that contains the CMCResponse from first trip; It should contains the CMC EncryptedPop control.

\fBdecryptedPopRequestFile\fP - the output file for the CMC request which should contain the CMC DecryptedPOP control.

\fBrequest.privKeyId\fP - see descripton for \fBrequest.privKeyId\fP; It is used to decrypt the EncryptedPop, thereby proving the possession of the private key.

Please note that the \fBPopLinkWitnessV2\fP control as well as the \fBselfSign\fP directive do not apply to EncryptedPOP/DecryptedPOP for the simple fact that the enrollment private key is not capable of signing.

.TP
.B revRequest.[enable, serial, reason, comment, issuer, sharedSecret]
Revocation can be done either by signing with user's own valid signing certificate, or by authenticating with user's shared secret (see \fBwitness.sharedSecret\fP) known by the CA.

For revocation request signed with user's own valid signing certificate, the \fBnicname\fP parameter should be a valid user signing certificate that belongs to the same user subject as that of the certificate to be revoked (but not necessarily the same certificate); Also, \fBrevRequest.issuer\fP and \fBrevRequest.sharedSecret\fP are ignored, while \fBrevRequest.serial\fP and \fBrevRequest.reason\fP must contain valid values.

For revocation by authenticating with user's shared secret, the following parameters are required: \fBrevRequest.serial\fP, \fBrevRequest.reason\fP, \fBrevRequest.issuer\fP, \fBrevRequest.sharedSecret\fP, while \fBnickname\fP will be ignored.

\fBrevRequest.reason\fP can have one of the following values: \fBunspecified\fP, \fBkeyCompromise\fP, \fBcaCompromise\fP, \fBaffiliationChanged\fP, \fBsuperseded\fP, \fBcessationOfOperation\fP, \fBcertificateHold\fP, \fBremoveFromCRL\fP.

\fBrevRequest.serial\fP is in Decimal.

\fBrevRequest.issuer\fP is issuer subject DN.

\fBrevRequest.invalidityDatePresent\fP is optional.  \fBtrue\fP or \fBfalse\fP. When true, the invalidityDate of the RevokeRequest will be set to the current time when this tool is being run.

\fBrevRequest.comment\fP is optional.

.SH EXAMPLES
.PP
CMC requests must be submitted to the CA to be processed. Tool supported by Dogtag for submitting these requests is \fBHttpClient\fP.
.PP
\fBNote:\fP For examples on how to use this tool, please see
http://www.dogtagpki.org/wiki/PKI_10.4_CMC_Feature_Update_(RFC5272)#Practical_Usage_Scenarios for Practical Usage Scenarios, and their examples.

.SH AUTHORS
Christina Fu <cfu@redhat.com>.

.SH COPYRIGHT
Copyright (c) 2018 Red Hat, Inc. This is licensed under the GNU General Public
License, version 2 (GPLv2). A copy of this license is available at
http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.

.SH SEE ALSO
.BR CMCResponse(1), CMCSharedToken(1), CMCRevoke(1), pki(1)
