#!/bin/sh
#
# Authors:
#     PKI Team <pki-devel@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Copyright (C) 2024 Red Hat, Inc.
# All rights reserved.
#

#
# PKI Tomcat Startup Wrapper
#
# This script provides an abstraction layer for starting Tomcat,
# detecting the installed Tomcat version and calling the appropriate
# startup command.
#

set -e

# Detect Tomcat flavor based on installed files
if [ -f /usr/libexec/tomcat/tomcat-run.sh ]; then
    # New Tomcat 10.1+ uses tomcat-run.sh
    exec /usr/libexec/tomcat/tomcat-run.sh
else
    # Old Tomcat 10 uses 'server start'
    exec /usr/libexec/tomcat/server start
fi

