#!/bin/bash
set -e

BUILDLOG=/tmp/compose.log

function compose {
    pushd ${BUILDDIR}/pki
    # run make with --quiet to reduce log verbosity.
    sudo -u ${BUILDUSER} MAKEFLAGS="-j2 --quiet" -- \
        ./scripts/$1 rpms
    popd
}

function upload {
    if test -f $BUILDLOG; then
        echo "Uploading build log to transfer"
        curl --upload-file $BUILDLOG https://transfer.sh/pkitravis_$1.txt
    fi
}

if test "${TRAVIS}" != "true"; then
    compose
else
    trap "upload $1" EXIT
    echo "Runing $1 rpms."
    echo "Build log will be posted to transfer.sh"
    echo $(date) > $BUILDLOG
    echo "Travis job ${TRAVIS_JOB_NUMBER}" >> $BUILDLOG
    compose $1>>$BUILDLOG 2>&1
fi