#!/bin/bash
set -e
PACKAGES=`find ${BUILDDIR}/packages/RPMS/ -name '*.rpm' -and -not -name '*debuginfo*'`

echo ${PACKAGES}

find ${BUILDDIR}/packages/RPMS/ -name '*.rpm' -and -not -name '*debuginfo*' \
    | xargs dnf install -y --best --allowerasing
  
# Remove the RPMs once installed. They are not required anymore. This will ensure
# that there is no issue generating next set of RPMs
find ${BUILDDIR}/packages/RPMS/ -name '*.rpm' -and -not -name '*debuginfo*' \
    | xargs rm