#!/usr/bin/python3
import os
import shutil

from distutils.sysconfig import get_python_lib


BUILDDIR = os.environ['BUILDDIR']
PKIBASE = os.path.join(BUILDDIR, 'pki', 'base')
PKICLIENT = os.path.join(PKIBASE, 'common', 'python', 'pki')
PKISERVER = os.path.join(PKIBASE, 'server', 'python', 'pki', 'server')
PKISBIN = os.path.join(PKIBASE, 'server', 'sbin')

SITEPACKAGES = get_python_lib()


def copyfiles():
    shutil.rmtree(os.path.join(SITEPACKAGES, 'pki'))
    shutil.copytree(
        PKICLIENT,
        os.path.join(SITEPACKAGES, 'pki')
    )
    shutil.copytree(
        PKISERVER,
        os.path.join(SITEPACKAGES, 'pki', 'server')
    )


if __name__ == '__main__':
    copyfiles()
