:_mod-docs-content-type: PROCEDURE

[id="installing-ca-with-existing-keys-in-internal-token"]
= Installing CA with existing keys in internal token 

Follow this process to install a CA subsystem with the system keys, CSRs, and certificates from an existing CA where the keys are stored on an internal token.

This method of installation could be useful for situations such as restoring an independent instance from a backup where the original server might not be available anymore.

To avoid conflicts with the existing CA subsystem, the new CA subsystem uses new SSL server and subsystem certificates, so they are not included in the installation process.

Prior to installation, ensure that the xref:../others/installation-prerequisites.adoc[Installation Prerequisites] are configured.

== Starting a CA subsystem installation 

Prepare a file, for example `ca-existing-certs-step1.cfg`, that contains the first deployment configuration.

A sample deployment configuration is available at xref:../../../base/server/examples/installation/ca-existing-certs-step1.cfg[/usr/share/pki/server/examples/installation/ca-existing-certs-step1.cfg].

Execute the following command:
[literal]
....
$ pkispawn -f ca-existing-certs-step1.cfg -s CA
....

It installs a CA subsystem in a Tomcat instance (default is pki-tomcat) and creates the following NSS databases:

* server NSS database: /var/lib/pki/pki-tomcat/conf/alias

* admin NSS database: ~/.dogtag/pki-tomcat/ca/alias

Since there are no CSR path parameters specified, it does not generate CA system and admin keys.

== Exporting existing system keys, CSRs, certificates 

. Export the system keys and certificates from the existing CA into a PKCS #12 file with the following command:
+
[literal]
....
$ pki -d /var/lib/pki/pki-tomcat/conf/alias -c Secret.123 pkcs12-export \
  --pkcs12 ca-certs.p12 \
  --password Secret.123
$ pki pkcs12-cert-del --pkcs12-file ca-certs.p12 --pkcs12-password Secret.123 sslserver
$ pki pkcs12-cert-del --pkcs12-file ca-certs.p12 --pkcs12-password Secret.123 subsystem
....

. Copy the CSRs from the existing CA to the pkispawn directory on the host where the new CA will be created, for example:
+
[literal]
....
cp /etc/pki/pki-tomcat/certs/* /root 
....

== Finishing a CA subsystem installation 

. Prepare another file, for example `ca-existing-certs-step2.cfg`, that contains the second deployment configuration.
+
The file can be created from the first file, that is `ca-existing-certs-step1.cfg`, with the following changes:
+
[literal]
....
pki_external_step_two=True
....

. Specify the existing keys and certificates in the PKCS #12 file with the following parameters:
+
[literal]
....
pki_pkcs12_path=ca-certs.p12
pki_pkcs12_password=Secret.123
....

. Specify the existing CSRs with the following parameters:
+
[literal]
....
pki_ca_signing_csr_path=ca_signing.csr
pki_ocsp_signing_csr_path=ca_ocsp_signing.csr
pki_audit_signing_csr_path=ca_audit_signing.csr
....
+
A sample deployment configuration is available at xref:../../../base/server/examples/installation/ca-existing-certs-step2.cfg[/usr/share/pki/server/examples/installation/ca-existing-certs-step2.cfg].

. Execute the following command:
+
[literal]
....
$ pkispawn -f ca-existing-certs-step2.cfg -s CA
....

== Verifying system certificates 

Verify that the server NSS database contains the following certificates:
[literal]
....
$ certutil -L -d /var/lib/pki/pki-tomcat/conf/alias

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

ca_signing                                                   CTu,Cu,Cu
ca_ocsp_signing                                              u,u,u
subsystem                                                    u,u,u
ca_audit_signing                                             u,u,Pu
sslserver                                                    u,u,u
....

== Verifying admin certificate 

. Import the CA signing certificate:
+
[literal]
....
$ pki nss-cert-import --cert ca_signing.crt --trust CT,C,C ca_signing
....

. Import admin certificate and key into the client NSS database (by default ~/.dogtag/nssdb) with the following command:
+
[literal]
....
$ pki -c Secret.123 pkcs12-import \
    --pkcs12 ~/.dogtag/pki-tomcat/ca_admin_cert.p12 \
    --pkcs12-password Secret.123
....

. Verify that the admin certificate can be used to access the CA subsystem by executing the following command:
+
[literal]
....
$ pki -c Secret.123 -n caadmin ca-user-show caadmin
--------------
User "caadmin"
--------------
  User ID: caadmin
  Full name: caadmin
  Email: caadmin@example.com
  Type: adminType
  State: 1
....
