:_mod-docs-content-type: PROCEDURE

[id="installing-ca-with-external-ca-signing-certificate"]
= Installing CA with external CA signing certificate 

An external CA is a CA that is not in the same security domain as that of the PKI subsystem that is being installed.

Follow this process to install a CA subsystem with an external CA signing certificate.

Prior to installation, ensure that the xref:../others/installation-prerequisites.adoc[Installation Prerequisites] are configured.

== Starting a CA subsystem installation 

Prepare a file, for example `ca-external-cert-step1.cfg`, that contains the first deployment configuration.

A sample deployment configuration is available at xref:../../../base/server/examples/installation/ca-external-cert-step1.cfg[/usr/share/pki/server/examples/installation/ca-external-cert-step1.cfg]

Execute the following command:
[literal]
....
$ pkispawn -f ca-external-cert-step1.cfg -s CA
....

It installs a CA subsystem in a Tomcat instance (default is pki-tomcat) and creates the following NSS databases:

* server NSS database: /var/lib/pki/pki-tomcat/conf/alias
* admin NSS database: ~/.dogtag/pki-tomcat/ca/alias

It also generates the CA signing key in the server NSS database and the CSR in the specified path.

== Generating a CA signing certificate 

Use the CSR to issue the CA signing certificate:

* For root CA installation, generate a self-signed CA signing certificate.

* For subordinate CA installation, submit the CSR to an external CA to issue the CA signing certificate.

Store the CA signing certificate in a file, for example `ca_signing.crt`. The CA signing certificate can be specified as a single certificate or a PKCS #7 certificate chain in PEM format.

If the CA signing certificate was issued by an external CA, store the external CA certificate chain in a file, for example `root-ca_signing.crt`.

The certificate chain can be specified as a single certificate or a PKCS #7 certificate chain in PEM format.

The certificate chain should include all CA certificates from the root CA to the external CA that issued the CA signing certificate, but it should not include the CA signing certificate itself.

// See also:
// 
// * link:https://github.com/dogtagpki/pki/wiki/Generating-CA-Signing-Certificate[Generating CA Signing Certificate]

== Finishing the CA subsystem installation 

. Prepare another file, for example `ca-external-cert-step2.cfg`, that contains the second deployment configuration. The file can be created from the first file, that is `ca-external-cert-step1.cfg`, with the following changes:
+
[literal]
....
pki_external_step_two=True
....

. Specify the custom CA signing certificate with the following parameter:
+
[literal]
....
pki_ca_signing_cert_path=ca_signing.crt
....

. If the CA signing certificate was issued by an external CA, specify the external CA certificate chain with the following parameters:
+
[literal]
....
pki_cert_chain_nickname=root-ca_signing
pki_cert_chain_path=root-ca_signing.crt
....
+
A sample deployment configuration is available at xref:../../../base/server/examples/installation/ca-external-cert-step2.cfg[/usr/share/pki/server/examples/installation/ca-external-cert-step2.cfg].

. Execute the following command:
+
[literal]
....
$ pkispawn -f ca-external-cert-step2.cfg -s CA
....

== Verifying system certificates 

Verify that the server NSS database contains the following certificates:
[literal]
....
$ certutil -L -d /var/lib/pki/pki-tomcat/conf/alias

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

root-ca_signing                                              CT,C,C
ca_signing                                                   CTu,Cu,Cu
ca_ocsp_signing                                              u,u,u
subsystem                                                    u,u,u
ca_audit_signing                                             u,u,Pu
sslserver                                                    u,u,u
....

== Verifying admin certificate 

. Import the external CA certificate chain:
+
[literal]
....
$ pki -c Secret.123 client-cert-import --ca-cert root-ca_signing.crt
....

. Import the CA signing certificate:
+
[literal]
....
$ pki nss-cert-import --cert ca_signing.crt --trust CT,C,C ca_signing
....

. Import the admin certificate and key into the client NSS database (by default ~/.dogtag/nssdb) with the following command:
+
[literal]
....
$ pki -c Secret.123 pkcs12-import \
    --pkcs12 ~/.dogtag/pki-tomcat/ca_admin_cert.p12 \
    --pkcs12-password Secret.123
....

. Verify that the admin certificate can be used to access the CA subsystem by executing the following command:
+
[literal]
....
$ pki -c Secret.123 -n caadmin ca-user-show caadmin
--------------
User "caadmin"
--------------
  User ID: caadmin
  Full name: caadmin
  Email: caadmin@example.com
  Type: adminType
  State: 1
....
