:_mod-docs-content-type: PROCEDURE

[id="installing-ca-clone"]
= Installing CA clone 

Follow this process to install a CA subsystem as a clone of an existing CA subsystem.

Prior to installation, ensure that the xref:../others/installation-prerequisites.adoc[Installation Prerequisites] are configured.

Additional useful tips:

* Ensure that the firewall on the master allows external access to LDAP from the clone.
* Ensure that the firewall on the clone allows external access to LDAP from the master.

== Exporting existing CA system certificates 

On the existing system, export the CA system certificates with the following command:
[literal]
....
$ pki-server ca-clone-prepare \
    --pkcs12-file ca-certs.p12 \
    --pkcs12-password Secret.123
....

The command exports the following certificates (including the certificate chain) and their keys into a PKCS #12 file:

* CA signing certificate
* OCSP signing certificate
* audit signing certificate
* subsystem certificate

Note that the existing SSL server certificate is not exported.

If necessary, third-party certificates, for example trust anchors, can be added into the same PKCS #12 file with the following command:
[literal]
....
$ pki -d /var/lib/pki/pki-tomcat/conf/alias -f /var/lib/pki/pki-tomcat/conf/password.conf \
    pkcs12-cert-import <nickname> \
    --pkcs12-file ca-certs.p12 \
    --pkcs12-password Secret.123 \
    --append
....

Optionally, the CSRs for the above certificates can be exported as well with the following commands:
[literal]
....
$ pki-server cert-export ca_signing \
    --csr-file ca_signing.csr

$ pki-server cert-export ca_ocsp_signing \
    --csr-file ca_ocsp_signing.csr

$ pki-server cert-export ca_audit_signing \
    --csr-file ca_audit_signing.csr

$ pki-server cert-export subsystem \
    --csr-file subsystem.csr
....

== SELinux permissions 

After copying the `ca-certs.p12` to the clone machine, ensure that appropriate SELinux rules are added:
[literal]
....
$ semanage fcontext -a -t pki_tomcat_cert_t ca-certs.p12
$ restorecon -R -v ca-certs.p12
....

Ensure that the `ca-certs.p12` file is owned by the `pkiuser`
[literal]
....
$ chown pkiuser:pkiuser ca-certs.p12
....

== Installing the CA subsystem 

Prepare a deployment configuration, for example `ca-clone-w-p12.cfg`, to deploy a CA subsystem clone. By default the subsystem is deployed into a Tomcat instance called `pki-tomcat`.

A sample deployment configuration is available at xref:../../../base/server/examples/installation/ca-clone-w-p12.cfg[/usr/share/pki/server/examples/installation/ca-clone-w-p12.cfg].

It assumes that the:

* The clone CA subsystem is running on a different machine than the primary. Note: In a test environment, if creating the clone on the same machine, the `pki_instance_name` and the port values (for PKI and DS) must be different.
* CA signing certificate has been exported into `ca_signing.crt`
* admin certificate and key have been exported into `ca_admin_cert.p12`
* PKCS #12 password is specified in the `pki_client_pkcs12_password` parameter.
* The CA is not using an HSM (which is a different installation case covered in section *Installing CA clone with HSM*).

See xref:installing-ca.adoc[CA installation] for details.

If the CSRs are available, they can be specified with the following parameters:
[literal]
....
pki_ca_signing_csr_path=ca_signing.csr
pki_ocsp_signing_csr_path=ca_ocsp_signing.csr
pki_audit_signing_csr_path=ca_audit_signing.csr
pki_subsystem_csr_path=subsystem.csr
....

To start the installation, execute the following command:
[literal]
....
$ pkispawn -f ca-clone-w-p12.cfg -s CA
....

== CA system certificates 

After installation the existing CA system certificates (including the certificate chain)
and their keys are stored in the server NSS database (i.e. `/var/lib/pki/pki-tomcat/conf/alias`),
and a new SSL server certificate is created for the new instance:
[literal]
....
$ certutil -L -d /var/lib/pki/pki-tomcat/conf/alias

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

ca_signing                                                   CTu,Cu,Cu
ca_ocsp_signing                                              u,u,u
subsystem                                                    u,u,u
ca_audit_signing                                             u,u,Pu
sslserver                                                    u,u,u
....

If necessary, the certificates can be exported into PEM files with the following command:
[literal]
....
$ pki-server cert-export <cert ID> --cert-file <filename>
....

The valid certificate IDs for CA are:

* `ca_signing`
* `ca_ocsp_signing`
* `ca_audit_signing`
* `subsystem`
* `sslserver`

Note that the `pki-server cert-export` command takes a certificate ID instead of a nickname. For simplicity the nicknames in this example are configured to be the same as the certificate IDs.

== Admin certificate 

To use the admin certificate, do the following.

. Import the CA signing certificate into the client NSS database:
+
[literal]
....
$ pki nss-cert-import --cert ca_signing.crt --trust CT,C,C ca_signing
....

. Import the admin certificate and key into the client NSS database (by default ~/.dogtag/nssdb) with the following command:
+
[literal]
....
$ pki pkcs12-import \
    --pkcs12 ca_admin_cert.p12 \
    --pkcs12-password Secret.123
....

. To verify that the admin certificate can be used to access the CA subsystem clone, execute the following command:
+
[literal]
....
$ pki -n caadmin ca-user-show caadmin
--------------
User "caadmin"
--------------
  User ID: caadmin
  Full name: caadmin
  Email: caadmin@example.com
  Type: adminType
  State: 1
....
