:_mod-docs-content-type: PROCEDURE

[id="installing-ca-with-hsm"]
= Installing CA with HSM 

Follow this process to install a CA subsystem with a self-signed CA signing certificate
where the system certificates and their keys are stored in HSM.

Prior to installation, please ensure that the xref:../others/installation-prerequisites.adoc[Installation Prerequisites] are configured.

== CA Subsystem Installation 
Prepare a file, for example `ca.cfg`, that contains the deployment configuration:

[literal,subs="+quotes,verbatim"]
----
[DEFAULT]
pki_instance_name=pki-tomcat
pki_https_port=8443
pki_http_port=8080
pki_server_database_password=Secret.123

pki_hsm_enable=True
pki_hsm_libfile=/usr/lib64/pkcs11/libsofthsm2.so
pki_hsm_modulename=softhsm
pki_token_name=HSM
pki_token_password=Secret.HSM

[Tomcat]
pki_ajp_port=8009
pki_tomcat_server_port=8005

[CA]
pki_admin_email=caadmin@example.com
pki_admin_name=caadmin
pki_admin_nickname=caadmin
pki_admin_password=Secret.123
pki_admin_uid=caadmin

pki_client_pkcs12_password=Secret.123

pki_ds_url=ldap://localhost.localdomain:389
pki_ds_base_dn=dc=ca,dc=pki,dc=example,dc=com
pki_ds_database=ca
pki_ds_password=Secret.123

pki_security_domain_name=EXAMPLE

pki_ca_signing_nickname=ca_signing
pki_ocsp_signing_nickname=ca_ocsp_signing
pki_audit_signing_nickname=ca_audit_signing
pki_sslserver_nickname=sslserver/pki.example.com
pki_subsystem_nickname=subsystem
----

Then execute the following command:

[literal,subs="+quotes,verbatim"]
....
$ pkispawn -f ca.cfg -s CA
....

It will install CA subsystem in a Tomcat instance (default is pki-tomcat) and create the following NSS databases:

* server NSS database: /var/lib/pki/pki-tomcat/conf/alias
* admin NSS database: ~/.dogtag/pki-tomcat/ca/alias

== Verifying System Certificates 
Verify that the internal token contains the following certificates:

[literal,subs="+quotes,verbatim"]
....
$ certutil -L -d /var/lib/pki/pki-tomcat/conf/alias

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

ca_signing                                                   CT,C,C
ca_audit_signing                                             ,,P
....

Verify that the HSM contains the following certificates:

[literal,subs="+quotes,verbatim"]
....
$ certutil -L -d /var/lib/pki/pki-tomcat/conf/alias -h HSM -f HSM.pwd

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

HSM:ca_signing                                               CTu,Cu,Cu
HSM:ca_ocsp_signing                                          u,u,u
HSM:subsystem                                                u,u,u
HSM:ca_audit_signing                                         u,u,Pu
HSM:sslserver/pki.example.com                                u,u,u
....

== Verifying Admin Certificate 

Import the CA signing certificate:

[literal,subs="+quotes,verbatim"]
....
$ pki nss-cert-import --cert ca_signing.crt --trust CT,C,C ca_signing
....

Import admin certificate and key into the client NSS database (by default ~/.dogtag/nssdb) with the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki -c Secret.123 pkcs12-import \
    --pkcs12 ~/.dogtag/pki-tomcat/ca_admin_cert.p12 \
    --pkcs12-password Secret.123
....

Verify that the admin certificate can be used to access the CA subsystem by executing the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki -c Secret.123 -n caadmin ca-user-show caadmin
--------------
User "caadmin"
--------------
  User ID: caadmin
  Full name: caadmin
  Email: caadmin@example.com
  Type: adminType
  State: 1
....
