:_mod-docs-content-type: PROCEDURE

[id="installing-ca-clone_{context}"]
= Installing CA Clone 

Follow this process to install a CA subsystem as a clone of an existing CA subsystem.

Prior to installation, please ensure that the xref:../others/installation-prerequisites.adoc[Installation Prerequisites] are configured.

Additional useful tips:

- Make sure the firewall on the master allows external access to LDAP from the clone
- Make sure the firewall on the clone allows external access to LDAP from the master
- Not having a `dc=pki,dc=example,dc=com` entry in LDAP will give the same error as not being able to connect to the LDAP server.

== Exporting Existing CA System Certificates 

On the existing system, export the CA system certificates with the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki-server ca-clone-prepare \
    --pkcs12-file ca-certs.p12 \
    --pkcs12-password Secret.123
....

The command will export the following certificates (including the certificate chain) and their keys into a PKCS #12 file:

* CA signing certificate
* OCSP signing certificate
* audit signing certificate
* subsystem certificate

Note that the existing SSL server certificate will not be exported.

If necessary, third-party certificates, for example trust anchors, can be added into the same PKCS #12 file with the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki -d /var/lib/pki/pki-tomcat/conf/alias -f /var/lib/pki/pki-tomcat/conf/password.conf \
    pkcs12-cert-import <nickname> \
    --pkcs12-file ca-certs.p12 \
    --pkcs12-password Secret.123 \
    --append
....

Optionally, the CSRs for the above certificates can be exported as well with the following commands:

[literal,subs="+quotes,verbatim"]
....
$ pki-server cert-export ca_signing \
    --csr-file ca_signing.csr

$ pki-server cert-export ca_ocsp_signing \
    --csr-file ca_ocsp_signing.csr

$ pki-server cert-export ca_audit_signing \
    --csr-file ca_audit_signing.csr

$ pki-server cert-export subsystem \
    --csr-file subsystem.csr
....

== SELinux Permissions 

After copying the `ca-certs.p12` to the clone machine, ensure that appropriate SELinux rules are added:

----
$ semanage fcontext -a -t pki_tomcat_cert_t ca-certs.p12
$ restorecon -R -v ca-certs.p12
----

Also, make sure the `ca-certs.p12` file is owned by the `pkiuser`

----
$ chown pkiuser:pkiuser ca-certs.p12
----

== CA Subsystem Installation 

Prepare a deployment configuration, for example `ca-clone.cfg`, to deploy CA subsystem clone.
By default the subsystem is deployed into a Tomcat instance called `pki-tomcat`.

A sample deployment configuration is available at xref:../../../base/server/examples/installation/ca-clone.cfg[/usr/share/pki/server/examples/installation/ca-clone.cfg].
It assumes that the primary CA subsystem is running at https://primary.example.com:8443,
the CA signing certificate has been exported into `ca_signing.crt`,
and the admin certificate and key have been exported into `ca_admin_cert.p12`.
The PKCS #12 password is specified in the `pki_client_pkcs12_password` parameter.
See xref:installing-ca.adoc[CA installation] for details.

If the CSRs are available, they can be specified with the following parameters:

[literal,subs="+quotes,verbatim"]
....
pki_ca_signing_csr_path=ca_signing.csr
pki_ocsp_signing_csr_path=ca_ocsp_signing.csr
pki_audit_signing_csr_path=ca_audit_signing.csr
pki_subsystem_csr_path=subsystem.csr
....

To start the installation execute the following command:

[literal,subs="+quotes,verbatim"]
....
$ pkispawn -f ca-clone.cfg -s CA
....

== CA System Certificates 

After installation the existing CA system certificates (including the certificate chain)
and their keys are stored in the server NSS database (i.e. `/var/lib/pki/pki-tomcat/conf/alias`),
and a new SSL server certificate is created for the new instance:

[literal,subs="+quotes,verbatim"]
....
$ certutil -L -d /var/lib/pki/pki-tomcat/conf/alias

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

ca_signing                                                   CTu,Cu,Cu
ca_ocsp_signing                                              u,u,u
subsystem                                                    u,u,u
ca_audit_signing                                             u,u,Pu
sslserver                                                    u,u,u
....

If necessary, the certificates can be exported into PEM files with the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki-server cert-export <cert ID> --cert-file <filename>
....

The valid certificate IDs for CA are:

* `ca_signing`
* `ca_ocsp_signing`
* `ca_audit_signing`
* `subsystem`
* `sslserver`

Note that the `pki-server cert-export` command takes a certificate ID instead of a nickname.
For simplicity the nicknames in this example are configured to be the same as the certificate IDs.

== Admin Certificate 

To use the admin certificate from the primary CA subsystem, prepare a client NSS database (default is `~/.dogtag/nssdb`):

[literal,subs="+quotes,verbatim"]
....
$ pki client-init
....

Then import the CA signing certificate into the client NSS database:

[literal,subs="+quotes,verbatim"]
....
$ pki nss-cert-import --cert ca_signing.crt -trust CT,C,C ca_signing
....

Finally, import admin certificate and key with the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki pkcs12-import \
    --pkcs12 ca_admin_cert.p12 \
    --pkcs12-password Secret.123
....

To verify that the admin certificate can be used to access the CA subsystem clone, execute the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki -n caadmin ca-user-show caadmin
--------------
User "caadmin"
--------------
  User ID: caadmin
  Full name: caadmin
  Email: caadmin@example.com
  Type: adminType
  State: 1
....
