:_mod-docs-content-type: PROCEDURE

[id="installing-ca"]
= Installing a CA 

Follow this process to install a CA subsystem instance with a self-signed CA signing certificate. It is also known as a "root CA".

Prior to installation, ensure that the xref:../others/installation-prerequisites.adoc[Installation Prerequisites] are configured.

== Installing the CA subsystem  

Prepare a deployment configuration, for example `ca.cfg`, to deploy CA subsystem. By default the subsystem is deployed into a Tomcat instance called `pki-tomcat`.

A sample deployment configuration is available at xref:../../../base/server/examples/installation/ca.cfg[/usr/share/pki/server/examples/installation/ca.cfg].

To start the installation execute the following command:
[literal,subs="+quotes,verbatim"]
....
$ pkispawn -f ca.cfg -s CA
....

== CA system certificates 

After installation, the CA system certificates and keys are stored in the server NSS database (i.e. `/var/lib/pki/pki-tomcat/conf/alias`):
[literal,subs="+quotes,verbatim"]
....
$ certutil -L -d /var/lib/pki/pki-tomcat/conf/alias

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

ca_signing                                                   CTu,Cu,Cu
ca_ocsp_signing                                              u,u,u
subsystem                                                    u,u,u
ca_audit_signing                                             u,u,Pu
sslserver                                                    u,u,u
....

If necessary, the certificates can be exported into PEM files by using the following command:
[literal,subs="+quotes,verbatim"]
....
$ pki-server cert-export <cert ID> --cert-file <filename>
....

The valid certificate IDs for CA are:

* `ca_signing`
* `ca_ocsp_signing`
* `ca_audit_signing`
* `subsystem`
* `sslserver`

Note that the `pki-server cert-export` command takes a certificate ID instead of a nickname.
For simplicity the nicknames in this example are configured to be the same as the certificate ID.

== Admin certificate 

After installation the admin certificate and key are stored in `~/.dogtag/pki-tomcat/ca_admin_cert.p12`.

The PKCS #12 password is specified in the `pki_client_pkcs12_password` parameter.

To use the admin certificate, do the following.

. Export the CA signing certificate from the server NSS database:
+
[literal,subs="+quotes,verbatim"]
....
$ pki-server cert-export ca_signing --cert-file ca_signing.crt
....

. Import the CA signing certificate into the client NSS database:
+
[literal,subs="+quotes,verbatim"]
....
$ pki nss-cert-import --cert ca_signing.crt --trust CT,C,C ca_signing
....

. Import the admin certificate and key into the client NSS database (by default ~/.dogtag/nssdb) with the following command:
+
[literal,subs="+quotes,verbatim"]
....
$ pki pkcs12-import \
    --pkcs12 ~/.dogtag/pki-tomcat/ca_admin_cert.p12 \
    --pkcs12-password Secret.123
....

. Verify that the admin certificate can be used to access the CA subsystem by executing the following command:
+
[literal,subs="+quotes,verbatim"]
....
$ pki -n caadmin ca-user-show caadmin
--------------
User "caadmin"
--------------
  User ID: caadmin
  Full name: caadmin
  Email: caadmin@example.com
  Type: adminType
  State: 1
....
