// This original content was copied to installing-ca-clone-with-temp-ldaps-connection.adoc
:_mod-docs-content-type: PROCEDURE

[id="installing-ca-clone-with-ldaps-connection_{context}"]
= Installing CA Clone with LDAPS Connection 

Follow this process to install a CA subsystem as clone of an existing CA subsystem with a secure database connection.

Prior to installation, please ensure that the xref:../others/installation-prerequisites.adoc[Installation Prerequisites] are configured.

== DS Configuration 

Once the prerequisites listed above are completed on the clone system, follow the procedure to xref:../others/getting-ds-cert-issued-by-actual-ca.adoc[enable SSL Connection with DS] so that the CA clone's DS is running with SSL enabled wtih a real server certificate issued by the CA.

Some useful tips:

 - Make sure the firewall on the master allows external access to LDAP from the clone
 - Make sure the firewall on the clone allows external access to LDAP from the master
 - Not having a `dc=pki,dc=example,dc=com` entry in LDAP will give the same error as
       not being able to connect to the LDAP server.


== Exporting Existing CA System Certificates 

On the existing system, export the CA system certificates and copy to clone system with the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki-server ca-clone-prepare --pkcs12-file ca-certs.p12 --pkcs12-password Secret.123
$ pki-server cert-export ca_signing --cert-file ca_signing.crt
....

The command will export the following certificates (including the certificate chain) and their keys into a PKCS #12 file:

* CA signing certificate
* OCSP signing certificate
* audit signing certificate
* subsystem certificate

Note that the existing SSL server certificate is not exported.

If necessary, third-party certificates, for example trust anchors, can be added into the same PKCS #12 file with the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki -d /var/lib/pki/pki-tomcat/conf/alias -f /var/lib/pki/pki-tomcat/conf/password.conf \
    pkcs12-cert-import <nickname> \
    --pkcs12-file ca-certs.p12 \
    --pkcs12-password Secret.123 \
    --append
....

== SELinux Permissions 

After copying the `ca-certs.p12` to the clone machine, ensure that appropriate SELinux rules are added:

----
$ semanage fcontext -a -t pki_tomcat_cert_t ca-certs.p12
$ restorecon -R -v ca-certs.p12
----

Also, make sure the `ca-certs.p12` file is owned by the `pkiuser`

----
$ chown pkiuser:pkiuser ca-certs.p12
----

== CA Subsystem Installation 

Prepare a deployment configuration, for example `ca-secure-ds-secondary.cfg`, to deploy CA subsystem clone.
By default the subsystem is deployed into a Tomcat instance called `pki-tomcat`.

*Note:* The sample pkispawn config file referenced below expects the DS server certificate's signing certificate to be in a file named ds_signing.crt.  Since we are using the existing CA as the signing cert, copy the CA's signing cert into ds_signing.crt:
// The ds_signing.crt is the same as ca_signing.crt in this case
// Will that work?

[literal,subs="+quotes,verbatim"]
....
$ cp ca_signing.crt ds_signing.crt
....

A sample deployment configuration is available at xref:../../../base/server/examples/installation/ca-secure-ds-secondary.cfg[/usr/share/pki/server/examples/installation/ca-secure-ds-secondary.cfg].
It assumes that the existing CA and DS instances are running on primary.example.com, and the new CA and DS clones are being installed on secondary.example.com,
the CA signing certificate has been exported into `ca_signing.crt`,
and the admin certificate and key have been exported into `ca_admin_cert.p12`.
The PKCS #12 password is specified in the `pki_client_pkcs12_password` parameter.

To start the installation execute the following command:

[literal,subs="+quotes,verbatim"]
....
$ pkispawn -f ca-secure-ds-secondary.cfg -s CA
....

== CA System Certificates 

After installation the existing CA system certificates (including the certificate chain)
and their keys are stored in the server NSS database (i.e. `/var/lib/pki/pki-tomcat/conf/alias`),
and a new SSL server certificate is created for the new instance:

[literal,subs="+quotes,verbatim"]
....
$ certutil -L -d /var/lib/pki/pki-tomcat/conf/alias

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

subsystem                                                    u,u,u
ca_signing                                                   CTu,Cu,Cu
ca_ocsp_signing                                              u,u,u
ca_audit_signing                                             u,u,Pu
ds_signing                                                   CT,C,C
sslserver                                                    u,u,u
....

If necessary, the clone CA system certificates can be exported into PEM files with the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki-server cert-export <cert ID> --cert-file <filename>
....

The valid certificate IDs for CA are:

* `ca_signing`
* `ca_ocsp_signing`
* `ca_audit_signing`
* `subsystem`
* `sslserver`

Note that the `pki-server cert-export` command takes a certificate ID instead of a nickname.
For simplicity the nicknames in this example are configured to be the same as the certificate IDs.

== Admin Certificate 

To use the admin certificate from the primary CA subsystem, prepare a client NSS database (default is `~/.dogtag/nssdb`):

[literal,subs="+quotes,verbatim"]
....
$ pki client-init
....

Then import the CA signing certificate into the client NSS database:

[literal,subs="+quotes,verbatim"]
....
$ pki nss-cert-import --cert ca_signing.crt --trust CT,C,C ca_signing
....

Finally, import admin certificate and key with the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki pkcs12-import \
    --pkcs12 ca_admin_cert.p12 \
    --pkcs12-password Secret.123
....

To verify that the admin certificate can be used to access the CA subsystem clone, execute the following command:

[literal,subs="+quotes,verbatim"]
....
$ pki -n caadmin ca-user-show caadmin
--------------
User "caadmin"
--------------
  User ID: caadmin
  Full name: caadmin
  Email: caadmin@example.com
  Type: adminType
  State: 1
....
