= Server Changes =

== Add pki_ds_url parameter ==

A new `pki_ds_url` parameter has been added for `pkispawn` to replace the following parameters:

* `pki_ds_hostname`
* `pki_ds_ldap_port`
* `pki_ds_ldaps_port`
* `pki_ds_secure_connection`

== Add pki_http_enable parameter ==

A new `pki_http_enable` parameter has been added for `pkispawn`
to enable/disable the plain HTTP connector in `server.xml`.
The default value is `True`.

== Remove cert and CSR from _CS.cfg_ ==

The parameters `<subsystem_name>.<cert_id>.cert` and `<subsystem_name>.<cert_id>.certreq` are removed from `CS.cfg` files.
Certificates are retrieved from the nssdb configured and they are not stored in other places.
CSR are stored in the folder `<instance_config>/certs` as `<cert_nickname>.csr` and they are retrieved from this location.

== New validity parameters for NSS Issuer in ACME ==

The `NSSIssuer` in ACME has been modified to provide `validityLength`
and `validityUnit` parameters to specify the certificate validity.
The default is 3 months.

The `monthsValid` parameter has been deprecated.

== Enable Random Serial Numbers v3 by Default ==

New CA and KRA installations will have Random Serial Numbers v3 enabled by default.
Existing installations will not be affected.

To migrate existing installations with the legacy sequential serial numbers or RandomSerial Numbers v1 to Random Serial Numbers v3 follow these instructions:

* link:https://github.com/dogtagpki/pki/wiki/Configuring-CA-with-Random-Serial-Numbers-v3[Configuring CA with Random Serial Numbers v3]
* link:https://github.com/dogtagpki/pki/wiki/Configuring-KRA-with-Random-Serial-Numbers-v3[Configuring KRA with Random Serial Numbers v3]

To install a new CA with the legacy sequential serial numbers specify the following parameters:

* `pki_cert_id_generator=legacy`
* `pki_request_id_generator=legacy`

To install a new CA with the legacy Random Serial Numbers v1 specify the following parameters:

* `pki_cert_id_generator=legacy`
* `pki_request_id_generator=legacy`
* `pki_random_serial_numbers_enable=True`

To install a new KRA with the legacy sequential serial numbers specify the following parameters:

* `pki_key_id_generator=legacy`
* `pki_request_id_generator=legacy`


== Add pki_<cert_id>_opsFlag and pki_<cert_id>_opsFlagMask parameters ==

Two new parameters are added to pkispawn configuration for setting the key flags in HSM.
The new parameters are available for all certificates created during the subsystem installation
and their value is a comma separated list of the following flags: encrypt, decrypt, sign,
sign_recover, verify, verify_recover, wrap, unwrap and derive. The first parameter add flags to
the list identified by underneath module while the second remove them.
Default values are empty lists to get the HSM default key flags.
