= Server Changes =

== Add pki_ds_url parameter ==

A new `pki_ds_url` parameter has been added for `pkispawn` to replace the following parameters:

* `pki_ds_hostname`
* `pki_ds_ldap_port`
* `pki_ds_ldaps_port`
* `pki_ds_secure_connection`

== Add pki_http_enable parameter ==

A new `pki_http_enable` parameter has been added for `pkispawn`
to enable/disable the plain HTTP connector in `server.xml`.
The default value is `True`.

== Remove cert and CSR from _CS.cfg_ ==

The parameters `<subsystem_name>.<cert_id>.cert` and `<subsystem_name>.<cert_id>.certreq` are removed from `CS.cfg` files.
Certificates are retrieved from the nssdb configured and they are not stored in other places.
CSR are stored in the folder `<instance_config>/certs` as `<cert_nickname>.csr` and they are retrieved from this location.

== New validity parameters for NSS Issuer in ACME ==

The `NSSIssuer` in ACME has been modified to provide `validityLength`
and `validityUnit` parameters to specify the certificate validity.
The default is 3 months.

The `monthsValid` parameter has been deprecated.
