= Tools Changes =

== New pki-server cert-validate CLI ==

The `pki-server cert-validate` command has been added to validate a system certificate.

== New SAN option for pki nss-cert CLIs ==

The `pki nss-cert-request` and `pki nss-cert-issue` commands have been
modified to provide a `--subjectAltName` option.
This option will override the `subjectAltName` parameter in the extension
configuration file.

== Deprecate sslget ==

The `sslget` command has been deprecated.
Use `pki` CLI or the `curl` command instead.

== Drop DRMTool ==

The `DRMTool` command is no longer available.
Use `KRATool` command instead.

== New validity options for pki nss-cert-issue CLI ==

The `pki nss-cert-issue` command has been modified to provide
`--validity-length` and `--validity-unit` options to specify
the certificate validity. The default is 3 months.

The `--months-valid` option has been deprecated.

== New pki nss-cert-del CLI ==

The `pki nss-cert-del` command has been added to delete a certificate from NSS database.

== Deprecate pki client-cert-del ==

The `pki client-cert-del` command has been deprecated.
Use `pki nss-cert-del` command instead.

== New pki-server cert-request CLI ==

The `pki-server cert-request` command has been added to generate a key pair and an enrollment request for a system certificate.

== Update pki-server cert-create CLI ==

The `pki-server cert-create` command has been updated to support
creating permanent system certificate using the server's NSS database
and RSNv3 serial numbers.

== Update pki-server cert-import CLI ==

The `pki-server cert-import` command has been updated to provide
options to specify the certificate nickname and token name.

== Update pki-server status CLI ==

The `pki-server status` command has been updated to no longer show
whether a subsystem is a new subsystem or a clone since there is no
distinction between them.

== New opsFlagMask options for pki nss-key-create CLI ==

The `pki nss-key-create` command has been modified to support the option `--ops-flag-mask`
to specify a list of flags to set for the new key.
