= Tools Changes =

== New pki-server cert-validate CLI ==

The `pki-server cert-validate` command has been added to validate a system certificate.

== New SAN option for pki nss-cert CLIs ==

The `pki nss-cert-request` and `pki nss-cert-issue` commands have been
modified to provide a `--subjectAltName` option.
This option will override the `subjectAltName` parameter in the extension
configuration file.

== Deprecate sslget ==

The `sslget` command has been deprecated.
Use `pki` CLI or the `curl` command instead.

== Drop DRMTool ==

The `DRMTool` command is no longer available.
Use `KRATool` command instead.

== New validity options for pki nss-cert-issue CLI ==

The `pki nss-cert-issue` command has been modified to provide
`--validity-length` and `--validity-unit` options to specify
the certificate validity. The default is 3 months.

The `--months-valid` option has been deprecated.

== New pki nss-cert-del CLI ==

The `pki nss-cert-del` command has been added to delete a certificate from NSS database.

== Deprecate pki client-cert-del ==

The `pki client-cert-del` command has been deprecated.
Use `pki nss-cert-del` command instead.

== New pki-server cert-request CLI ==

The `pki-server cert-request` command has been added to generate a key pair and an enrollment request for a system certificate.
