#!/bin/bash
# BEGIN COPYRIGHT BLOCK
# (C) 2010 Red Hat, Inc.
# All rights reserved.
# END COPYRIGHT BLOCK

##
## Include common 'compose' functions
##

COMPOSE_PWD=`dirname $0`
source ${COMPOSE_PWD}/compose_functions


## Always switch into the base directory three levels
## above this shell script prior to executing it so
## that all of its output is written to this directory

cd `dirname $0`/../..


##
## Retrieve the name of this base directory
##

PKI_PWD=`pwd`


##
## Establish the 'pki-console' name and version information
##

PKI_CONSOLE="pki-console"
PKI_CONSOLE_VERSION="10.1.0"


##
## Establish the SOURCE files/directories of the 'pki-console' source directory
##

PKI_SPECS_FILE="${PKI_DIR}/specs/${PKI_CONSOLE}.spec"
PKI_COMPONENT_LIST="test console"


##
## Establish the TARGET files/directories of the 'pki-console' source/spec files
##

if [ $WORK_DIR ]; then
    PKI_PACKAGES="`cd $WORK_DIR ; pwd`"
else
    PKI_PACKAGES="${PKI_PWD}/packages"
fi

PKI_CONSOLE_BUILD_DIR="${PKI_PACKAGES}/BUILD"
PKI_CONSOLE_RPMS_DIR="${PKI_PACKAGES}/RPMS"
PKI_CONSOLE_SOURCES_DIR="${PKI_PACKAGES}/SOURCES"
PKI_CONSOLE_SPECS_DIR="${PKI_PACKAGES}/SPECS"
PKI_CONSOLE_SRPMS_DIR="${PKI_PACKAGES}/SRPMS"

PKI_CONSOLE_TARBALL="${PKI_CONSOLE}-${PKI_CONSOLE_VERSION}.tar.gz"
PKI_CONSOLE_SPEC_FILE="${PKI_CONSOLE_SPECS_DIR}/${PKI_CONSOLE}.spec"
PKI_CONSOLE_PACKAGE_SCRIPT="${PKI_PACKAGES}/package_${PKI_CONSOLE}"
PKI_CONSOLE_PACKAGE_COMMAND="${RPMBUILD_CMD} SPECS/${PKI_CONSOLE}.spec"

PKI_CONSOLE_STAGING_DIR="${PKI_PACKAGES}/staging"
PKI_CONSOLE_DIR="${PKI_CONSOLE_STAGING_DIR}/${PKI_CONSOLE}-${PKI_CONSOLE_VERSION}"
PKI_CONSOLE_BASE_DIR="${PKI_CONSOLE_DIR}/base"


##
## Always create a top-level 'packages' directory
##

mkdir -p ${PKI_PACKAGES}


##
## Always create 'pki-console' package directories
##

mkdir -p ${PKI_CONSOLE_BUILD_DIR}
mkdir -p ${PKI_CONSOLE_RPMS_DIR}
mkdir -p ${PKI_CONSOLE_SOURCES_DIR}
mkdir -p ${PKI_CONSOLE_SPECS_DIR}
mkdir -p ${PKI_CONSOLE_SRPMS_DIR}


##
## Always start with new 'pki-console' package files
##

rm -rf ${PKI_CONSOLE_BUILD_DIR}/${PKI_CONSOLE}-${PKI_CONSOLE_VERSION}
rm -f  ${PKI_CONSOLE_RPMS_DIR}/${PKI_CONSOLE}-${PKI_CONSOLE_VERSION}*.rpm
rm -f  ${PKI_CONSOLE_SOURCES_DIR}/${PKI_CONSOLE_TARBALL}
rm -f  ${PKI_CONSOLE_SPEC_FILE}
rm -f  ${PKI_CONSOLE_SRPMS_DIR}/${PKI_CONSOLE}-${PKI_CONSOLE_VERSION}*.rpm


##
## Copy a new 'pki-console' spec file from the
## current contents of the PKI working repository
##

cp -p ${PKI_SPECS_FILE} ${PKI_CONSOLE_SPECS_DIR}


##
## If specified, copy all Patches from the spec file URL to SOURCES
##

if [ ${FETCH_PATCH_FILES} -eq 1 ] ; then
	Fetch_Patch_Files ${PKI_SPECS_FILE} ${PKI_CONSOLE_SOURCES_DIR}
fi


##
## Copy the specified Source Tarball from the spec file URL to SOURCES, or
## Generate a fresh Source Tarball from the local source
##

if [ ${FETCH_SOURCE_TARBALL} -eq 1 ] ; then
	Fetch_Source_Tarball ${PKI_SPECS_FILE} ${PKI_CONSOLE_SOURCES_DIR}
else
	##
	## Always start with a new 'pki-console' staging directory
	##

	rm -rf ${PKI_CONSOLE_STAGING_DIR}


	##
	## To generate the 'pki-console' tarball, construct a staging area
	## consisting of the 'pki-console' source components from the
	## current contents of the PKI working repository
	##

	mkdir -p ${PKI_CONSOLE_DIR}
	cd ${PKI_DIR}
	for file in "${PKI_FILE_LIST}" ;
	do
		cp -p ${file} ${PKI_CONSOLE_DIR}
	done
	find ${PKI_CMAKE_DIR}             \
		-name .svn -prune -o          \
		-name *.swp -prune -o         \
		-print | cpio -pdum ${PKI_CONSOLE_DIR} > /dev/null 2>&1
	cd - > /dev/null 2>&1

	mkdir -p ${PKI_CONSOLE_BASE_DIR}
	cd ${PKI_BASE_DIR}
	cp -p ${PKI_BASE_MANIFEST} ${PKI_CONSOLE_BASE_DIR}
	for component in "${PKI_COMPONENT_LIST}" ;
	do
		find ${component}             \
		-name .svn -prune -o          \
		-name *.swp -prune -o         \
		-print | cpio -pdum ${PKI_CONSOLE_BASE_DIR} > /dev/null 2>&1
	done
	cd - > /dev/null 2>&1


	##
	## Create the 'pki-console' tarball
	##

	mkdir -p ${PKI_CONSOLE_SOURCES_DIR}
	cd ${PKI_CONSOLE_STAGING_DIR}
	gtar -zcvf ${PKI_CONSOLE_TARBALL}    \
		"${PKI_CONSOLE}-${PKI_CONSOLE_VERSION}" > /dev/null 2>&1
	mv ${PKI_CONSOLE_TARBALL} ${PKI_CONSOLE_SOURCES_DIR}
	cd - > /dev/null 2>&1


	##
	## Always remove the PKI staging area
	##

	rm -rf ${PKI_CONSOLE_STAGING_DIR}
fi


##
## Always generate a fresh 'pki-console' package script
##

rm -rf ${PKI_CONSOLE_PACKAGE_SCRIPT}
printf "#!/bin/bash\n\n"                    >  ${PKI_CONSOLE_PACKAGE_SCRIPT}
printf "${PKI_CONSOLE_PACKAGE_COMMAND}\n\n" >> ${PKI_CONSOLE_PACKAGE_SCRIPT}
chmod 775 ${PKI_CONSOLE_PACKAGE_SCRIPT}


##
## Automatically invoke RPM/SRPM creation
##

cd ${PKI_PACKAGES} ;
bash ./package_${PKI_CONSOLE} | tee package_${PKI_CONSOLE}.log 2>&1

