#!/bin/sh
# BEGIN COPYRIGHT BLOCK
# (C) 2012 Red Hat, Inc.
# All rights reserved.
# END COPYRIGHT BLOCK

##  Always switch into this base directory
##  prior to script execution so that all
##  of its output is written to this directory

cd `dirname $0`


##
##  This script MUST be run as root!
##

ROOTUID=0

OS=`uname`
if [ "${OS}" = "Linux" ] ; then
    MY_EUID=`/usr/bin/id -u`
    MY_UID=`/usr/bin/id -ur`
    USERNAME=`/usr/bin/id -un`
else
    printf "ERROR:  Unsupported operating system '${OS}'!\n"
    exit 255
fi

if [ "${MY_UID}"  != "${ROOTUID}" ] &&
   [ "${MY_EUID}" != "${ROOTUID}" ] ; then
    printf "ERROR:  The '$0' script must be run as root!\n"
    exit 255
fi


if [ -f "/usr/lib64/java/jss4.jar" ] ; then
	JSS_TARGET=/usr/lib64/java/jss4.jar
	ARCH=64

elif [ -f "/usr/lib/java/jss4.jar" ] ; then
	JSS_TARGET=/usr/lib/java/jss4.jar
	ARCH=32

else
	printf "ERROR: jss4.jar not found\n"
	exit 255
fi

JSS_LINK=/usr/share/java/jss/jss4.jar

mkdir -p `dirname $JSS_LINK`
ln -sf $JSS_TARGET $JSS_LINK

printf "Created symlink to $ARCH-bit JSS library in $JSS_LINK.\n"
