:_mod-docs-content-type: PROCEDURE

[id="installing-est-pkispawn"]
= EST installation using `pkispawn` 

Once the prerequisites in xref:../est/installing-est.adoc[Installing EST] are configured, it is possible to install *EST*.


== Installation 

An example `pkispawn` installation configuration is provided in `/usr/share/pki/server/examples/installation/est.cfg` with the following content:

[literal]
....
[DEFAULT]
pki_server_database_password=Secret.123
pki_admin_setup=False

[EST]
est_realm_type=ds
est_realm_url=ldap://localhost.localdomain:389
est_realm_bind_password=Secret.123
pki_sslserver_nickname=sslserver
pki_subsystem_nickname=subsystem

pki_security_domain_name=EXAMPLE
pki_security_domain_user=caadmin
pki_security_domain_password=Secret.123
....


The following commands install an EST subsystem on a PKI server instance that already has a CA subsystem in it. By default the PKI server instance is called `pki-tomcat` and it  uses HTTP port `8080` and HTTPS port `8443`. To use a different instance name or port numbers refer to the command's manual page.

To install EST in the same instance of the CA and with the DS realm, run the command:

[literal]
....
# pkispawn \
    -f /usr/share/pki/server/examples/installation/est.cfg \
    -s EST \
    -D est_realm_url=ldap://estds.example.com:389 \
    -v
....


If the CA is in a separate instance or server, the security domain information and CA certificate have to be provided  so the command will become:
[literal]
....
# pkispawn \
    -f /usr/share/pki/server/examples/installation/est.cfg \
    -s EST \
    -D est_realm_url=ldap://estds.example.com:389 \
    -D pki_ca_uri=https://ca.example.com:8443 \
    -D pki_security_domain_hostname=ca.example.com \
    -D pki_cert_chain_path=ca_signing.crt \
    -D pki_cert_chain_nickname=caSigning \
    -v
....

Note that the `est_realm_url` points to the user DB. The other configurations that could be modified according to the deployment are:

[literal]
....
est_ca_profile=estServiceCert
est_ca_user_name=
est_ca_user_password=
est_ca_user_password_file=
est_ca_user_certificate=
est_realm_type=
est_realm_custom=
est_realm_url=
est_realm_auth_type=BasicAuth
est_realm_bind_dn=cn=Directory Manager
est_realm_bind_password=
est_realm_nickname=
est_realm_user=
est_realm_username=
est_realm_password=
est_realm_users_dn=ou=people,dc=est,dc=pki,dc=example,dc=com
est_realm_groups_dn=ou=groups,dc=est,dc=pki,dc=example,dc=com
est_realm_statements=/usr/share/pki/est/conf/realm/postgresql/statements.conf
est_authorizer_exec_path=/usr/share/pki/est/bin/estauthz
....

The `est_ca_*` provides information related to the user and profile configured in the CA for the EST subsystem.

The `est_authorizer_exec_path` is the path to the executable responsible for verifying the authorization. The default script `estauthz` is a simple authorization example that checks only that the user has the role _estclient_.

The `est_realm_*` options allow one to customize the realm. Possible types are: ds, postgresql and in-memory.

As an example, to install EST with PostgreSQL the command is:

[literal]
....
# pkispawn \
    -f /usr/share/pki/server/examples/installation/est.cfg \
    -s EST \
    -D est_realm_url="jdbc:postgresql://postgresql.example.com:5432/est?ssl=true&sslmode=require" \
    -D est_realm_type=postgresql \
    -D est_realm_user=est \
    -D est_realm_password=mysecretpassword \
    -v
....

The `est_realm_custom` is a path to a custom realm configuration for Tomcat and if provided it will overwrite all other realm related configurations.

[id="installation-on-separate-instance-with-certificates"]
=== Installation on separate instance with certificates 

EST can also be installed on a Tomcat instance that is separate from the CA.

In addition to the configuration above, installing EST in a separate instance requires some extra steps to configure the certificates.


[id="installation-on-standalone-instance"]
=== Installation on standalone instance

If the EST subsystem is not required to join the existing security domain, or
no security domain is configured for the CA, it is possible to perform
a 2-step standalone installation.

An example `pkispawn` installation configuration is provided in
`/usr/share/pki/server/examples/installation/est-standalone.cfg` with
the following content:

[literal]
....
[DEFAULT]
pki_server_database_password=Secret.123
pki_admin_setup=False

[EST]
est_realm_type=ds
est_realm_url=ldap://localhost.localdomain:389
est_realm_bind_password=Secret.123
pki_sslserver_nickname=sslserver
pki_subsystem_nickname=subsystem

pki_security_domain_setup=False
pki_standalone=True
....

The installation is done in the first step will create the CSRs for
the certificate needed to the EST instance and it is done with the following command:

[literal]
....
# pkispawn \
    -f /usr/share/pki/server/examples/installation/est-standalone.cfg \
    -s EST \
    -D est_realm_url=ldap://estds.example.com:3389 \
    -D pki_ca_uri=https://ca.example.com:8443 \
    -D pki_cert_chain_nickname=ca_signing \
    -D pki_subsystem_csr_path=subsystem.csr \
    -D pki_sslserver_csr_path=sslserver.csr \
    -D pki_cert_chain_path=ca_signing.crt \
    -D pki_external_step_two=False \
    -v
....

It is possible to use the CSRs to generate the certificate and then go ahead with step 2 command:

[literal]
....
# pkispawn \
    -f /usr/share/pki/server/examples/installation/est-standalone.cfg \
    -s EST \
    -D est_realm_url=ldap://estds.example.com:3389 \
    -D pki_ca_uri=https://ca.example.com:8443 \
    -D pki_cert_chain_nickname=ca_signing \
    -D pki_subsystem_csr_path=subsystem.csr \
    -D pki_subsystem_cert_path=subsystem.crt \ 
    -D pki_sslserver_csr_path=sslserver.csr \
    -D pki_sslserver_cert_path=sslserver.crt \
    -D pki_cert_chain_path=ca_signing.crt \
    -D pki_external_step_two=False \
    -D pki_external_step_two=True \
    -v
....

The subsystem cert has to be associate with an agent user in
the CA. Information on how to crete the user are available in the
prerequisite section in xref:../est/installing-est.adoc[Installing
EST].


== Removing EST 

To remove the EST subsystem, it is possible to use the `pkidestroy` command as follows:

[literal]
....
# pkidestroy -s EST -v
....

Note: the configuration and log folders are not removed. To remove everything add the the options: `--remove-conf` `--remove-logs`.

