:_mod-docs-content-type: PROCEDURE

[id="installing-est-pki-server_{context}"]
= EST installation using `pki-server` 

After the prerequisite in xref:../est/installing-est.adoc[Installing EST], it is
possible to install *EST*.

A PKI Tomcat instance has to be already available, if it is not present then it
is possible to create a new one with `pki-server create` (see  more details
link:https://github.com/dogtagpki/pki/wiki/PKI-Server-Create-CLI[here]).


Create the _EST subsystem_ inside the pki server instance:

----
# pki-server est-create
----

Configure the issuance backend. The class
`org.dogtagpki.est.DogtagRABackend` is used for the EST instance to
communicate with the CA. This requires:

* the _url_ parameter pointing to the CA subsystem;
* credentials of an EST RA account using either of the following methods that authorizes the account to request certificate issuance using the configured enrollment profile:
    ** _username_ and _password_ if the EST RA account;
    ** _TLS client certificate_ that belongs to the EST RA account.
* the enrollment _profile_.


----
# cat >/var/lib/pki/pki-tomcat/conf/est/backend.conf <<EOF
class=org.dogtagpki.est.DogtagRABackend
url=https://$(hostname):8443
profile=estServiceCert
username=est-ra-1
password=password4ESTUser
EOF
----

Note: to use TLS mutual authentication instead of _username/password_, one needs to:

* get issuance for a TLS client certificate from the CA, using the EST
  instance’s crypto token for generating keys and CSR in the instance
  alias directory;
* import the certificate into the EST instance’s crypto token;
* assign the nickname to the parameter _nickname_ (leave out _username_ and _password_);
* in addition, add the certificate to the EST RA user account on the CA.

An example on how to get the certificate and configure EST with TLS
mutual configuration is provided in the `pkispawn` installation guide
xref:../est/installing-est-pkispawn.adoc#installation-on-separate-instance-with-certificates[here].

Configure request authorization. The class
`org.dogtagpki.est.ExternalProcessRequestAuthorizer` allows to
delegate the authorization to an external process configured with the
parameter *executable*:

----
# cat >/var/lib/pki/pki-tomcat/conf/est/authorizer.conf <<EOF
class=org.dogtagpki.est.ExternalProcessRequestAuthorizer
executable=/usr/share/pki/est/bin/estauthz
EOF
----

The executable script in this example performs a simple check of the user role and it
is available xref:/base/est/bin/estauthz[here]. It can be replaced if a
more sophisticated authorization framework has to be adopted.


Deploy the EST application:

----
# pki-server est-deploy
----

Configure the authentication. The authentication allows one to use realms
from _tomcat_ or developed for dogtag. As an example we use an in
memory realm:

----
# cat >/var/lib/pki/pki-tomcat/conf/est/realm.conf <<EOF
class=com.netscape.cms.realm.PKIInMemoryRealm
username=alice
password=4me2Test
roles=estclient
EOF
----

Finally, restart the server:

----
# pki-server restart --wait
----

