:_mod-docs-content-type: PROCEDURE

[id="installing-est-pki-server"]
= EST installation using `pki-server` 

Once the prerequisite in xref:../est/installing-est.adoc[Installing EST] are configured, it is possible to install *EST*.

A PKI Tomcat instance has to be already available, if it is not present then it is possible to create a new one with `pki-server create` (see  more details
link:https://github.com/dogtagpki/pki/wiki/PKI-Server-Create-CLI[here]).

Create the _EST subsystem_ inside the pki server instance:

[literal]
....
# pki-server est-create
....

Configure the issuance backend. The class `org.dogtagpki.est.DogtagRABackend` is used for the EST instance to communicate with the CA. This requires:

* The _url_ parameter pointing to the CA subsystem;

* Credentials of an EST RA account using either of the following methods that authorizes the account to request certificate issuance using the configured enrollment profile:

** _username_ and _password_ if the EST RA account;
** _TLS client certificate_ that belongs to the EST RA account.

* The enrollment _profile_.

[literal]
....
# cat >/var/lib/pki/pki-tomcat/conf/est/backend.conf <<EOF
class=org.dogtagpki.est.DogtagRABackend
url=https://$(hostname):8443
profile=estServiceCert
username=est-ra-1
password=password4ESTUser
EOF
....

Note: To use TLS mutual authentication instead of _username/password_, one needs to:

* Get issuance for a TLS client certificate from the CA, using the EST instance’s crypto token for generating keys and CSR in the instance alias directory;
* Import the certificate into the EST instance’s crypto token;
* Assign the nickname to the parameter _nickname_ (leave out _username_ and _password_);
* Add the certificate to the EST RA user account on the CA.

An example on how to get the certificate and configure EST with TLS mutual configuration is provided in the `pkispawn` installation guide xref:../est/installing-est-pkispawn.adoc#installation-on-separate-instance-with-certificates[here].

Configure request authorization. The class `org.dogtagpki.est.ExternalProcessRequestAuthorizer` allows to delegate the authorization to an external process configured with the
parameter *executable*:

[literal]
....
# cat >/var/lib/pki/pki-tomcat/conf/est/authorizer.conf <<EOF
class=org.dogtagpki.est.ExternalProcessRequestAuthorizer
executable=/usr/share/pki/est/bin/estauthz
EOF
....

The executable script in this example performs a simple check of the user role and it is available at `/usr/share/pki/est/bin/estauthz`. It can be replaced if a
more sophisticated authorization framework has to be adopted.

Deploy the EST application:

[literal]
....
# pki-server est-deploy
....

Configure the authentication. The authentication allows one to use realms from _Tomcat_ or developed for dogtag. As an example we use an in memory realm:

[literal]
....
# cat >/var/lib/pki/pki-tomcat/conf/est/realm.conf <<EOF
class=com.netscape.cms.realm.PKIInMemoryRealm
username=alice
password=4me2Test
roles=estclient
EOF
....

Finally, restart the server:

[literal]
....
# pki-server restart --wait
....

