# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.username = "root"
  config.vm.box = "fedora/RELEASE-cloud-base"
  config.vm.synced_folder "./", "/vagrant", type: "virtualbox"

  config.vm.provider :virtualbox do |domain, override|
    # Defaults for masters and clone
    # WARNING: Do not overcommit CPUs, it causes issues during
    # provisioning, when RPMs are installed
    domain.cpus = 1

    # GH hosted runners provide 8GB. Use conservatively if provisioning a clone VM
    # Note: Assigning 3000 causes the provisioning to fail sometimes
    domain.memory = 2750

  end

  config.vm.define "controller" , primary: true do |controller|
    config.vm.provider :virtualbox do |domain, override|
      # Less resources needed for controller
      domain.memory = 930
    end
    controller.vm.provision "ansible_local" do |ansible|
      # Disable default limit to connect to all the machines
      ansible.limit = "all"
      ansible.install_mode = "pip_args_only"
      ansible.pip_args = "-r /vagrant/tests/dogtag/pytest-ansible/requirements.txt"
      ansible.become = true
      ansible.playbook = "/vagrant/tests/dogtag/pytest-ansible/installation/main.yml"
      ansible.inventory_path = "/vagrant/inventory"
      ansible.verbose = "vv"
      ansible.raw_arguments  = "-M /vagrant/tests/dogtag/pytest-ansible/common-modules/"
    end

    controller.vm.network :private_network, ip: "CONTROLLER_IP"
  end

  config.vm.define "master"  do |master|
    master.vm.network :private_network, ip: "MASTER_IP"
    master.vm.provision "shell", inline: "find /vagrant -name '*.rpm' -and -not -name '*debuginfo*' | xargs sudo dnf -y install"
  end

#  config.vm.define "clone0"  do |clone0|
#  clone0.vm.network :private_network, ip: "CLONE_IP"
#  end
end
