#!/bin/bash
# BEGIN COPYRIGHT BLOCK
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# (C) 2007 Red Hat, Inc.
# All rights reserved.
# END COPYRIGHT BLOCK

# Always switch into the base directory of this
# shell script prior to executing it so that all
# of its output is written to this directory
cd `dirname $0`

# Retrieve the directory name housing this component
PWD=`pwd`

# Set Dogtag component-specific environment variables
DOGTAG_BUILD_SCRIPT=`basename $0`
export DOGTAG_BUILD_SCRIPT
DOGTAG_COMPONENT=`basename ${PWD}`
export DOGTAG_COMPONENT
DOGTAG_SPECFILE="dogtag-pki-kra-ui.spec"
export DOGTAG_SPECFILE

# Set PKI 'ant' environment variables (originally obtained from specfile)
PKI_PRODUCT_UI_FLAVOR_PREFIX="dogtag"
export PKI_PRODUCT_UI_FLAVOR_PREFIX
PKI_PRODUCT_PREFIX="pki"
export PKI_PRODUCT_PREFIX
PKI_PRODUCT="kra-ui"
export PKI_PRODUCT
PKI_VERSION="1.3.1"
export PKI_VERSION

# Set Dogtag helper variables
DOGTAG_COMPONENT_NAME=${PKI_PRODUCT}
export DOGTAG_COMPONENT_NAME
DOGTAG_WGET_URL=http://cvs.fedora.redhat.com/viewvc
export DOGTAG_WGET_URL

# Obtain '${DOGTAG_SPECFILE}' as necessary
if [ "$1" = "refresh" ]; then
	if [ -f "${DOGTAG_SPECFILE}" ]; then
		printf "Removing '${DOGTAG_SPECFILE}' . . . "
		rm -rf ${DOGTAG_SPECFILE}
		printf "done.\n"
	fi
	shift
fi
if [ ! -f "${DOGTAG_SPECFILE}" ]; then
	# Check for Fedora Operating System
	if [ ! -f /etc/fedora-release ]; then
		printf "'${DOGTAG_COMPONENT_NAME}' ONLY builds on Fedora!\n"
		exit 255
	fi
	# Obtain Fedora Operating System Version
	FEDORA_VERSION="F-`cat /etc/fedora-release | awk '{print $3}'`"
	export FEDORA_VERSION
	# Retrieve '${DOGTAG_SPECFILE}' from Koji
	printf "Fetching '${DOGTAG_SPECFILE}' for '${FEDORA_VERSION}' . . .\n"
	wget -O ${DOGTAG_SPECFILE} ${DOGTAG_WGET_URL}/${FEDORA_VERSION}/${DOGTAG_COMPONENT_NAME}/${DOGTAG_SPECFILE}?view=co
	if [ ! -s "${DOGTAG_SPECFILE}" ]; then
		printf "Failed to fetch '${DOGTAG_SPECFILE}' for '${FEDORA_VERSION}'!\n"
		rm -rf ${DOGTAG_SPECFILE}
		exit 255
	fi
fi

# Invoke the shared Dogtag PKI build script
config-ext/build_dogtag_pki $@

