#!/bin/bash
#
# --- BEGIN COPYRIGHT BLOCK ---
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Copyright (C) 2007-2010 Red Hat, Inc.
# All rights reserved.
# --- END COPYRIGHT BLOCK ---
#

PROG_NAME=`basename $0`
SERVICE_NAME="pkicontrol"
SERVICE_PROG="/bin/systemctl"

command="$1"
pki_subsystem_type="$2"
pki_instance="$3"

PKI_PATH="/usr/share/pki/${pki_subsystem_type}"
PKI_REGISTRY="/etc/sysconfig/pki/${pki_subsystem_type}"
PKI_TYPE="pki-${pki_subsystem_type}"
PKI_SYSTEMD_TARGET="pki-${pki_subsystem_type}d"
SYSTEMD=1

# Source the PKI function library
. /usr/share/pki/scripts/functions

# See how we were called.
case $command in
    status)
	registry_status
	exit $?
	;;
    start)
	start
	exit $?
	;;
    restart)
	restart
	exit $?
	;;
    stop)
	stop
	exit $?
	;;
    condrestart|force-restart|try-restart)
        [ ! -f ${lockfile} ] || restart
        exit $?
        ;;
    reload)
        echo "The 'reload' action is an unimplemented feature."
        exit ${default_error}
        ;;
    *)
	echo "unknown action ($command)"
        usage
        echo "where valid instance names include:"
        list_instances
        exit ${default_error}
        ;;
esac

