= Dogtag PKI Documentation Convention

*Work in Progress* : waiting on CS writers to complete the list

Due to style and format requirements of downstream docs, please follow the following convention when editing or adding Asciidoc files.

See installation/ca/installing-ca.adoc for example.

== Convention ==

* File naming convention
** use hyphon ('-') instead of underscore ('_')
** all lower cases
** bears extension .adoc
** no articles (e.g. 'a', 'the')
* Add header including the “id” line at the very beginning of of the file, using the file name. e.g.
** :_mod-docs-content-type: PROCEDURE
** <blank line>
** [id="installing-ca"]
* Do not refer to a section as “page”.  If applies, try using the word "section".
* Do not use “e.g.”.  Use “for example” instead
* Quoted blocks (“....” v.s. “----”)
** Use “....” for commands or other smaller blocks
** Use “----” block brackets for code blocks or content of a file such as pkispawn cfg file samples
** Add the following line above beginning of each block:
*** [literal,subs="+quotes,verbatim"]
* use a pair of backticks around words that are literal such as file names or commands
* do not use future tense (e.g. 'will', "will be", etc.).  Use present tense instead.
* Create PR and request for reviews from members of the dogtag pki team (and doc team if applicable)

