= Server Changes =

== Remove pki_restart_configured_instance ==

The `pki_restart_configured_instance` parameter for `pkispawn` is no longer used so it has been removed.

== Remove pki_<tag>_csr_path and pki_<tag>_cert_path default values ==

The default values of `pki_<tag>_csr_path` and `pki_<tag>_cert_path` parameters have been removed.
The actual paths to the CSRs and certificates need to be specified during installation with external certificates.

== Remove tokendb.hostport ==

The `tokendb.hostport` parameter in TPS's `CS.cfg` is no longer used
so it has been removed.

== Remove pkicreate.<name>, pkiremove.<name>, and os.<name> ==

The `pkicreate.<name>`, `pkiremove.<name>`, and `os.<name>` parameters in `CS.cfg` are no longer used
so they have been removed.

== Remove system and transaction logs ==

The system and transaction logs have been replaced with debug and signed audit logs.
The `log.instance.System.<name>` and `log.instance.Transactions.<name>` parameters in `CS.cfg`
are no longer used so they have been removed.
