name: CA Extra Tests

on: [push, pull_request]

jobs:
  build:
    name: Waiting for build
    uses: ./.github/workflows/wait-for-build.yml
    secrets: inherit

  ca-cert-revocation-test:
    name: CA cert revocation
    needs: build
    uses: ./.github/workflows/ca-cert-revocation-test.yml

  ca-crl-test:
    name: CA CRL database
    needs: build
    uses: ./.github/workflows/ca-crl-test.yml

  ca-publishing-ca-cert-test:
    name: CA with CA cert publishing
    needs: build
    uses: ./.github/workflows/ca-publishing-ca-cert-test.yml

  ca-publishing-user-cert-test:
    name: CA with user cert publishing
    needs: build
    uses: ./.github/workflows/ca-publishing-user-cert-test.yml

  ca-publishing-crl-file-test:
    name: CA with file-based CRL publishing
    needs: build
    uses: ./.github/workflows/ca-publishing-crl-file-test.yml

  ca-publishing-crl-ldap-test:
    name: CA with LDAP-based CRL publishing
    needs: build
    uses: ./.github/workflows/ca-publishing-crl-ldap-test.yml

  ca-notification-request-test:
    name: CA with request notification
    needs: build
    uses: ./.github/workflows/ca-notification-request-test.yml

  ca-hsm-operation-test:
    name: CA with HSM and custom operation key flags
    needs: build
    uses: ./.github/workflows/ca-hsm-operation-test.yml

  ca-nuxwdog-test:
    name: CA with Nuxwdog
    needs: build
    uses: ./.github/workflows/ca-nuxwdog-test.yml

  ca-pruning-test:
    name: CA database pruning
    needs: build
    uses: ./.github/workflows/ca-pruning-test.yml

  ca-rsnv1-test:
    name: CA with RSNv1
    needs: build
    uses: ./.github/workflows/ca-rsnv1-test.yml

  ca-ssnv1-test:
    name: CA with SSNv1
    needs: build
    uses: ./.github/workflows/ca-ssnv1-test.yml

  ca-ssnv2-test:
    name: CA with SSNv2
    needs: build
    uses: ./.github/workflows/ca-ssnv2-test.yml

  scep-test:
    name: SCEP responder
    needs: build
    uses: ./.github/workflows/scep-test.yml
