name: CA with PQC
# This test will perform the following operations:
# - install CA with ML-DSA-65
# - remove CA
# - install CA with ML-DSA-87 and default buffer (for PQC is 65536)
# - remove CA
# - install CA with ML-DSA-87 and buffer size forced to the legacy value (18713)
# - remove CA

on: workflow_call

env:
  DS_IMAGE: ${{ vars.DS_IMAGE || 'quay.io/389ds/dirsrv' }}

jobs:
  # docs/installation/ca/installing-ca-with-pqc.adoc
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SHARED: /tmp/workdir/pki
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Retrieve PKI images
        uses: actions/cache@v4
        with:
          key: pki-images-${{ github.sha }}
          path: pki-images.tar

      - name: Load PKI images
        run: docker load --input pki-images.tar

      - name: Create network
        run: docker network create example

      - name: Set up DS container
        run: |
          tests/bin/ds-create.sh \
              --image=${{ env.DS_IMAGE }} \
              --hostname=ds.example.com \
              --network=example \
              --network-alias=ds.example.com \
              --password=Secret.123 \
              ds

      - name: Set up PKI container
        run: |
          tests/bin/runner-init.sh \
              --hostname=pki.example.com \
              --network=example \
              --network-alias=pki.example.com \
              pki

          # get Fedora version
          FEDORA_VERSION=$(docker exec pki sed -n 's/^VERSION_ID=//p' /etc/os-release)
          echo "FEDORA_VERSION=$FEDORA_VERSION" >> $GITHUB_ENV

      - name: Enable ML-DSA in default crypto-policies
        if: ${{ fromJSON(env.FEDORA_VERSION) < 44 }}
        # ML-DSA algorithms for NSS are enabled as default in rawhide (Fedora 44)
        run: |
          docker exec pki sed -i \
              's/smime-key-exchange:ECDSA/smime-key-exchange:ML-DSA-65:ML-DSA-87:ECDSA/' \
              /etc/crypto-policies/back-ends/nss.config

      - name: Install CA
        run: |
          docker exec pki pkispawn \
              -f /usr/share/pki/server/examples/installation/ca-pqc.cfg \
              -s CA \
              -D pki_ds_url=ldap://ds.example.com:3389 \
              -D pki_enable_access_log=False \
              -v

      - name: Check system cert keys
        run: |
          # all keys should be "mldsa"
          echo Secret.123 > password.txt
          docker exec pki certutil -K -d /var/lib/pki/pki-tomcat/conf/alias -f ${SHARED}/password.txt | tee output
          echo "mldsa" > expected

          grep ca_signing output | sed -n 's/<.*>\s\(\S\+\)\s.*/\1/p' > actual
          diff expected actual

          grep ca_ocsp_signing output | sed -n 's/<.*>\s\(\S\+\)\s.*/\1/p' > actual
          diff expected actual

          grep ca_audit_signing output | sed -n 's/<.*>\s\(\S\+\)\s.*/\1/p' > actual
          diff expected actual

          grep subsystem output | sed -n 's/<.*>\s\(\S\+\)\s.*/\1/p' > actual
          diff expected actual

          grep sslserver output | sed -n 's/<.*>\s\(\S\+\)\s.*/\1/p' > actual
          diff expected actual

      - name: Check CA signing cert
        run: |
          # inspect cert with certutil
          docker exec pki certutil -L -d /var/lib/pki/pki-tomcat/conf/alias -f ${SHARED}/password.txt -n ca_signing | tee output

          # signing algorithm should be "ML-DSA-65"
          echo "ML-DSA-65" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # inspect cert with openssl
          docker exec pki pki-server cert-export ca_signing --cert-file ca_signing.crt
          docker exec pki openssl x509 -text -noout -in ca_signing.crt | tee output

          # signing algorithm should be "ML-DSA-65"
          echo "ML-DSA-65" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # default signing algorithm should be "ML-DSA-65"
          echo "ML-DSA-65" > expected
          docker exec pki pki-server ca-config-show ca.signing.defaultSigningAlgorithm | tee actual
          diff expected actual

      - name: Check CA OCSP signing cert
        run: |
          # inspect cert with certutil
          docker exec pki certutil -L -d /var/lib/pki/pki-tomcat/conf/alias -f ${SHARED}/password.txt -n ca_ocsp_signing | tee output

          # signing algorithm should be "ML-DSA-65"
          echo "ML-DSA-65" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # inspect cert with openssl
          docker exec pki pki-server cert-export ca_ocsp_signing --cert-file ca_ocsp_signing.crt
          docker exec pki openssl x509 -text -noout -in ca_ocsp_signing.crt | tee output

          # signing algorithm should be "ML-DSA-65"
          echo "ML-DSA-65" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # default signing algorithm should be "ML-DSA-65"
          echo "ML-DSA-65" > expected
          docker exec pki pki-server ca-config-show ca.ocsp_signing.defaultSigningAlgorithm | tee actual
          diff expected actual

      - name: Check CA audit signing cert
        run: |
          # inspect cert with certutil
          docker exec pki certutil -L -d /var/lib/pki/pki-tomcat/conf/alias -f ${SHARED}/password.txt -n ca_audit_signing | tee output

          # signing algorithm should be "ML-DSA-65"
          echo "ML-DSA-65" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # inspect cert with openssl
          docker exec pki pki-server cert-export ca_audit_signing --cert-file ca_audit_signing.crt
          docker exec pki openssl x509 -text -noout -in ca_audit_signing.crt | tee output

          # signing algorithm should be "ML-DSA-65"
          echo "ML-DSA-65" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # default signing algorithm should be "ML-DSA-65"
          echo "ML-DSA-65" > expected
          docker exec pki pki-server ca-config-show ca.audit_signing.defaultSigningAlgorithm | tee actual
          diff expected actual

      - name: Check subsystem cert
        run: |
          # inspect cert with certutil
          docker exec pki certutil -L -d /var/lib/pki/pki-tomcat/conf/alias -f ${SHARED}/password.txt -n subsystem | tee output

          # signing algorithm should be "ML-DSA-65"
          echo "ML-DSA-65" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # inspect cert with openssl
          docker exec pki pki-server cert-export subsystem --cert-file subsystem.crt
          docker exec pki openssl x509 -text -noout -in subsystem.crt | tee output

          # signing algorithm should be "ML-DSA-65"
          echo "ML-DSA-65" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # default signing algorithm should not exist
          echo "ERROR: No such parameter: ca.subsystem.defaultSigningAlgorithm" > expected
          docker exec pki pki-server ca-config-show ca.subsystem.defaultSigningAlgorithm \
              > >(tee stdout) 2> >(tee stderr >&2) || true
          diff expected stderr

      - name: Check SSL server cert
        run: |
          # inspect cert with certutil
          docker exec pki certutil -L -d /var/lib/pki/pki-tomcat/conf/alias -f ${SHARED}/password.txt -n sslserver | tee output

          # signing algorithm should be "ML-DSA-65"
          echo "ML-DSA-65" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # inspect cert with openssl
          docker exec pki pki-server cert-export sslserver --cert-file sslserver.crt
          docker exec pki openssl x509 -text -noout -in sslserver.crt | tee output

          # signing algorithm should be "ML-DSA-65"
          echo "ML-DSA-65" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # default signing algorithm should not exist
          echo "ERROR: No such parameter: ca.sslserver.defaultSigningAlgorithm" > expected
          docker exec pki pki-server ca-config-show ca.sslserver.defaultSigningAlgorithm \
              > >(tee stdout) 2> >(tee stderr >&2) || true
          diff expected stderr

      - name: Enable audit signing
        run: |
          docker exec pki pki-server stop --wait
          docker exec pki pki-server ca-audit-config-mod --logSigning True
          docker exec pki pki-server start --wait

      - name: Run PKI healthcheck
        run: docker exec pki pki-healthcheck --failures-only

      - name: Check authenticating as CA admin user
        run: |
          docker exec pki pki-server cert-export \
              --cert-file ca_signing.crt \
              ca_signing

          docker exec pki pki nss-cert-import \
              --cert ca_signing.crt \
              --trust CT,C,C \
              ca_signing

          docker exec pki pki pkcs12-import \
              --pkcs12 /root/.dogtag/pki-tomcat/ca_admin_cert.p12 \
              --password Secret.123

          docker exec pki pki -n caadmin ca-user-show caadmin

      - name: Check CA admin cert
        run: |
          # inspect cert with certutil
          docker exec pki certutil -L -d /root/.dogtag/nssdb -n caadmin | tee output

          # signing algorithm should be "ML-DSA-65"
          echo "ML-DSA-65" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # inspect cert with openssl
          docker exec pki openssl x509 -text -noout -in /root/.dogtag/pki-tomcat/ca_admin.cert | tee output

          # signing algorithm should be "ML-DSA-65"
          echo "ML-DSA-65" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

      - name: Check issuing SSL server cert with RSA key
        run: |
          # issue cert
          docker exec pki /usr/share/pki/tests/ca/bin/sslserver-create.sh

          # inspect cert with certutil
          docker exec pki certutil -L -d /root/.dogtag/nssdb -n sslserver | tee output

          # key type should be "PKCS #1 RSA Encryption"
          echo "PKCS #1 RSA Encryption" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Public Key Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # signing algorithm should be "ML-DSA-65"
          echo "ML-DSA-65" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # inspect cert with openssl
          docker exec pki openssl x509 -text -noout -in sslserver.crt | tee output

          # signing algorithm should be "ML-DSA-65"
          echo "ML-DSA-65" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

      - name: Check issuing SSL server cert with ML-DSA-65 key
        run: |
          docker exec pki certutil -F -d /root/.dogtag/nssdb -n sslserver

          # issue cert
          docker exec pki pki nss-cert-request \
                  --subject "CN=pki.example.com" \
                  --ext /usr/share/pki/server/certs/sslserver.conf \
                  --csr sslserver_mldsa.csr \
                  --key-type MLDSA \
                  --key-strength 65

          docker exec pki  pki -n caadmin ca-cert-issue \
                  --profile caMLDSAServerCert \
                  --csr-file sslserver_mldsa.csr \
                  --output-file sslserver_mldsa.crt

          docker exec pki pki nss-cert-import sslserver --cert sslserver_mldsa.crt

          echo "ML-DSA-65" > expected

          # inspect cert with certutil
          docker exec pki certutil -L -d /root/.dogtag/nssdb -n sslserver | tee output

          # key type should be "ML-DSA-65"
          sed -n -e "s/\s*$//" -e "s/^\s*Public Key Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual
          
          # signing algorithm should be "ML-DSA-65"
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # inspect cert with openssl
          docker exec pki openssl x509 -text -noout -in sslserver_mldsa.crt | tee output

          # signing algorithm should be "ML-DSA-65"
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

      - name: Check audit get signed
        run: |
          docker exec pki cat /var/log/pki/pki-tomcat/ca/signedAudit/ca_audit | grep AuditEvent=AUDIT_LOG_SIGNING | tee output
          grep -q . output

      - name: Enable caMLDSAUserCert profile
        run: |
          docker exec pki pki -n caadmin ca-profile-enable caMLDSAUserCert

      - name: Enroll OCSP test cert
        run: |
          docker exec pki pki nss-cert-request \
              --subject "UID=ocsp-test" \
              --csr ocsp_test.csr \
              --key-type MLDSA \
              --key-strength 65

          docker exec pki pki -n caadmin ca-cert-issue \
              --profile caMLDSAUserCert \
              --csr-file ocsp_test.csr \
              --output-file ocsp_test.crt

          docker exec pki openssl x509 -in ocsp_test.crt -noout -serial | tee output
          CERT_SERIAL="0x$(sed 's/serial=//i' output)"
          echo "$CERT_SERIAL" > ocsp_cert.id
          echo "Issued OCSP test cert with serial: $CERT_SERIAL"

      - name: Check good cert OCSP response signed with ML-DSA
        run: |
          CERT_SERIAL=$(cat ocsp_cert.id)

          docker exec pki openssl ocsp \
              -url http://pki.example.com:8080/ca/ocsp \
              -CAfile ca_signing.crt \
              -issuer ca_signing.crt \
              -serial $CERT_SERIAL \
              -resp_text \
              | tee output

          # cert status should be good
          sed -n "/^$CERT_SERIAL:/p" output > actual
          echo "$CERT_SERIAL: good" > expected
          diff expected actual

          # OCSP response signature algorithm should be ML-DSA-65
          echo "ML-DSA-65" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

      - name: Revoke OCSP test cert
        run: |
          CERT_SERIAL=$(cat ocsp_cert.id)

          docker exec pki pki -n caadmin ca-cert-hold \
              --force \
              $CERT_SERIAL

      - name: Check revoked cert OCSP response signed with ML-DSA
        run: |
          CERT_SERIAL=$(cat ocsp_cert.id)

          docker exec pki openssl ocsp \
              -url http://pki.example.com:8080/ca/ocsp \
              -CAfile ca_signing.crt \
              -issuer ca_signing.crt \
              -serial $CERT_SERIAL \
              -resp_text \
              | tee output

          # cert status should be revoked
          sed -n "/^$CERT_SERIAL:/p" output > actual
          echo "$CERT_SERIAL: revoked" > expected
          diff expected actual

          # OCSP response signature algorithm should be ML-DSA-65
          echo "ML-DSA-65" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

      - name: Generating new sslserver certificate with CMC
        run: |
          # check cert request
          docker exec pki openssl req -text -noout -in /etc/pki/pki-tomcat/certs/sslserver.csr

          # create CMC request
          docker exec pki cp /etc/pki/pki-tomcat/certs/sslserver.csr sslserver.csr
          docker exec pki CMCRequest \
              /usr/share/pki/server/examples/cmc/sslserver-cmc-request.cfg

          # copy the submit and update the profile to use
          docker exec pki \
              cp /usr/share/pki/server/examples/cmc/sslserver-cmc-submit.cfg \
              /tmp/sslserver-cmc-submit.cfg
          docker exec pki sed -i 's/profileId=caCMCserverCert/profileId=caCMCMLDSAserverCert/' /tmp/sslserver-cmc-submit.cfg
          docker exec pki sed -i 's/host=ca.example.com/host=pki.example.com/' /tmp/sslserver-cmc-submit.cfg
          
          # submit CMC request
          docker exec pki HttpClient \
              /tmp/sslserver-cmc-submit.cfg

          # convert CMC response (DER PKCS #7) into PEM PKCS #7 cert chain
          docker exec pki CMCResponse \
              -d /root/.dogtag/nssdb \
              -i sslserver.cmc-response \
              -o $SHARED/sslserver.p7b

          # check issued cert chain
          docker exec pki openssl pkcs7 -print_certs -in $SHARED/sslserver.p7b

      - name: Remove CA and cleanup home
        run: |
          docker exec pki pkidestroy -s CA --remove-logs --remove-conf --force -v
          docker exec pki rm -rf /root/.dogtag

      - name: Create ML-DSA-87 configuration
        # ML-DSA algorithms for NSS are enabled as default in rawhide (Fedora 44)
        run: |
          docker exec pki cp /usr/share/pki/server/examples/installation/ca-pqc.cfg ca-pqc.cfg
          docker exec pki sed -i 's/65$/87/' ca-pqc.cfg

      - name: Install CA with ML-DSA-87 and default buffer (65536 for PQC)
        run: |
          docker exec pki pkispawn \
              -f ca-pqc.cfg \
              -s CA \
              -D pki_ds_url=ldap://ds.example.com:3389 \
              -D pki_enable_access_log=False \
              -v

      - name: Check CA signing cert
        run: |
          # inspect cert with certutil
          docker exec pki certutil -L -d /var/lib/pki/pki-tomcat/conf/alias -f ${SHARED}/password.txt -n ca_signing | tee output

          # signing algorithm should be "ML-DSA-87"
          echo "ML-DSA-87" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # inspect cert with openssl
          docker exec pki pki-server cert-export ca_signing --cert-file ca_signing.crt
          docker exec pki openssl x509 -text -noout -in ca_signing.crt | tee output

          # signing algorithm should be "ML-DSA-87"
          echo "ML-DSA-87" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # default signing algorithm should be "ML-DSA-87"
          echo "ML-DSA-87" > expected
          docker exec pki pki-server ca-config-show ca.signing.defaultSigningAlgorithm | tee actual
          diff expected actual

      - name: Check authenticating as CA admin user
        run: |
          docker exec pki pki-server cert-export \
              --cert-file ca_signing.crt \
              ca_signing

          docker exec pki pki nss-cert-import \
              --cert ca_signing.crt \
              --trust CT,C,C \
              ca_signing

          docker exec pki pki pkcs12-import \
              --pkcs12 /root/.dogtag/pki-tomcat/ca_admin_cert.p12 \
              --password Secret.123

          docker exec pki pki -n caadmin ca-user-show caadmin

      - name: Check CA admin cert
        run: |
          # inspect cert with certutil
          docker exec pki certutil -L -d /root/.dogtag/nssdb -n caadmin | tee output

          # signing algorithm should be "ML-DSA-87"
          echo "ML-DSA-87" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # inspect cert with openssl
          docker exec pki openssl x509 -text -noout -in /root/.dogtag/pki-tomcat/ca_admin.cert | tee output

          # signing algorithm should be "ML-DSA-87"
          echo "ML-DSA-87" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

      - name: Remove CA
        run: |
          docker exec pki pkidestroy -s CA --remove-logs --remove-conf --force -v
          docker exec pki rm -rf /root/.dogtag

      - name: Install CA with ML-DSA-87 with legacy buffer size
        # pkispawn with ML-DSA-87 certificate will fail because the buffer is too small
        run: |
          docker exec pki sed -i \
              's/-Dredhat.crypto-policies=false/-Dredhat.crypto-policies=false -Djdk.tls.maxHandshakeMessageSize=18713/' \
              /usr/share/pki/server/conf/tomcat.conf

          docker exec pki pkispawn \
              -f ca-pqc.cfg \
              -s CA \
              -D pki_ds_url=ldap://ds.example.com:3389 \
              -D pki_enable_access_log=False \
              -v || echo "Failed" | tee output

          echo "Failed" > expected
          tail -n 1 output > actual
          diff expected actual

      - name: Remove CA
        run: |
          docker exec pki pkidestroy -s CA -v

      - name: Check DS server systemd journal
        if: always()
        run: |
          docker exec ds journalctl -x --no-pager -u dirsrv@localhost.service

      - name: Check DS container logs
        if: always()
        run: |
          docker logs ds

      - name: Check PKI server systemd journal
        if: always()
        run: |
          docker exec pki journalctl -x --no-pager -u pki-tomcatd@pki-tomcat.service

      - name: Check CA debug log
        if: always()
        run: |
          docker exec pki find /var/lib/pki/pki-tomcat/logs/ca -name "debug.*" -exec cat {} \;
