name: CA with custom profile
# The test will perform the following:
# - create an auth database
# - connect CA to the auth database
# - create a custom profile
# - enroll a cert with the custom profile

on: workflow_call

env:
  DS_IMAGE: ${{ vars.DS_IMAGE || 'quay.io/389ds/dirsrv' }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SHARED: /tmp/workdir/pki
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install xmlstarlet

      - name: Clone repository
        uses: actions/checkout@v7

      - name: Retrieve PKI images
        uses: actions/cache@v5
        with:
          key: pki-images-${{ github.sha }}
          path: pki-images.tar

      - name: Load PKI images
        run: docker load --input pki-images.tar

      - name: Create network
        run: docker network create example

      - name: Set up DS container
        run: |
          tests/bin/ds-create.sh \
              --image=${{ env.DS_IMAGE }} \
              --hostname=ds.example.com \
              --network=example \
              --network-alias=ds.example.com \
              --password=Secret.123 \
              ds

      - name: Set up authentication database
        run: |
          docker exec -i ds ldapadd \
              -H ldap://ds.example.com:3389 \
              -D "cn=Directory Manager" \
              -w Secret.123 << EOF
          dn: ou=people,dc=example,dc=com
          objectclass: top
          objectclass: organizationalUnit
          ou: People
          aci: (target = "ldap:///ou=people,dc=example,dc=com")
           (targetattr=objectClass||dc||ou||uid||cn||sn||givenName)
           (version 3.0; acl "Allow anyone to read and search basic attributes"; allow (search, read) userdn = "ldap:///anyone";)
          aci: (target = "ldap:///ou=people,dc=example,dc=com")
           (targetattr=*)
           (version 3.0; acl "Allow anyone to read and search itself"; allow (search, read) userdn = "ldap:///self";)

          dn: uid=testuser,ou=people,dc=example,dc=com
          objectClass: person
          objectClass: organizationalPerson
          objectClass: inetOrgPerson
          uid: testuser
          cn: 鄧麗君
          sn: 鄧
          userPassword: Secret.123

      - name: Set up PKI container
        run: |
          tests/bin/runner-init.sh \
              --hostname=pki.example.com \
              --network=example \
              --network-alias=pki.example.com \
              pki

      - name: Install CA
        run: |
          docker exec pki pkispawn \
              -f /usr/share/pki/server/examples/installation/ca.cfg \
              -s CA \
              -D pki_ds_url=ldap://ds.example.com:3389 \
              -v

      - name: Configure UserDirEnrollment
        run: |
          docker exec pki pki-server ca-config-set auths.instance.UserDirEnrollment.pluginName UidPwdDirAuth
          docker exec pki pki-server ca-config-set auths.instance.UserDirEnrollment.ldap.basedn dc=example,dc=com
          docker exec pki pki-server ca-config-set auths.instance.UserDirEnrollment.ldap.ldapauth.authtype BasicAuth
          docker exec pki pki-server ca-config-set auths.instance.UserDirEnrollment.ldap.ldapauth.bindDN "cn=Directory Manager"
          docker exec pki pki-server ca-config-set auths.instance.UserDirEnrollment.ldap.ldapauth.bindPWPrompt internaldb
          docker exec pki pki-server ca-config-set auths.instance.UserDirEnrollment.ldap.ldapconn.host ds.example.com
          docker exec pki pki-server ca-config-set auths.instance.UserDirEnrollment.ldap.ldapconn.port 3389
          docker exec pki pki-server ca-config-set auths.instance.UserDirEnrollment.ldap.ldapconn.secureConn false

      - name: Restart CA subsystem
        run: |
          docker exec pki pki-server ca-redeploy --wait

      - name: Install CA admin cert
        run: |
          docker exec pki pki-server cert-export \
              --cert-file ca_signing.crt \
              ca_signing

          docker exec pki pki nss-cert-import \
              --cert ca_signing.crt \
              --trust CT,C,C \
              ca_signing

          docker exec pki pki pkcs12-import \
              --pkcs12 /root/.dogtag/pki-tomcat/ca_admin_cert.p12 \
              --password Secret.123

      - name: Retrieve caDirUserCert profile
        run: |
          docker exec pki pki \
              -n caadmin \
              ca-profile-show \
              --output $SHARED/CustomProfile.xml \
              caDirUserCert

          cat CustomProfile.xml

      - name: Create custom profile
        run: |
          # allow updates
          sudo chmod go+w CustomProfile.xml

          # update profile ID
          xmlstarlet edit --inplace \
              -u "/Profile/@id" \
              -v "CustomProfile" \
              CustomProfile.xml

          # update profile name
          xmlstarlet edit --inplace \
              -u "/Profile/name" \
              -v "中文 Cert Profile" \
              CustomProfile.xml

          # update profile description
          xmlstarlet edit --inplace \
              -u "/Profile/description" \
              -v "Certificate profile in 中文" \
              CustomProfile.xml

          cat CustomProfile.xml

      - name: Add custom profile
        run: |
          docker exec pki pki \
              -n caadmin \
              ca-profile-add \
              $SHARED/CustomProfile.xml

      - name: Enable custom profile
        run: |
          docker exec pki pki \
              -n caadmin \
              ca-profile-enable \
              CustomProfile

      - name: Check custom profile info
        run: |
          docker exec pki pki \
              -n caadmin \
              ca-profile-show \
              CustomProfile \
              | tee output

          sed -n \
              -e "/^\s*Name:/p" \
              -e "/^\s*Description:/p" \
              output > actual

          cat > expected << EOF
            Name: 中文 Cert Profile
            Description: Certificate profile in 中文
          EOF

          diff expected actual

      - name: Check custom profile config
        run: |
          docker exec pki pki \
              -n caadmin \
              ca-profile-show \
              --raw \
              CustomProfile \
              | tee output

          sed -n \
              -e "/^name=/p" \
              -e "/^desc=/p" \
              output > actual

          cat > expected << EOF
          desc=Certificate profile in 中文
          name=中文 Cert Profile
          EOF

      - name: Check custom profile config file
        run: |
          docker exec pki cat /var/lib/pki/pki-tomcat/ca/profiles/ca/CustomProfile.cfg \
              | tee output

          sed -n \
              -e "/^name=/p" \
              -e "/^desc=/p" \
              output > actual

          cat > expected << EOF
          desc=Certificate profile in 中文
          name=中文 Cert Profile
          EOF

          diff expected actual

      - name: Create cert request
        run: |
          docker exec pki pki nss-cert-request \
              --subject "UID=testuser,OU=people,DC=example,DC=com" \
              --csr testuser.csr

      - name: Issue cert
        run: |
          echo "Secret.123" > password.txt

          docker exec pki pki ca-cert-issue \
              --profile CustomProfile \
              --username testuser \
              --password-file $SHARED/password.txt \
              --csr-file testuser.csr \
              --output-file testuser.crt

          # import cert
          docker exec pki pki nss-cert-import testuser --cert testuser.crt
          docker exec pki pki nss-cert-show testuser | tee output

          # normalize output
          sed \
              -e '/^ *Serial Number:/d' \
              -e '/^ *Not Valid Before:/d' \
              -e '/^ *Not Valid After:/d' \
              output > actual

          cat > expected << EOF
            Nickname: testuser
            Subject DN: UID=testuser,OU=people,DC=example,DC=com
            Issuer DN: CN=CA Signing Certificate,OU=pki-tomcat,O=EXAMPLE
            Trust Flags: u,u,u
          EOF

          diff expected actual

      - name: Disable custom profile
        run: |
          docker exec pki pki \
              -n caadmin \
              ca-profile-disable \
              CustomProfile

      - name: Remove custom profile
        run: |
          docker exec pki pki \
              -n caadmin \
              ca-profile-del \
              CustomProfile

      - name: Remove CA
        run: docker exec pki pkidestroy -s CA -v

      - name: Check DS server systemd journal
        if: always()
        run: |
          docker exec ds journalctl -x --no-pager -u dirsrv@localhost.service

      - name: Check DS container logs
        if: always()
        run: |
          docker logs ds

      - name: Check PKI server systemd journal
        if: always()
        run: |
          docker exec pki journalctl -x --no-pager -u pki-tomcatd@pki-tomcat.service

      - name: Check PKI server access log
        if: always()
        run: |
          docker exec pki find /var/log/pki/pki-tomcat -name "localhost_access_log.*" -exec cat {} \;

      - name: Check CA debug log
        if: always()
        run: |
          docker exec pki find /var/lib/pki/pki-tomcat/logs/ca -name "debug.*" -exec cat {} \;
