name: CA with secure DS (PQC)

on: workflow_call

env:
  DS_IMAGE: ${{ vars.DS_IMAGE || 'quay.io/389ds/dirsrv' }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SHARED: /tmp/workdir/pki
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Retrieve PKI images
        uses: actions/cache@v4
        with:
          key: pki-images-${{ github.sha }}
          path: pki-images.tar

      - name: Load PKI images
        run: docker load --input pki-images.tar

      - name: Create network
        run: docker network create example

      - name: Set up DS container
        run: |
          tests/bin/ds-create.sh \
              --image=pki-runner \
              --hostname=ds.example.com \
              --network=example \
              --network-alias=ds.example.com \
              --password=Secret.123 \
              ds

      - name: Set up PKI container
        run: |
          tests/bin/runner-init.sh \
              --hostname=pki.example.com \
              --network=example \
              --network-alias=pki.example.com \
              pki

          # get Fedora version
          FEDORA_VERSION=$(docker exec pki sed -n 's/^VERSION_ID=//p' /etc/os-release)
          echo "FEDORA_VERSION=$FEDORA_VERSION" >> $GITHUB_ENV

      - name: Enable ML-DSA in default crypto-policies
        if: ${{ fromJSON(env.FEDORA_VERSION) < 44 }}
        run: |
          docker exec pki sed -i \
              's/smime-key-exchange:ECDSA/smime-key-exchange:ML-DSA-65:ECDSA/' \
              /etc/crypto-policies/back-ends/nss.config

      - name: Create DS signing cert
        run: |
          docker exec pki pki \
              nss-cert-request \
              --key-type MLDSA \
              --key-strength 65 \
              --subject "CN=DS Signing Certificate" \
              --ext /usr/share/pki/server/certs/ca_signing.conf \
              --csr ds_signing.csr
          docker exec pki pki \
              nss-cert-issue \
              --csr ds_signing.csr \
              --ext /usr/share/pki/server/certs/ca_signing.conf \
              --cert ds_signing.crt

          docker exec pki pki nss-cert-import \
              --cert ds_signing.crt \
              --trust CT,C,C \
              Self-Signed-CA

          docker exec pki certutil -L -d /root/.dogtag/nssdb

      - name: Create DS server cert
        run: |
          docker exec pki pki \
              nss-cert-request \
              --key-type MLDSA \
              --key-strength 65 \
              --subject "CN=ds.example.com" \
              --ext /usr/share/pki/server/certs/sslserver.conf \
              --csr ds_server.csr
          docker exec pki pki \
              nss-cert-issue \
              --issuer Self-Signed-CA \
              --csr ds_server.csr \
              --ext /usr/share/pki/server/certs/sslserver.conf \
              --cert ds_server.crt

          docker exec pki pki nss-cert-import \
              --cert ds_server.crt \
              Server-Cert

          docker exec pki certutil -L -d /root/.dogtag/nssdb

      - name: Import certs into DS container
        run: |
          docker exec pki pk12util \
              -d /root/.dogtag/nssdb \
              -o $SHARED/ds_server.p12 \
              -W Secret.123 \
              -n Server-Cert

          sudo chmod go+r ds_server.p12

          tests/bin/ds-certs-import.sh \
              --image=pki-runner \
              --input=ds_server.p12 \
              --password=Secret.123 \
              --debug \
              ds

          tests/bin/ds-stop.sh \
              --image=pki-runner \
              ds

          tests/bin/ds-start.sh \
              --image=pki-runner \
              ds

      - name: Install CA
        run: |
          docker exec pki pkispawn \
              -f /usr/share/pki/server/examples/installation/ca-secure-ds-pqc.cfg \
              -s CA \
              -D pki_ds_url=ldaps://ds.example.com:3636 \
              -D pki_enable_access_log=False \
              -v

          docker exec pki pki-server cert-find

      - name: Run PKI healthcheck
        run: docker exec pki pki-healthcheck --failures-only

      - name: Verify DS connection
        run: |
          docker exec pki pki-server ca-db-config-show > output
          cat output
          echo "ds.example.com" > expected
          sed -n 's/^\s\+Hostname:\s\+\(\S\+\)$/\1/p' output > actual
          diff expected actual
          echo "3636" > expected
          sed -n 's/^\s\+Port:\s\+\(\S\+\)$/\1/p' output > actual
          diff expected actual
          echo "true" > expected
          sed -n 's/^\s\+Secure:\s\+\(\S\+\)$/\1/p' output > actual
          diff expected actual

      - name: Check DS signing cert
        run: |
          docker exec pki certutil -L -d /root/.dogtag/nssdb -n Self-Signed-CA | tee output

          echo "ML-DSA-65" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          docker exec pki openssl x509 -text -noout -in ds_signing.crt | tee output

          echo "ML-DSA-65" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

      - name: Check DS server cert
        run: |
          docker exec pki certutil -L -d /root/.dogtag/nssdb -n Server-Cert | tee output

          echo "ML-DSA-65" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          docker exec pki openssl x509 -text -noout -in ds_server.crt | tee output

          echo "ML-DSA-65" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

      - name: Remove CA
        run: docker exec pki pkidestroy -s CA -v

      - name: Check DS server systemd journal
        if: always()
        run: |
          docker exec ds journalctl -x --no-pager -u dirsrv@localhost.service

      - name: Check DS container logs
        if: always()
        run: |
          docker logs ds

      - name: Check PKI server systemd journal
        if: always()
        run: |
          docker exec pki journalctl -x --no-pager -u pki-tomcatd@pki-tomcat.service

      - name: Check CA debug log
        if: always()
        run: |
          docker exec pki find /var/lib/pki/pki-tomcat/logs/ca -name "debug.*" -exec cat {} \;
