name: IPA KRA
# This test will perform the following operations:
# - install IPA server with CA
# - install KRA
# - run test_vault_plugin.py
# - create vault
# - generate private key
# - archive private key
# - retrieve private key

on: workflow_call

env:
  DS_IMAGE: ${{ vars.DS_IMAGE || 'quay.io/389ds/dirsrv' }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SHARED: /tmp/workdir/pki
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Retrieve IPA images
        uses: actions/cache@v4
        with:
          key: ipa-images-${{ github.sha }}
          path: ipa-images.tar

      - name: Load IPA images
        run: docker load --input ipa-images.tar

      - name: Create network
        run: docker network create example

      - name: Run IPA container
        run: |
          tests/bin/runner-init.sh \
              --image=ipa-runner \
              --hostname=ipa.example.com \
              --network=example \
              --network-alias=ipa.example.com \
              --network-alias=ipa-ca.example.com \
              ipa

      - name: Install IPA server
        run: |
          docker exec ipa sysctl net.ipv6.conf.lo.disable_ipv6=0
          docker exec ipa ipa-server-install \
              -U \
              --domain example.com \
              -r EXAMPLE.COM \
              -p Secret.123 \
              -a Secret.123 \
              --no-host-dns \
              --no-ntp

          docker exec ipa pki-server cert-export ca_signing --cert-file ca_signing.crt

      - name: Update PKI server configuration
        run: |
          docker exec ipa dnf install -y xmlstarlet

          # disable access log buffer
          docker exec ipa xmlstarlet edit --inplace \
              -u "//Valve[@className='org.apache.catalina.valves.AccessLogValve']/@buffered" \
              -v "false" \
              -i "//Valve[@className='org.apache.catalina.valves.AccessLogValve' and not(@buffered)]" \
              -t attr \
              -n "buffered" \
              -v "false" \
              /etc/pki/pki-tomcat/server.xml

          # restart PKI server
          docker exec ipa pki-server restart --wait

      - name: Check DS server
        run: |
          # check DS instances
          docker exec ipa dsctl --list

          # check DS backends
          docker exec ipa dsconf slapd-EXAMPLE-COM backend suffix list

          # check root DSE
          docker exec ipa ldapsearch \
              -H ldap://ipa.example.com:389 \
              -D "cn=Directory Manager" \
              -w Secret.123 \
              -x \
              -b "" \
              -s base \
              -o ldif_wrap=no \
              -LLL

          # check CA base DN
          docker exec ipa ldapsearch \
              -H ldap://ipa.example.com:389 \
              -D "cn=Directory Manager" \
              -w Secret.123 \
              -x \
              -b "o=ipaca" \
              -s base \
              -o ldif_wrap=no \
              -LLL

      - name: Check IPA admin user
        run: |
          echo Secret.123 | docker exec -i ipa kinit admin
          docker exec ipa ipa ping

      - name: Install CA admin cert
        run: |
          docker exec ipa ls -la /root/.dogtag/pki-tomcat
          docker exec ipa cat /root/.dogtag/pki-tomcat/ca_admin.cert
          docker exec ipa openssl x509 -text -noout -in /root/.dogtag/pki-tomcat/ca_admin.cert

          # import CA admin cert and key into the client's NSS database
          docker exec ipa pki nss-cert-import \
              --cert ca_signing.crt \
              --trust CT,C,C \
              ca_signing

          docker exec ipa pki pkcs12-import \
              --pkcs12 /root/ca-agent.p12 \
              --pkcs12-password Secret.123

      - name: Install RA agent cert
        run: |
          # import RA agent cert and key into a PKCS #12 file
          # then import it into the client's NSS database
          docker exec ipa openssl pkcs12 -export \
              -in /var/lib/ipa/ra-agent.pem \
              -inkey /var/lib/ipa/ra-agent.key \
              -out ra-agent.p12 \
              -passout pass:Secret.123 \
              -name ipa-ra-agent

          docker exec ipa pki pkcs12-import \
              --pkcs12 ra-agent.p12 \
              --pkcs12-password Secret.123

      - name: Install KRA
        run: |
          docker exec ipa ipa-kra-install -p Secret.123
          docker exec ipa pki-server ca-connector-find

      - name: Check PKI certs and keys
        run: |
          # check certs
          docker exec ipa pki-server cert-find

          # check keys
          docker exec ipa certutil -K \
              -d /var/lib/pki/pki-tomcat/conf/alias \
              -f /var/lib/pki/pki-tomcat/conf/alias/pwdfile.txt | tee output

          # there should be no orphaned keys
          echo "0" > expected
          grep "(orphan)" output | wc -l > actual
          diff expected actual

      - name: Check DS server after installing KRA
        run: |
          # check DS backends
          docker exec ipa dsconf slapd-EXAMPLE-COM backend suffix list

          # check root DSE
          docker exec ipa ldapsearch \
              -H ldap://ipa.example.com:389 \
              -D "cn=Directory Manager" \
              -w Secret.123 \
              -x \
              -b "" \
              -s base \
              -o ldif_wrap=no \
              -LLL

          # check KRA base DN
          docker exec ipa ldapsearch \
              -H ldap://ipa.example.com:389 \
              -D "cn=Directory Manager" \
              -w Secret.123 \
              -x \
              -b "o=kra,o=ipaca" \
              -s base \
              -o ldif_wrap=no \
              -LLL

      - name: Check CA admin cert after installing KRA
        run: |
          docker exec ipa ls -la /root/.dogtag/pki-tomcat
          docker exec ipa cat /root/.dogtag/pki-tomcat/ca_admin.cert
          docker exec ipa openssl x509 -text -noout -in /root/.dogtag/pki-tomcat/ca_admin.cert

      - name: Check KRA users
        run: |
          docker exec ipa pki-server kra-user-find

          # check KRA admin user
          docker exec ipa pki-server kra-user-show admin
          docker exec ipa pki-server kra-user-cert-find admin
          docker exec ipa pki-server kra-user-role-find admin

          # check KRA subsystem user
          docker exec ipa pki-server kra-user-show CA-ipa.example.com-443
          docker exec ipa pki-server kra-user-cert-find CA-ipa.example.com-443
          docker exec ipa pki-server kra-user-role-find CA-ipa.example.com-443

          # check IPA KRA user
          docker exec ipa pki-server kra-user-show ipakra
          docker exec ipa pki-server kra-user-cert-find ipakra
          docker exec ipa pki-server kra-user-role-find ipakra

      - name: Check RA agent cert
        run: |
          # RA agent should be able to access key requests
          docker exec ipa pki -n ipa-ra-agent kra-key-request-find

      - name: Check webapps
        run: |
          docker exec ipa pki-server webapp-find | tee output

          # IPA server should now have ROOT, acme, ca, kra, and pki webapps
          echo "ROOT" > expected
          echo "acme" >> expected
          echo "ca" >> expected
          echo "kra" >> expected
          echo "pki" >> expected
          sed -n 's/^ *Webapp ID: *\(.*\)$/\1/p' output > actual
          diff expected actual

          docker exec ipa pki-server webapp-show kra

      - name: Check subsystems
        run: |
          docker exec ipa pki-server subsystem-find | tee output

          # IPA server should now have CA, KRA, and ACME subsystems
          echo "ca" > expected
          echo "kra" >> expected
          echo "acme" >> expected
          sed -n 's/^ *Subsystem ID: *\(.*\)$/\1/p' output > actual
          diff expected actual

          # all subsystems should be enabled
          echo "True" > expected
          echo "True" >> expected
          echo "True" >> expected
          sed -n 's/^ *Enabled: *\(.*\)$/\1/p' output > actual
          diff expected actual

      - name: Run PKI healthcheck
        run: docker exec ipa pki-healthcheck --failures-only

      - name: Configure test environment
        run: |
          docker exec ipa bash -c "cp -r /etc/ipa/* ~/.ipa"
          docker exec ipa bash -c "echo Secret.123 > ~/.ipa/.dmpw"
          docker exec ipa bash -c "echo 'wait_for_dns=5' >> ~/.ipa/default.conf"

      - name: Run test_vault_plugin.py
        run: |
          docker exec ipa ipa-run-tests -x --verbose \
              test_xmlrpc/test_vault_plugin.py

      - name: Create vault
        run: |
          docker exec ipa ipa vault-add \
              --type symmetric \
              --password Secret.123 \
              testvault

          docker exec ipa pki \
              -n ipa-ra-agent \
              kra-key-find \
              --clientKeyID ipa:/users/admin/testvault | tee output

          # there should be 1 active key record initially
          echo "active" > expected
          sed -n 's/^\s*Status:\s*\(.*\)$/\1/p' output > actual
          diff expected actual

          HEX_KEY_ID=$(sed -n "s/^\s*Key ID:\s*\(\S*\)$/\1/p" output)
          echo "Key ID: $HEX_KEY_ID"

          DEC_KEY_ID=$(python -c "print(int('$HEX_KEY_ID', 16))")
          echo "Dec Key ID: $DEC_KEY_ID"

          # check key record
          docker exec ipa ldapsearch \
              -H ldap://ipa.example.com:389 \
              -x \
              -D "cn=Directory Manager" \
              -w Secret.123 \
              -b "cn=$DEC_KEY_ID,ou=keyRepository,ou=kra,o=kra,o=ipaca" \
              -o ldif_wrap=no \
              -LLL | tee output

          # normalize output
          sed \
              -e '/^$/d' \
              -e 's/^\(serialno\): .*$/\1: XXXXX/' \
              -e 's/^\(privateKeyData\):: .*$/\1:: XXXXX/' \
              -e 's/^\(metaInfo: payloadEncryptionIV\):.*/\1:XXXXX/' \
              -e 's/^\(dateOfCreate\): .*$/\1: XXXXX/' \
              -e 's/^\(dateOfModify\): .*$/\1: XXXXX/' \
              output > actual

          cat > expected << EOF
          dn: cn=$DEC_KEY_ID,ou=keyRepository,ou=kra,o=kra,o=ipaca
          objectClass: top
          objectClass: keyRecord
          keyState: VALID
          serialno: XXXXX
          ownerName: ipakra
          privateKeyData:: XXXXX
          metaInfo: sessionKeyWrapAlgorithm:RSA
          metaInfo: payloadEncrypted:true
          metaInfo: sessionKeyKeyGenAlgorithm:AES
          metaInfo: sessionKeyType:AES
          metaInfo: sessionKeyLength:128
          metaInfo: payloadEncryptionOID:2.16.840.1.101.3.4.1.2
          metaInfo: payloadEncryptionIV:XXXXX
          metaInfo: payloadWrapAlgorithm:AES KeyWrap/Padding
          dateOfCreate: XXXXX
          dateOfModify: XXXXX
          archivedBy: ipakra
          clientId: ipa:/users/admin/testvault
          status: active
          dataType: passPhrase
          cn: $DEC_KEY_ID
          EOF

          diff expected actual

      - name: Retrieve initial vault content
        run: |
          docker exec ipa ipa vault-retrieve \
              --password Secret.123 \
              --out $SHARED/output \
              testvault

          # the vault should be empty initially
          diff /dev/null output

      - name: Generate private key
        run: |
          docker exec ipa openssl genrsa -out $SHARED/private.key 2048
          docker exec ipa chmod go+r $SHARED/private.key
          cat private.key

      - name: Archive private key
        run: |
          docker exec ipa ipa vault-archive \
              --password Secret.123 \
              --in $SHARED/private.key \
              testvault

          docker exec ipa pki \
              -n ipa-ra-agent \
              kra-key-find \
              --clientKeyID ipa:/users/admin/testvault | tee output

          # the initial key record should be inactive and the new one should be active
          echo "inactive" > expected
          echo "active" >> expected
          sed -n 's/^\s*Status:\s*\(.*\)$/\1/p' output > actual
          diff expected actual

          # get the latest key ID
          HEX_KEY_ID=$(sed -n "s/^\s*Key ID:\s*\(\S*\)$/\1/p" output | tail -1)
          echo "Key ID: $HEX_KEY_ID"

          DEC_KEY_ID=$(python -c "print(int('$HEX_KEY_ID', 16))")
          echo "$DEC_KEY_ID" > key.id
          echo "Dec Key ID: $DEC_KEY_ID"

          # check key record
          docker exec ipa ldapsearch \
              -H ldap://ipa.example.com:389 \
              -x \
              -D "cn=Directory Manager" \
              -w Secret.123 \
              -b "cn=$DEC_KEY_ID,ou=keyRepository,ou=kra,o=kra,o=ipaca" \
              -o ldif_wrap=no \
              -LLL | tee output

          # normalize output
          sed \
              -e '/^$/d' \
              -e 's/^\(serialno\): .*$/\1: XXXXX/' \
              -e 's/^\(privateKeyData\):: .*$/\1:: XXXXX/' \
              -e 's/^\(metaInfo: payloadEncryptionIV\):.*/\1:XXXXX/' \
              -e 's/^\(dateOfCreate\): .*$/\1: XXXXX/' \
              -e 's/^\(dateOfModify\): .*$/\1: XXXXX/' \
              output > actual

          cat > expected << EOF
          dn: cn=$DEC_KEY_ID,ou=keyRepository,ou=kra,o=kra,o=ipaca
          objectClass: top
          objectClass: keyRecord
          keyState: VALID
          serialno: XXXXX
          ownerName: ipakra
          privateKeyData:: XXXXX
          metaInfo: sessionKeyWrapAlgorithm:RSA
          metaInfo: payloadEncrypted:true
          metaInfo: sessionKeyKeyGenAlgorithm:AES
          metaInfo: sessionKeyType:AES
          metaInfo: sessionKeyLength:128
          metaInfo: payloadEncryptionOID:2.16.840.1.101.3.4.1.2
          metaInfo: payloadEncryptionIV:XXXXX
          metaInfo: payloadWrapAlgorithm:AES KeyWrap/Padding
          dateOfCreate: XXXXX
          dateOfModify: XXXXX
          archivedBy: ipakra
          clientId: ipa:/users/admin/testvault
          status: active
          dataType: passPhrase
          cn: $DEC_KEY_ID
          EOF

          diff expected actual

      - name: Retrieve private key
        run: |
          docker exec ipa ipa vault-retrieve \
              --password Secret.123 \
              --out $SHARED/output \
              testvault

          # the retrieved key should be identical to the original
          diff private.key output

      - name: Check IPA CA install log
        if: always()
        run: |
          docker exec ipa cat /var/log/ipaserver-install.log

      - name: Check IPA KRA install log
        if: always()
        run: |
          docker exec ipa cat /var/log/ipaserver-kra-install.log

      - name: Check HTTPD access logs
        if: always()
        run: |
          docker exec ipa cat /var/log/httpd/access_log

      - name: Check HTTPD error logs
        if: always()
        run: |
          docker exec ipa cat /var/log/httpd/error_log

      - name: Check DS server systemd journal
        if: always()
        run: |
          docker exec ipa journalctl -x --no-pager -u dirsrv@EXAMPLE-COM.service

      - name: Check DS access logs
        if: always()
        run: |
          docker exec ipa cat /var/log/dirsrv/slapd-EXAMPLE-COM/access

      - name: Check DS error logs
        if: always()
        run: |
          docker exec ipa cat /var/log/dirsrv/slapd-EXAMPLE-COM/errors

      - name: Check DS security logs
        if: always()
        run: |
          docker exec ipa cat /var/log/dirsrv/slapd-EXAMPLE-COM/security

      - name: Check CA pkispawn log
        if: always()
        run: |
          docker exec ipa find /var/log/pki -name "pki-ca-spawn.*" -exec cat {} \;

      - name: Check KRA pkispawn log
        if: always()
        run: |
          docker exec ipa find /var/log/pki -name "pki-kra-spawn.*" -exec cat {} \;

      - name: Check PKI server systemd journal
        if: always()
        run: |
          docker exec ipa journalctl -x --no-pager -u pki-tomcatd@pki-tomcat.service

      - name: Check PKI server access log
        if: always()
        run: |
          docker exec ipa find /var/log/pki/pki-tomcat -name "localhost_access_log.*" -exec cat {} \;

      - name: Check CA debug log
        if: always()
        run: |
          docker exec ipa find /var/lib/pki/pki-tomcat/logs/ca -name "debug.*" -exec cat {} \;

      - name: Check KRA debug log
        if: always()
        run: |
          docker exec ipa find /var/lib/pki/pki-tomcat/logs/kra -name "debug.*" -exec cat {} \;

      - name: Remove IPA server
        run: docker exec ipa ipa-server-install --uninstall -U

      - name: Check CA pkidestroy log
        if: always()
        run: |
          docker exec ipa find /var/log/pki -name "pki-ca-destroy.*" -exec cat {} \;

      - name: Check KRA pkidestroy log
        if: always()
        run: |
          docker exec ipa find /var/log/pki -name "pki-kra-destroy.*" -exec cat {} \;
