name: KRA with SSKG
# https://github.com/dogtagpki/pki/wiki/Server-Side-Key-Generation-for-EE

# This test will perform the following operations:
# - install CA
# - install KRA
# - use default password policy in caServerKeygen_UserCert
# - submit request with good password
# - submit request with short password
# - submit request with numeric password
# - disable password policy in caServerKeygen_UserCert
# - submit request with minimal password

# TODO: verify that the key is generated in KRA

on: workflow_call

env:
  DS_IMAGE: ${{ vars.DS_IMAGE || 'quay.io/389ds/dirsrv' }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SHARED: /tmp/workdir/pki
    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Retrieve PKI images
        uses: actions/cache@v5
        with:
          key: pki-images-${{ github.sha }}
          path: pki-images.tar

      - name: Load PKI images
        run: docker load --input pki-images.tar

      - name: Create network
        run: docker network create example

      - name: Set up DS container
        run: |
          tests/bin/ds-create.sh \
              --image=${{ env.DS_IMAGE }} \
              --hostname=ds.example.com \
              --network=example \
              --network-alias=ds.example.com \
              --password=Secret.123 \
              ds

      - name: Set up PKI container
        run: |
          tests/bin/runner-init.sh \
              --hostname=pki.example.com \
              --network=example \
              --network-alias=pki.example.com \
              pki

      - name: Install CA
        run: |
          docker exec pki pkispawn \
              -f /usr/share/pki/server/examples/installation/ca.cfg \
              -s CA \
              -D pki_ds_url=ldap://ds.example.com:3389 \
              -D pki_admin_nickname=admin \
              -v

      - name: Install KRA
        run: |
          docker exec pki pkispawn \
              -f /usr/share/pki/server/examples/installation/kra.cfg \
              -s KRA \
              -D pki_ds_url=ldap://ds.example.com:3389 \
              -D pki_admin_nickname=admin \
              -v

      - name: Check KRA connector in CA
        run: |
          docker exec pki pki-server cert-export \
              --cert-file $SHARED/kra_transport.crt \
              kra_transport

          TRANSPORT_CERT=$(openssl x509 \
              -in kra_transport.crt \
              -outform der \
              | base64 --wrap=0)

          docker exec pki pki-server ca-config-find | grep ^ca\.connector.KRA\. | tee output

          # by default KRA connector should contain transport cert data
          cat > expected << EOF
          ca.connector.KRA.enable=true
          ca.connector.KRA.host=pki.example.com
          ca.connector.KRA.local=false
          ca.connector.KRA.nickName=subsystem
          ca.connector.KRA.port=8443
          ca.connector.KRA.timeout=30
          ca.connector.KRA.transportCert=$TRANSPORT_CERT
          ca.connector.KRA.uri=/kra/agent/kra/connector
          EOF

          diff expected output

      - name: Update KRA connector in CA
        run: |
          # drop transport cert data from KRA connector
          docker exec pki pki-server ca-config-unset ca.connector.KRA.transportCert

          # check transport cert in NSS database
          docker exec pki pki-server cert-show kra_transport

          # set transport cert nickname in KRA connector
          docker exec pki pki-server ca-config-set ca.connector.KRA.transportCertNickname kra_transport

          docker exec pki pki-server ca-config-find | grep ^ca\.connector.KRA\. | tee output

          # KRA connector should contain transport cert nickname
          cat > expected << EOF
          ca.connector.KRA.enable=true
          ca.connector.KRA.host=pki.example.com
          ca.connector.KRA.local=false
          ca.connector.KRA.nickName=subsystem
          ca.connector.KRA.port=8443
          ca.connector.KRA.timeout=30
          ca.connector.KRA.transportCertNickname=kra_transport
          ca.connector.KRA.uri=/kra/agent/kra/connector
          EOF

          diff expected output

          docker exec pki pki-server ca-redeploy --wait

      - name: Install admin cert
        run: |
          docker exec pki pki-server cert-export \
              --cert-file $SHARED/ca_signing.crt \
              ca_signing

          docker exec pki pki nss-cert-import \
              --cert $SHARED/ca_signing.crt \
              --trust CT,C,C \
              ca_signing

          docker exec pki pki nss-cert-import \
              --cert $SHARED/kra_transport.crt \
              kra_transport

          docker exec pki pki pkcs12-import \
              --pkcs12 /root/.dogtag/pki-tomcat/ca_admin_cert.p12 \
              --password Secret.123

          docker exec pki pki nss-cert-find

          docker exec pki pki -n admin ca-user-show caadmin

          docker exec pki pki -n admin kra-user-show kraadmin

      - name: Create request template for caServerKeygen_UserCert
        run: |
          # get request template
          docker exec pki curl \
              -s \
              -o - \
              --cacert $SHARED/ca_signing.crt \
              https://pki.example.com:8443/ca/v2/certrequests/profiles/caServerKeygen_UserCert \
              | tee caServerKeygen_UserCert.json

          # configure request to create 2048-bit RSA key
          cat caServerKeygen_UserCert.json \
              | jq '.Input[0].Attribute[1].Value|="RSA" | .Input[0].Attribute[2].Value|="2048"' \
              | tee template.json

      - name: Submit request with good password
        run: |
          # create request with good password for user test1
          #
          # by default the password must be at least 20 characters,
          # contain at least 2 upper case letters, and contain at
          # least 1 special character.
          cat template.json \
              | jq '.Input[0].Attribute[0].Value|="k342r09cmIJmklOLIJ,lwerkln234lik-[df"' \
              | jq '.Input[1].Attribute[0].Value|="test1"' \
              | tee request.json

          # submit request
          docker exec pki curl \
              -s \
              -o - \
              --cacert $SHARED/ca_signing.crt \
              --json @$SHARED/request.json \
              https://pki.example.com:8443/ca/v2/certrequests \
              | tee response.json

          # request should be pending
          jq -r '.entries[0].requestStatus' response.json > actual

          cat > expected << EOF
          pending
          EOF

          diff expected actual

          # approve request
          REQUEST_ID=$(jq -r '.entries[0].requestID' response.json)
          docker exec pki pki \
              -n admin \
              ca-cert-request-approve \
              --force \
              $REQUEST_ID \
              | tee output

          # export cert
          CERT_ID=$(sed -n 's/^\s*Certificate ID:\s*\(\S*\)$/\1/p' output)
          docker exec pki pki ca-cert-export \
              --output-file $SHARED/test1.crt \
              $CERT_ID
          echo "Cert ID: $CERT_ID"
          echo $CERT_ID > test1.cert_id

      - name: Find generated key
        run: |
          # find generated key by owner
          docker exec pki pki \
              -n admin \
              kra-key-find \
              --owner UID=test1 \
              | tee output

          KEY_ID=$(sed -n 's/^\s*Key ID:\s*\(\S*\)$/\1/p' output)
          echo "Key ID: $KEY_ID"
          echo $KEY_ID > test1.key_id

      - name: Retrieve generated key
        run: |
          KEY_ID=$(cat test1.key_id)
          echo "Key ID: $KEY_ID"

          # export cert into Base64-encoded format
          BASE64_CERT=$(openssl x509 -in test1.crt -outform DER | base64 --wrap=0)
          echo "Cert: $BASE64_CERT"

          # create retrieval request with key ID, cert, and passphrase
          cat > request.json <<EOF
          {
            "ClassName" : "com.netscape.certsrv.key.KeyRecoveryRequest",
            "Attributes" : {
              "Attribute" : [ {
                "name" : "keyId",
                "value" : "$KEY_ID"
              }, {
                "name" : "certificate",
                "value" : "$BASE64_CERT"
              }, {
                "name" : "passphrase",
                "value" : "Secret.123"
              } ]
            }
          }
          EOF

          # retrieve cert and key into PKCS #12 file
          docker exec pki pki \
              -n admin \
              kra-key-retrieve \
              --input $SHARED/request.json \
              --transport kra_transport \
              --output-data test1.p12

          docker exec pki pki pkcs12-cert-find \
              --pkcs12 test1.p12 \
              --password Secret.123

          docker exec pki pki pkcs12-key-find \
              --pkcs12 test1.p12 \
              --password Secret.123

      - name: Import retrieved key
        run: |
          # import PKCS #12 file into NSS database with the passphrase
          docker exec pki pki \
              -d nssdb \
              pkcs12-import \
              --pkcs12 test1.p12 \
              --password Secret.123

          # remove retrieved cert from NSS database
          docker exec pki pki \
              -d nssdb \
              nss-cert-del \
              UID=test1

          # import original cert into NSS database
          docker exec pki pki \
              -d nssdb \
              nss-cert-import \
              --cert $SHARED/test1.crt \
              test1

          # the original cert should match the retrieved key (trust flags must be u,u,u)
          docker exec pki pki \
              -d nssdb \
              nss-cert-show \
              test1 \
              | tee output

          cat > expected << EOF
          u,u,u
          EOF

          sed -n 's/^\s*Trust Flags:\s*\(\S\+\)$/\1/p' output > actual

          diff expected actual

      - name: Submit request with short password
        run: |
          # create request with short password for user test2
          cat template.json \
              | jq '.Input[0].Attribute[0].Value|="k342r0"' \
              | jq '.Input[1].Attribute[0].Value|="test2"' \
              | tee request.json

          # submit request
          docker exec pki curl \
              -s \
              -o - \
              --cacert $SHARED/ca_signing.crt \
              --json @$SHARED/request.json \
              https://pki.example.com:8443/ca/v2/certrequests \
              | tee response.json

          # request should be rejected
          jq -r '.entries[0].requestStatus, .entries[0].errorMessage' response.json > actual

          cat > expected <<EOF
          rejected
          The password must be at least 20 characters
          EOF

          diff expected actual

      - name: Submit request with numeric password
        run: |
          # create request with numeric password for user test3
          cat template.json \
              | jq '.Input[0].Attribute[0].Value|="1234567890246801357938"' \
              | jq '.Input[1].Attribute[0].Value|="test3"' \
              | tee request.json

          # submit request
          docker exec pki curl \
              -s \
              -o - \
              --cacert $SHARED/ca_signing.crt \
              --json @$SHARED/request.json \
              https://pki.example.com:8443/ca/v2/certrequests \
              | tee response.json

          # request should be rejected
          jq -r '.entries[0].requestStatus, .entries[0].errorMessage' response.json > actual

          cat > expected <<EOF
          rejected
          The password requires at least 2 upper case letter(s)
          EOF

          diff expected actual

      - name: "Disable PKCS #12 password constraint"
        run: |
          # disable p12ExportPasswordConstraintImpl
          docker exec pki sed -i \
              's/^policyset.userCertSet.list=1,10,2,3,4,5,6,7,8,9,11/policyset.userCertSet.list=1,10,2,3,4,5,6,7,8,9/' \
              /etc/pki/pki-tomcat/ca/profiles/ca/caServerKeygen_UserCert.cfg

          docker exec pki pki-server ca redeploy --wait

      - name: Submit request with minimal password
        run: |
          # create request with minimal password for user test4
          cat template.json \
              | jq '.Input[0].Attribute[0].Value|="1"' \
              | jq '.Input[1].Attribute[0].Value|="test4"' \
              | tee request.json

          # submit request
          docker exec pki curl \
              -s \
              -o - \
              --cacert $SHARED/ca_signing.crt \
              --json @$SHARED/request.json \
              https://pki.example.com:8443/ca/v2/certrequests \
              | tee response.json

          # request should be pending
          jq -r '.entries[0].requestStatus' response.json > actual

          cat > expected << EOF
          pending
          EOF

          diff expected actual

          # approve request
          REQUEST_ID=$(jq -r '.entries[0].requestID' response.json)
          docker exec pki pki \
              -n admin \
              ca-cert-request-approve \
              --force \
              $REQUEST_ID \
              | tee output

          # export cert
          CERT_ID=$(sed -n 's/^\s*Certificate ID:\s*\(\S*\)$/\1/p' output)
          docker exec pki pki ca-cert-export \
              --output-file $SHARED/test4.crt \
              $CERT_ID
          echo "Cert ID: $CERT_ID"
          echo $CERT_ID > test4.cert_id

      - name: Find generated key
        run: |
          # find generated key by owner
          docker exec pki pki \
              -n admin \
              kra-key-find \
              --owner UID=test4 \
              | tee output

          KEY_ID=$(sed -n 's/^\s*Key ID:\s*\(\S*\)$/\1/p' output)
          echo "Key ID: $KEY_ID"
          echo $KEY_ID > test4.key_id

      - name: Retrieve generated key
        run: |
          KEY_ID=$(cat test4.key_id)
          echo "Key ID: $KEY_ID"

          # export cert into Base64-encoded format
          BASE64_CERT=$(openssl x509 -in test4.crt -outform DER | base64 --wrap=0)
          echo "Cert: $BASE64_CERT"

          # create retrieval request with key ID, cert, and passphrase
          cat > request.json <<EOF
          {
            "ClassName" : "com.netscape.certsrv.key.KeyRecoveryRequest",
            "Attributes" : {
              "Attribute" : [ {
                "name" : "keyId",
                "value" : "$KEY_ID"
              }, {
                "name" : "certificate",
                "value" : "$BASE64_CERT"
              }, {
                "name" : "passphrase",
                "value" : "Secret.123"
              } ]
            }
          }
          EOF

          # retrieve cert and key into PKCS #12 file
          docker exec pki pki \
              -n admin \
              kra-key-retrieve \
              --input $SHARED/request.json \
              --transport kra_transport \
              --output-data test4.p12

          docker exec pki pki pkcs12-cert-find \
              --pkcs12 test4.p12 \
              --password Secret.123

          docker exec pki pki pkcs12-key-find \
              --pkcs12 test4.p12 \
              --password Secret.123

      - name: Import generated key
        run: |
          # import PKCS #12 file into NSS database with the passphrase
          docker exec pki pki \
              -d nssdb \
              pkcs12-import \
              --pkcs12 test4.p12 \
              --password Secret.123

          # remove retrieved cert from NSS database
          docker exec pki pki \
              -d nssdb \
              nss-cert-del \
              UID=test4

          # import original cert into NSS database
          docker exec pki pki \
              -d nssdb \
              nss-cert-import \
              --cert $SHARED/test4.crt \
              test4

          # the original cert should match the retrieved key (trust flags must be u,u,u)
          docker exec pki pki \
              -d nssdb \
              nss-cert-show \
              test4 \
              | tee output

          cat > expected << EOF
          u,u,u
          EOF

          sed -n 's/^\s*Trust Flags:\s*\(\S\+\)$/\1/p' output > actual

          diff expected actual

      - name: Remove KRA
        run: docker exec pki pkidestroy -s KRA -v

      - name: Remove CA
        run: docker exec pki pkidestroy -s CA -v

      - name: Check for PKI core dumps
        if: failure()
        run: |
          docker exec pki ls -l
          docker exec pki find / -path /proc -prune -o -name "hs_err_pid*.log" -exec cat {} \;

      - name: Check PKI server systemd journal
        if: always()
        run: |
          docker exec pki journalctl -x --no-pager -u pki-tomcatd@pki-tomcat.service

      - name: Check PKI server access log
        if: always()
        run: |
          docker exec pki find /var/log/pki/pki-tomcat -name "localhost_access_log.*" -exec cat {} \;

      - name: Check CA debug log
        if: always()
        run: |
          docker exec pki find /var/lib/pki/pki-tomcat/logs/ca -name "debug.*" -exec cat {} \;

      - name: Check KRA debug log
        if: always()
        run: |
          docker exec pki find /var/lib/pki/pki-tomcat/logs/kra -name "debug.*" -exec cat {} \;
