name: PKI NSS CLI with SoftHSM
# This test will perform the following operations:
# - create NSS database
# - create CA signing key
# - create CA signing CSR with existing key
# - issue self-signed CA signing cert
# - import CA signing cert
# - create SSL server CSR with new key
# - issue SSL server cert
# - import SSL server cert
# - remove SSL server cert and key
# - create audit signing CSR with new key
# - issue audit signing cert
# - import audit signing cert
# - remove audit signing cert and key
# - remove CA signing cert and key

on: workflow_call

env:
  DS_IMAGE: ${{ vars.DS_IMAGE || 'quay.io/389ds/dirsrv' }}

jobs:
  # https://github.com/dogtagpki/pki/wiki/PKI-NSS-CLI
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SHARED: /tmp/workdir/pki
    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Retrieve PKI images
        uses: actions/cache@v5
        with:
          key: pki-images-${{ github.sha }}
          path: pki-images.tar

      - name: Load PKI images
        run: docker load --input pki-images.tar

      - name: Set up runner container
        run: |
          tests/bin/runner-init.sh pki
        env:
          HOSTNAME: pki.example.com

      - name: Create SoftHSM token
        run: |
          docker exec pki dnf install -y softhsm opendnssec

          # create password file for HSM
          echo "Secret.HSM" > password.hsm

          docker exec pki softhsm2-util --init-token \
              --label HSM \
              --so-pin $(cat password.hsm) \
              --pin $(cat password.hsm) \
              --free

          docker exec pki softhsm2-util --show-slots

          docker exec pki modutil -nocertdb -list

      - name: Create NSS database
        run: |
          # create password file for internal token
          echo "Secret.123" > password.txt

          # create password config
          echo "internal=$(cat password.txt)" > password.conf
          echo "hardware-HSM=$(cat password.hsm)" >> password.conf

          # create password-protected NSS database
          docker exec pki pki \
              -C $SHARED/password.txt \
              nss-create

      - name: Create CA signing key
        run: |
          cat password.hsm | docker exec -i pki pki \
              --token HSM \
              nss-key-create \
              --key-id-file $SHARED/ca_signing.key-id

      - name: Check CA signing key in internal token
        run: |
          docker exec pki certutil -K \
              -d /root/.dogtag/nssdb \
              -f $SHARED/password.txt \
              | tee output

          # key should not exist
          sed -n 's/^<.*>\s\+\(\S\+\)\s\+\S\+\s\+.*$/\1/p' output > actual

          diff /dev/null actual

          # list all keys
          docker exec pki pki \
              -f $SHARED/password.conf \
              nss-key-find \
              | tee output

          # key should not exist
          sed -n 's/\s*Type:\s*\(\S\+\)\s*$/\1/p' output > actual

          diff /dev/null actual

      - name: Check CA signing key in HSM
        run: |
          docker exec pki certutil -K \
              -d /root/.dogtag/nssdb \
              -f $SHARED/password.hsm \
              -h HSM \
              | tee output

          # key type should be RSA
          echo "rsa" > expected
          sed -n 's/^<.*>\s\+\(\S\+\)\s\+\S\+\s\+.*$/\1/p' output > actual

          diff expected actual

          # list all keys
          docker exec pki pki \
              -f $SHARED/password.conf \
              --token HSM \
              nss-key-find \
              | tee output

          # key type should be RSA
          echo "RSA" > expected
          sed -n 's/\s*Type:\s*\(\S\+\)\s*$/\1/p' output > actual

          diff expected actual

          # check key with inline password
          docker exec pki pki \
              -c $(cat password.hsm) \
              --token HSM \
              nss-key-show \
              --key-id-file $SHARED/ca_signing.key-id \
              | tee output

          # key type should be RSA
          echo "RSA" > expected
          sed -n 's/\s*Type:\s*\(\S\+\)\s*$/\1/p' output > actual

          diff expected actual

          # check key with password file
          docker exec pki pki \
              -C $SHARED/password.hsm \
              --token HSM \
              nss-key-show \
              --key-id-file $SHARED/ca_signing.key-id \
              | tee output

          # key type should be RSA
          echo "RSA" > expected
          sed -n 's/\s*Type:\s*\(\S\+\)\s*$/\1/p' output > actual

          diff expected actual

          # check key with password config
          docker exec pki pki \
              -f $SHARED/password.conf \
              --token HSM \
              nss-key-show \
              --key-id-file $SHARED/ca_signing.key-id \
              | tee output

          # key type should be RSA
          echo "RSA" > expected
          sed -n 's/\s*Type:\s*\(\S\+\)\s*$/\1/p' output > actual

          diff expected actual

          # check key with password prompt
          cat password.hsm | docker exec -i pki pki \
              --token HSM \
              nss-key-show \
              --key-id-file $SHARED/ca_signing.key-id \
              | tee output

          # key type should be RSA
          echo "RSA" > expected
          sed -n 's/\s*Type:\s*\(\S\+\)\s*$/\1/p' output > actual

          diff expected actual

      - name: Create CA signing CSR with existing key
        run: |
          cat password.hsm | docker exec -i pki pki \
              --token HSM \
              nss-cert-request \
              --key-id-file $SHARED/ca_signing.key-id \
              --subject "CN=Certificate Authority" \
              --ext /usr/share/pki/server/certs/ca_signing.conf \
              --csr ca_signing.csr

          docker exec pki openssl req -text -noout -in ca_signing.csr

      - name: Issue self-signed CA signing cert
        run: |
          cat password.hsm | docker exec -i pki pki \
              --token HSM \
              nss-cert-issue \
              --csr ca_signing.csr \
              --ext /usr/share/pki/server/certs/ca_signing.conf \
              --cert ca_signing.crt

          docker exec pki openssl x509 -text -noout -in ca_signing.crt

      - name: Import CA signing cert
        run: |
          # this command doesn't prompt for a password but it requires
          # the passwords to the internal token and HSM in order to set
          # the trust flags properly
          docker exec pki pki \
              -f $SHARED/password.conf \
              nss-cert-import \
              --cert ca_signing.crt \
              --trust "CT,C,C" \
              HSM:ca_signing

      - name: Check CA signing cert in internal token
        run: |
          docker exec pki certutil -L \
              -d /root/.dogtag/nssdb \
              -f $SHARED/password.txt \
              | tee output

          # trust flags should be CT,C,C
          echo "CT,C,C" > expected
          sed -n 's/^ca_signing\s*\(\S\+\)\s*$/\1/p' output > actual

          diff expected actual

          # check cert with nickname
          docker exec pki pki \
              -f $SHARED/password.conf \
              nss-cert-show \
              ca_signing \
              | tee output

          # trust flags should be CT,C,C
          echo "CT,C,C" > expected
          sed -n 's/\s*Trust Flags:\s*\(\S\+\)\s*$/\1/p' output > actual

          diff expected actual

      - name: Check CA signing cert in HSM
        run: |
          docker exec pki certutil -L \
              -d /root/.dogtag/nssdb \
              -f $SHARED/password.hsm \
              -h HSM \
              | tee output

          # trust flags should be CTu,Cu,Cu
          echo "CTu,Cu,Cu" > expected
          sed -n 's/^HSM:ca_signing\s*\(\S\+\)\s*$/\1/p' output > actual

          diff expected actual

          # check cert with nickname
          docker exec pki pki \
              -f $SHARED/password.conf \
              --token HSM \
              nss-cert-show \
              HSM:ca_signing \
              | tee output

          # trust flags should be CTu,Cu,Cu
          echo "CTu,Cu,Cu" > expected
          sed -n 's/\s*Trust Flags:\s*\(\S\+\)\s*$/\1/p' output > actual

          diff expected actual

      - name: Create SSL server CSR with new key
        run: |
          cat password.hsm | docker exec -i pki pki \
              --token HSM \
              nss-cert-request \
              --subject "CN=pki.example.com" \
              --ext /usr/share/pki/server/certs/sslserver.conf \
              --csr sslserver.csr

          # CSR should be created
          docker exec pki openssl req -text -noout -in sslserver.csr

      - name: Issue SSL server cert
        run: |
          cat password.hsm | docker exec -i pki pki \
              --token HSM \
              nss-cert-issue \
              --issuer HSM:ca_signing \
              --csr sslserver.csr \
              --ext /usr/share/pki/server/certs/sslserver.conf \
              --cert sslserver.crt

          docker exec pki openssl x509 -text -noout -in sslserver.crt

      - name: Import SSL server cert
        run: |
          # this command doesn't prompt for a password
          docker exec pki pki \
              nss-cert-import \
              --cert sslserver.crt \
              HSM:sslserver

      - name: Check SSL server key in internal token
        run: |
          docker exec pki pki \
              -f $SHARED/password.conf \
              nss-key-find \
              --nickname sslserver \
              | tee output

          # key should not exist
          diff /dev/null output

      - name: Check SSL server key in HSM
        run: |
          docker exec pki pki \
              -f $SHARED/password.conf \
              --token HSM \
              nss-key-find \
              --nickname HSM:sslserver | tee output

          # key type should be RSA
          echo rsa > expected
          sed -n 's/\s*Type:\s*\(\S\+\)\s*$/\L\1/p' output > actual

          diff expected actual

      - name: Check SSL server cert in internal token
        run: |
          docker exec pki certutil -L \
              -d /root/.dogtag/nssdb \
              | tee output

          # trust flags should be ,,
          echo ",," > expected
          sed -n 's/^sslserver\s*\(\S\+\)\s*$/\1/p' output > actual

          diff expected actual

          docker exec pki pki \
              nss-cert-show \
              sslserver \
              | tee output

          # trust flags should be ,,
          echo ",," > expected
          sed -n 's/\s*Trust Flags:\s*\(\S\+\)\s*$/\1/p' output > actual

          diff expected actual

      - name: Check SSL server cert in HSM
        run: |
          docker exec pki certutil -L \
              -d /root/.dogtag/nssdb \
              -f $SHARED/password.hsm \
              -h HSM \
              | tee output

          # trust flags should be u,u,u
          echo "u,u,u" > expected
          sed -n 's/^HSM:sslserver\s*\(\S\+\)\s*$/\1/p' output > actual

          diff expected actual

          docker exec pki pki \
              -f $SHARED/password.conf \
              --token HSM \
              nss-cert-show \
              HSM:sslserver | tee output

          # trust flags should be u,u,u
          echo "u,u,u" > expected
          sed -n 's/\s*Trust Flags:\s*\(\S\+\)\s*$/\1/p' output > actual

          diff expected actual

      - name: Remove SSL server cert from internal token
        run: |
          cat password.txt | docker exec -i pki pki \
              nss-cert-del \
              sslserver \
              --remove-key

          docker exec pki certutil -L \
              -d /root/.dogtag/nssdb \
              | tee output

          # cert should not exist
          echo "ca_signing CT,C,C" > expected
          sed -n -e '1,4d' -e 's/^\(.*\S\)\s\+\(\S\+\)\s*$/\1 \2/p' output > actual

          diff expected actual

          docker exec pki certutil -K \
              -d /root/.dogtag/nssdb \
              -f $SHARED/password.txt \
              | tee output

          # key should not exist
          sed -n 's/^<.*>\s\+\S\+\s\+\S\+\s\+\(.*\)$/\1/p' output | sort > actual

          diff /dev/null actual

          docker exec pki pki \
              nss-cert-show \
              sslserver \
              > >(tee stdout) 2> >(tee stderr >&2) || true

          # cert should not exist
          cat > expected << EOF
          ERROR: Certificate not found: sslserver
          EOF

          diff expected stderr

          docker exec pki pki \
              nss-cert-export \
              sslserver \
              > >(tee stdout) 2> >(tee stderr >&2) || true

          # cert should not exist
          cat > expected << EOF
          ERROR: Certificate not found: sslserver
          EOF

          diff expected stderr

      - name: Remove SSL server cert and key from HSM
        run: |
          cat password.hsm | docker exec -i pki pki \
              nss-cert-del \
              HSM:sslserver \
              --remove-key

          docker exec pki certutil -L \
              -d /root/.dogtag/nssdb \
              -f $SHARED/password.hsm \
              -h HSM \
              | tee output

          # cert should be removed
          echo "HSM:ca_signing CTu,Cu,Cu" > expected
          sed -n -e '1,4d' -e 's/^\(.*\S\)\s\+\(\S\+\)\s*$/\1 \2/p' output > actual
          diff expected actual

          docker exec pki certutil -K \
              -d /root/.dogtag/nssdb \
              -f $SHARED/password.hsm \
              -h HSM \
              | tee output

          # key should be removed
          echo "HSM:ca_signing" > expected
          sed -n 's/^<.*>\s\+\S\+\s\+\S\+\s\+\(.*\)$/\1/p' output | sort > actual
          diff expected actual

          docker exec pki pki \
              -f $SHARED/password.conf \
              nss-cert-show \
              HSM:sslserver \
              > >(tee stdout) 2> >(tee stderr >&2) || true

          # cert should be removed
          cat > expected << EOF
          ERROR: Certificate not found: HSM:sslserver
          EOF

          diff expected stderr

          docker exec pki pki \
              -f $SHARED/password.conf \
              nss-cert-export \
              HSM:sslserver \
              > >(tee stdout) 2> >(tee stderr >&2) || true

          # cert should be removed
          cat > expected << EOF
          ERROR: Certificate not found: HSM:sslserver
          EOF

          diff expected stderr

      - name: Create audit signing CSR with new key
        run: |
          cat password.hsm | docker exec -i pki pki \
              --token HSM \
              nss-cert-request \
              --subject "CN=Audit Signing Certificate" \
              --ext /usr/share/pki/server/certs/audit_signing.conf \
              --csr audit_signing.csr

          docker exec pki openssl req -text -noout -in audit_signing.csr

      - name: Issue audit signing cert
        run: |
          cat password.hsm | docker exec -i pki pki \
              --token HSM \
              nss-cert-issue \
              --issuer HSM:ca_signing \
              --csr audit_signing.csr \
              --ext /usr/share/pki/server/certs/audit_signing.conf \
              --cert audit_signing.crt

          docker exec pki openssl x509 -text -noout -in audit_signing.crt

      - name: Import audit signing cert
        run: |
          # this command doesn't prompt for a password
          docker exec pki pki \
              nss-cert-import \
              --cert audit_signing.crt \
              HSM:audit_signing

      - name: Check audit signing key
        run: |
          docker exec pki certutil -K \
              -d /root/.dogtag/nssdb \
              -f $SHARED/password.hsm \
              -h HSM \
              | tee output

          # key type should be RSA
          echo "rsa" > expected
          sed -n 's/^<.*>\s\+\(\S\+\)\s\+\S\+\s\+HSM:audit_signing$/\1/p' output > actual

          diff expected actual

          docker exec pki pki \
              -f $SHARED/password.conf \
              nss-key-find \
              --nickname HSM:audit_signing | tee output

          # key type should be RSA
          echo "RSA" > expected
          sed -n 's/\s*Type:\s*\(\S\+\)\s*$/\1/p' output > actual

          diff expected actual

      - name: Check audit signing cert
        run: |
          docker exec pki certutil -L \
              -d /root/.dogtag/nssdb \
              -f $SHARED/password.hsm \
              -h HSM \
              | tee output

          # trust flags should be u,u,u
          echo "u,u,u" > expected
          sed -n 's/^HSM:audit_signing\s*\(\S\+\)\s*$/\1/p' output > actual

          diff expected actual

          docker exec pki pki \
              -f $SHARED/password.conf \
              nss-cert-show \
              HSM:audit_signing | tee output

          # trust flags should be u,u,u
          echo "u,u,u" > expected
          sed -n 's/\s*Trust Flags:\s*\(\S\+\)\s*$/\1/p' output > actual

          diff expected actual

      - name: Modify audit signing cert trust flags
        run: |
          # this command doesn't prompt for a password but it requires
          # the passwords to the internal token and HSM in order to set
          # the trust flags properly
          docker exec -i pki pki \
              -f $SHARED/password.conf \
              --token HSM \
              nss-cert-mod \
              --trust-flags ",,P" \
              HSM:audit_signing

      - name: Check audit signing cert trust flags in internal token
        run: |
          docker exec pki certutil -L \
              -d /root/.dogtag/nssdb \
              -f $SHARED/password.txt \
              | tee output

          # trust flags should be be ,,P
          echo ",,P" > expected
          sed -n 's/^audit_signing\s*\(\S\+\)\s*$/\1/p' output > actual

          diff expected actual

          docker exec pki pki \
              -f $SHARED/password.conf \
              nss-cert-show \
              audit_signing \
              | tee output

          # trust flags should be ,,P
          echo ",,P" > expected
          sed -n 's/\s*Trust Flags:\s*\(\S\+\)\s*$/\1/p' output > actual

          diff expected actual

      - name: Check audit signing cert trust flags in HSM
        run: |
          docker exec pki certutil -L \
              -d /root/.dogtag/nssdb \
              -f $SHARED/password.hsm \
              -h HSM \
              | tee output

          # trust flags should be u,u,Pu
          echo "u,u,Pu" > expected
          sed -n 's/^HSM:audit_signing\s*\(\S\+\)\s*$/\1/p' output > actual

          diff expected actual

          docker exec pki pki \
              -f $SHARED/password.conf \
              nss-cert-show \
              HSM:audit_signing \
              | tee output

          # trust flags should be u,u,Pu
          echo "u,u,Pu" > expected
          sed -n 's/\s*Trust Flags:\s*\(\S\+\)\s*$/\1/p' output > actual

          diff expected actual

      - name: Remove audit signing cert from internal token
        run: |
          # this command doesn't prompt for a password
          docker exec pki pki \
              nss-cert-del \
              audit_signing

          docker exec pki certutil -L \
              -d /root/.dogtag/nssdb \
              -f $SHARED/password.txt \
              | tee output

          # cert should be removed
          echo "ca_signing CT,C,C" > expected
          sed -n -e '1,4d' -e 's/^\(.*\S\)\s\+\(\S\+\)\s*$/\1 \2/p' output > actual

          diff expected actual

      - name: Remove audit signing cert and key from HSM
        run: |
          cat password.hsm | docker exec -i pki pki \
              --token HSM \
              nss-cert-del \
              HSM:audit_signing \
              --remove-key

          docker exec pki certutil -L \
              -d /root/.dogtag/nssdb \
              -f $SHARED/password.hsm \
              -h HSM \
              | tee output

          # cert should be removed
          echo "HSM:ca_signing CTu,Cu,Cu" > expected
          sed -n -e '1,4d' -e 's/^\(.*\S\)\s\+\(\S\+\)\s*$/\1 \2/p' output > actual

          diff expected actual

          docker exec pki certutil -K \
              -d /root/.dogtag/nssdb \
              -f $SHARED/password.hsm \
              -h HSM \
              | tee output

          # key should be removed
          echo "HSM:ca_signing" > expected
          sed -n 's/^<.*>\s\+\S\+\s\+\S\+\s\+\(.*\)$/\1/p' output | sort > actual

          diff expected actual

      - name: Remove CA signing cert from internal token
        run: |
          # this command doesn't prompt for a password
          docker exec pki pki \
              nss-cert-del \
              ca_signing

          docker exec pki certutil -L \
              -d /root/.dogtag/nssdb \
              -f $SHARED/password.txt \
              | tee output

          # cert should be removed
          sed -n -e '1,4d' -e 's/^\(.*\S\)\s\+\(\S\+\)\s*$/\1 \2/p' output > actual

          diff /dev/null actual

      - name: Remove CA signing cert from HSM
        run: |
          cat password.hsm | docker exec -i pki pki \
              --token HSM \
              nss-cert-del \
              HSM:ca_signing

          docker exec pki certutil -L \
              -d /root/.dogtag/nssdb \
              -f $SHARED/password.hsm \
              -h HSM \
              | tee output

          # cert should be removed
          sed -n -e '1,4d' -e 's/^\(.*\S\)\s\+\(\S\+\)\s*$/\1 \2/p' output > actual

          diff /dev/null actual

          docker exec pki certutil -K \
              -d /root/.dogtag/nssdb \
              -f $SHARED/password.hsm \
              -h HSM \
              | tee output

          # key should not be removed
          echo "(orphan)" > expected
          sed -n 's/^<.*>\s\+\S\+\s\+\S\+\s\+\(.*\)$/\1/p' output | sort > actual

          diff expected actual

      - name: Remove CA signing key
        run: |
          cat password.hsm | docker exec -i pki pki \
              --token HSM \
              nss-key-del \
              --key-id-file $SHARED/ca_signing.key-id

          docker exec pki certutil -K \
              -d /root/.dogtag/nssdb \
              -f $SHARED/password.hsm \
              -h HSM \
              | tee output

          # key should be removed
          sed -n 's/^<.*>\s\+\S\+\s\+\S\+\s\+\(.*\)$/\1/p' output | sort > actual

          diff /dev/null actual

      - name: Remove SoftHSM token
        run: |
          docker exec pki softhsm2-util --delete-token --token HSM
