#common to all subsystems
CLIENT_PKCS12_PASSWORD='Secret123'
BACKUP_PASSWORD = 'Secret123'
#CA Instance
CA_HTTPS_PORT = 8443
CA_HTTP_PORT = 8080
CA_AJP_PORT = 8009
CA_TOMCAT_PORT = 8005
CA_CLIENT_DIR = '/opt/FoobarCA'
CA_INSTANCE_NAME = 'FoobarCA'
SECURITY_DOMAIN_PASSWORD = 'Secret123'
CA_PASSWORD = 'Secret123'
CA_SECURITY_DOMAIN_NAME = 'Foobar Org'
CA_ADMIN_USERNAME = 'caadmin'
#KRA Instance
KRA_INSTANCE_NAME = 'FoobarKRA'
KRA_HTTPS_PORT = 12443
KRA_HTTP_PORT = 12080
KRA_AJP_PORT = 12009
KRA_TOMCAT_PORT = 12005
KRA_PASSWORD = 'Secret123'
KRA_CLIENT_DIR = '/opt/FoobarKRA'
#OCSP Instance
OCSP_INSTANCE_NAME = 'FoobarOCSP'
OCSP_HTTPS_PORT = 14443
OCSP_HTTP_PORT = 14080
OCSP_AJP_PORT = 14009
OCSP_TOMCAT_PORT = 14005
OCSP_PASSWORD = 'Secret123'
OCSP_CLIENT_DIR = '/opt/FoobarOCSP'
#TKS Instance
TKS_INSTANCE_NAME = 'FoobarTKS'
TKS_HTTPS_PORT = 15443
TKS_HTTP_PORT = 15080
TKS_AJP_PORT = 15009
TKS_TOMCAT_PORT = 15005
TKS_PASSWORD = 'Secret123'
TKS_CLIENT_DIR = '/opt/FoobarTKS'
#TPS instance
TPS_INSTANCE_NAME = 'FoobarTPS'
TPS_HTTPS_PORT = 16443
TPS_HTTP_PORT = 16080
TPS_AJP_PORT = 16009
TPS_TOMCAT_PORT = 16005
TPS_PASSWORD = 'Secret123'
TPS_CLIENT_DIR = '/opt/FoobarTPS'
#clone CA instance
CLONECA_HTTPS_PORT = 8443
CLONECA_HTTP_PORT = 8080
CLONECA_AJP_PORT = 8009
CLONECA_TOMCAT_PORT = 8005
CLONECA_CLIENT_DIR = '/opt/FoobarCloneCA'
CLONECA_INSTANCE_NAME = 'FoobarCloneCA'
CLONECA_PASSWORD = 'Secret123'

#clone KRA instance
CLONEKRA_INSTANCE_NAME = 'FoobarCloneKRA'
CLONEKRA_HTTPS_PORT = 12443
CLONEKRA_HTTP_PORT = 12080
CLONEKRA_AJP_PORT = 12009
CLONEKRA_TOMCAT_PORT = 12005
CLONEKRA_PASSWORD = 'Secret123'
CLONEKRA_CLIENT_DIR = '/opt/FoobarCloneKRA'

#clone OCSP Instance
CLONEOCSP_INSTANCE_NAME = 'FoobarCloneOCSP'
CLONEOCSP_HTTPS_PORT = 14443
CLONEOCSP_HTTP_PORT = 14080
CLONEOCSP_AJP_PORT = 14009
CLONEOCSP_TOMCAT_PORT = 14005
CLONEOCSP_PASSWORD = 'Secret123'
CLONEOCSP_CLIENT_DIR = '/opt/FoobarCloneOCSP'

#clone TKS instance
CLONETKS_INSTANCE_NAME = 'FoobarCloneTKS'
CLONETKS_HTTPS_PORT = 15443
CLONETKS_HTTP_PORT = 15080
CLONETKS_AJP_PORT = 15009
CLONETKS_TOMCAT_PORT = 15005
CLONETKS_PASSWORD = 'Secret123'
CLONETKS_CLIENT_DIR = '/opt/FoobarCloneTKS'

#clone TPS Instance
CLONETPS_INSTANCE_NAME = 'FoobarCloneTPS'
CLONETPS_HTTPS_PORT = 16443
CLONETPS_HTTP_PORT = 16080
CLONETPS_AJP_PORT = 16009
CLONETPS_TOMCAT_PORT = 16005
CLONETPS_PASSWORD = 'Secret123'
CLONETPS_CLIENT_DIR = '/opt/FoobarCloneTPS'
